### ISSUE TITLE
Track-specific lists of exercises to implement

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#1]
We've been creating issues with lists of checkboxes for language tracks to keep track of which exercises should be implemented. The idea was to check things off, but this hasn't been working very well and is cumbersome.

e.g.: https://github.com/exercism/xperl6/issues/1

Not too long ago we started adding some endpoints to the API that can show dynamically which exercises that have not been implemented.

e.g.: http://x.exercism.io/v3/tracks/perl6/todo

That dynamic list is based on whatever has been deployed to the API, which isn't always completely up-to-date (I deploy more-or-less daily, but occasionally stuff happens and it can take longer).

There are a few options, I think, to improve this process:

1. Use the todo endpoint as is; create an issue about "add more exercises" and explain how to use the endpoint.
2. Create and endpoint that uses the GitHub API to look at what's available in master at any point in time. We have the inverse of this (http://synopsis.exercism.io/, https://github.com/exercism/synopsis), but I don't use it; I don't know if anyone does.
3. Based on whichever endpoint we decide to use, create a page on exercism.io that is nice and helpful and shows people everything they need in order to choose an exercise and do the work to implement it.

My suggestion would be to start with a very simple improvement: close all of the existing checklist issues, replace them with a single issue that explains how to use the current existing endpoint to figure out what to implement. We could make an instruction to create a WIP PR (and how to do that) to "claim" an issue so that two people don't start working on the same thing.

Then as a second step we could implement the contribute/todo feature/page on the website itself, and the "todo" issue in the track could point to that page instead.

What do you think @roseaboveit?

**Comment by roseaboveit** [comment]
I'm not following 100% but the part that is directly related to my issue at hand has definitely been addressed. I agree that since there is another way we are tracking these tasks and their completion status through the second method that we can close all tasks related to the first method with a helpful message about how to go about finding tasks to work on in another way. I don't think this has to be a new issue but this could involve updating the contributing guidelines if this is not otherwise handled there.

I'd like to discuss further the 2nd step option. That sounds like a feature that could be fleshed out and made into a development task. I'm uncertain exactly what is happening with this recommendation but I will come back to it either this evening or tomorrow and see if it makes more sense to me.

**Comment by kytrinyx** [comment]
Agreed, we should put this in the contributing guidelines, and then close the issues with a link to the correct place.

I have a placeholder for it here: https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#porting-an-exercise-to-another-language-track

For the 2nd step, I think that it can be turned into a development task, we just need to figure out what we think would make sense. I'm thinking something like this:

On each language page, e.g. http://exercism.io/languages/go there would be a section/menu option "implement new exercises". It would have to be linkable (right now you can only link to the page, not the sub-items, and it's important that we be able to link directly to the "implement new exercises" section or page).

On that page it would have a friendly explanation, it would link to the relevant section in the contributing guide, and then it would list all of the exercises that we have a generic problem description for, but that hasn't yet been implemented in the language. For each problem we can link to the README and other metadata for the problem, and we can also link to the shared test data (if there is some, e.g. https://github.com/exercism/x-common/blob/master/clock.json), and also we can show you a list of all the languages that have implemented that exercise, and we can link you to the directory on GitHub so you can use those test suites for inspiration). 

That page would have the most up-to-date information (based on the API endpoint).

**Comment by kytrinyx** [comment]
As I see it there are four todo items that need to happen in order to close this issue:

1. Describe the desired process in the CONTRIBUTING guide using the API endpoint directly.
2. Come up with a short, friendly text that we can use to close the existing checklist issues, linking to the guide.
3. Close the issues (here's a search that will give us a good place to start to find those issues: https://github.com/search?utf8=%E2%9C%93&q=user%3Aexercism+is%3Aissue+is%3Aopen+implement+exercises&type=Issues&ref=searchresults)
4. Create the development task for v2 that would expose the data from the API endpoint in a user-friendly way on the website itself.

**Comment by roseaboveit** [comment]
I think that covers it from my perspective.

So... I don't actually know... how would be best to use the API endpoint directly? I'd be happy to break it down into small user friendly pieces once I understand it myself. Or someone else can do it if they already know.

I'm thinking of something like this for the friendly text:

"This method of keeping track of exercises to be implemented wasn't working for us. We have a new process that you can use to find exercises to implement. You can read all about it here(link). Thanks for your interest in expanding the exercise base for this language!"

**Comment by kytrinyx** [comment]
That's a good, friendly text.

I'll write up the details on how to use the endpoint directly.

**Comment by kytrinyx** [comment]
I've described how to use the endpoint here: https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#porting-an-exercise-to-another-language-track

**Comment by kytrinyx** [comment]
One of the issues on exercism.io morphed to become the development task for this: https://github.com/exercism/exercism.io/issues/2762

**Comment by kytrinyx** [comment]
I'm going to use a slightly tweaked version of the friendly text to close the related issues:

```
This method of keeping track of exercises to be implemented wasn't working for us. We have a new process that you can use to find exercises to implement. You can read all about it [here[(https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#porting-an-exercise-to-another-language-track).

We're closing this issue in favor of the process described in the Contributing guide linked to above.

Thanks!
```

**Comment by LegalizeAdulthood** [comment]
`http://x.exercism.io/tracks/cpp/todo` gives `{"error":"No implementation for todo in track 'cpp'"}` so I'm not sure how this is supposed to work...

**Comment by LegalizeAdulthood** [comment]
Oh, seems I used the wrong URL `http://x.exercism.io/v3/tracks/cpp/todo` returned something useful.

**Comment by kytrinyx** [comment]
Oh, yeah it's the v3 link.

**Comment by kytrinyx** [comment]
We've got both the api endpoint as well as a page on the site that lists all the exercises to implement, e.g.: http://exercism.io/languages/java/contribute
