### ISSUE TITLE
Is the custom-set test set too long?

### ISSUE THREAD

**Issue by IanWhitney** [exercism/discussions#10]
I'm working on re-working the Rust implementation so that it follows the [common test suite](https://github.com/exercism/x-common/blob/master/custom-set.json). I'm currently at 32 tests and I might be half-way through.

This seems long. It seems to be that a lot of these tests are repetitive. Or maybe they are trying to catch weird corner cases that simply aren't occurring to me.

Some examples

- Testing non-empty sets, why two tests? https://github.com/exercism/x-common/blob/master/custom-set.json#L134
- Testing element presence, why four tests? https://github.com/exercism/x-common/blob/master/custom-set.json#L176
- Subset testing appears to have lots of repetition https://github.com/exercism/x-common/blob/master/custom-set.json#L235
- Eight tests of intersection: https://github.com/exercism/x-common/blob/master/custom-set.json#L289
- And eight of Union: https://github.com/exercism/x-common/blob/master/custom-set.json#L342

I'm not a Set Theory expert, so maybe these tests are catching useful bugs, but it does seem to me that there's a lot that could be trimmed.

Thoughts?

**Comment by IanWhitney** [comment]
In most cases as soon as I get a function's first or second test to pass, all of the others pass without problem. This suggests to me that those tests aren't catching corner cases. Though they might be catching corner cases that I didn't happen to hit.

**Comment by IanWhitney** [comment]
Also, I'm wondering if the whole `mixed_types` section can just be dropped. With languages that enforce that collections contain the same types (like Rust, Haskell, etc), I'm not even sure how to go about implementing this. 

That's not to say it's not implementable, just that I have no idea how. It might be beyond the scope of the problem.

**Comment by ryanplusplus** [comment]
This is something I've noticed with a lot of the common tests. Recently I went through the Clock tests and they also seemed to be a little bit overdone. I think that some of the tests are aimed at producing NASA-grade implementations instead of producing something that can be critiqued for style.

On the other hand, the tests only need to be written once and I've never felt that a long list of tests burdened me when doing an exercise, so maybe it's better to have these bullet proof tests.

**Comment by verdammelt** [comment]
Looks like the first two groups of tests you point to are in the common 0, 1, many pattern. I don't see that is being too redundant given that we are talking about a container. I'm not seeing the duplication in the subset tests and the intersection tests look "OK" in my skimming of them.

If I were TDD-ing a set implementation I might not have all these tests myself (e.g. the intersection test that tests against empty as the first *and* second parameter) but I don't think they do much harm.

**Comment by IanWhitney** [comment]
@ryanplusplus, I'm less concerned about the work it takes maintainers to implement the exercise and more with the effect on students. There are two problems I see with big test suites, especially ones with redundant tests.

1. It makes the problem seem huge. The Rust test suite update I'm working on is currently 400 LOC, and I have about 2 dozen test left that I could implement. If I'm a student coming to that test suite, the problem space is going to seem massive.

2. Repetitive tests offer no educational value. Let's take the [8 union tests] as an example. They test

- two empty sets
- An empty set and a set with one element
- An empty set and a set with 3 elements
- An set with 2 elements and an empty set
- 2 sets with the same elements
- A set with 2 elements and a set with 1 element
- 2 sets with 2 elements
- Sets with some shared, some different elements

Assuming that a student is working their way through the tests, getting 1 to pass at a time, at which point do all of these tests pass? I'm guessing by test 5, when we check for duplicate elements. If so, what does a student learn from the remaining 3 tests?

---

I think nearly all of these test collections could be consolidated into 3 tests each. Union, Intersect, Diff and Symmetric Diff could each have 3 tests:

- 2 empty sets
- 1 empty, 1 non-empty
- 2 non-empty sets with some shared elements

**Comment by IanWhitney** [comment]
A good indication I've found with test duplication is that I can't find a way to make test names unique. If I see a set of tests named:

- `union_of_two_non_empty_sets_contains_all_unique_elements_one`
- `union_of_two_non_empty_sets_contains_all_unique_elements_two`
- `union_of_two_non_empty_sets_contains_all_unique_elements_three`

Then I figure either I'm unimaginative (possible) or the tests cover the same ground.

**Comment by petertseng** [comment]
I suppose I don't have much to say about this specific issue since I haven't worked on the `custom-set` issue in any language,. What I can see, however, is something that seems useful in general. If someone make a test json file, it will probably be useful to explain what some of the corner cases are testing (what kinds of solutions might not pass this test? why?). Or at least in the commit message.

**Comment by kytrinyx** [comment]
I would like to reduce duplication/unnecessary test cases in the tests.

(Side note: With the clock tests I added more tests, because people were submitting solutions that had bugs that the test suite (in Go) wasn't catching. This was happening often enough that I thought more tests would be helpful. It's an interesting problem in Go; I don't know what it's like in other languages).

**Comment by IanWhitney** [comment]
I'll put together a shorter test suite and put it up for a PR. See what people say.

**Comment by kytrinyx** [comment]
> Union, Intersect, Diff and Symmetric Diff could each have 3 tests [...]

@IanWhitney what about two non-empty non-intersecting sets?

**Comment by IanWhitney** [comment]
My claim that they should have 3 was wrong. I think each ended up with 4 tests. Did I cover the case you're asking about? https://github.com/IanWhitney/x-common/blob/reduce_custom_set_tests/custom-set.json#L204

**Comment by IanWhitney** [comment]
{1,2} ∩ {3,4} = {} is what you mean, right? Sorry, early morning & my set math brain is not working. That should be covered [with this test](https://github.com/IanWhitney/x-common/blob/reduce_custom_set_tests/custom-set.json#L191]

**Comment by masters3d** [comment]
Multiple tests does not bother me al long as the test suite is able to group them into a "single" function. 
https://github.com/exercism/xswift/blob/master/exercises/custom-set/CustomSetTest.swift
If my test suit forced me to break out every case into its own function then that would be burdensome.

**Comment by kytrinyx** [comment]
@IanWhitney yeah, that's what I was thinking of.
