### ISSUE TITLE
PowerShell maintainer

### ISSUE THREAD

**Issue by spuder** [exercism/discussions#100]

**Comment by spuder** [comment]
I see on twitter talks about keeping momentum going on different languages. 

I'm happy to help maintain the PowerShell language.

**Comment by Insti** [comment]
Awesome! Thanks @spuder 
Katrina will add you as soon as she can.

**Comment by kytrinyx** [comment]
:sparkles: @spuder I'm very excited to have your help on this! I've added you both to the `@exercism/powershell` team and the `@exercism/track-maintainers` team, which has commit on the x-common repository where a lot of the generic discussions happen.

Here's a bit of documentation that could help you get started: https://github.com/exercism/exercism.io/blob/master/docs/maintaining-a-track.md
If you have questions, please ask! We're all thrilled to help people help us out. 

Also, if you happen to be at a meetup or hanging out with other people who are excited about PowerShell, then this bit of documentation could help if they want to start getting involved https://github.com/exercism/exercism.io/blob/master/docs/getting-involved-in-a-track.md

:heart: 💚 💜 💛

**Comment by spuder** [comment]
Sure thing @kytrinyx happy to help.
