### ISSUE TITLE
24 Pull Requests preparations

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#101]
We're about a week out from the start of [24 Pull Requests](http://24pullrequests.com/) and it would be lovely if we could prepare in advance to make it as easy as possible to contribute, and as easy as possible to manage.

I'd prefer to focus on the language tracks and the x-common repository, since these are much easier to manage and contribute to than the main site is.

In light of the recent discussions around the status and health of the various tracks in https://github.com/exercism/discussions/issues/97, I think it would make sense to only showcase language tracks where the maintainers have the capacity to prepare issues and review contributions throughout the month of December.

**Comment by kytrinyx** [comment]
One thing we could do is create a stand-alone static website that runs on GitHub Pages at https://exercism.github.io/24pullrequests

It would require a bit of up-front work, but it could be worth it since it would mean that we could point people to a single place that describes how to contribute to Exercism for 24pullrequests.

If each track that wanted to participate in this creates a file in their `docs/` directory (e.g. `docs/24pullrequests.md`) describing the types of contributions they'd like to see, then we could use Trackler to generate the static HTML site.

**Comment by kotp** [comment]
That sounds good.  I will have time each day for this in December.

**Comment by kotp** [comment]
I have created a project with some notes on the Organization level.

Who should submit the tracks individually when ready at the 24pullrequests site?  Track Maintainers?  Or do you think just one suggestion to cover any/all?

**Comment by NobbZ** [comment]
I will take a deeper look later today, in general is like to fish for help
this way, but since my unborn is scheduled for mid of December I might
disappear all of a sudden for a week which would be disappointing for
participants.

Should I still try to set it up for erlang or leave it out?

Victor Goff <notifications@github.com> schrieb am Sa., 26. Nov. 2016 09:37:

**Comment by kytrinyx** [comment]
@kotp thank you! If we need to submit individual repositories, then probably track maintainers, but if we have a stand-alone site or a single link that we can point people to which directs them further, I think it would make more sense to just submit one link. Then again, if we want to tag projects individually with the correct language, it might make more sense to submit each track individually.

@NobbZ congratulations on the new addition to your family! I think we should only submit the Erlang track if we find a second person who can help review in December when the baby arrives.

**Comment by IanWhitney** [comment]
Could it work like Hacktober fest where we created an issue badge? I should have time to work on this on Wednesday, and I should be able to look at PRs throughout December.

**Comment by kotp** [comment]
[![Gitter](https://badges.gitter.im/24pullrequests/24pullrequests.svg)](https://gitter.im/24pullrequests/24pullrequests?utm_source=badge&utm_medium=badge&utm_campaign=exercism.io)

**Comment by kotp** [comment]
It also looks like Exercism.io is listed as a "project" on their site.  This is one point of entry, the tracks may also be good to have there as well, for those looking for specific language contributions..

**Comment by kytrinyx** [comment]
> Could it work like Hacktober fest where we created an issue badge?

Yeah, that would actually make it very easy to link to issues / search results.

> It also looks like Exercism.io is listed as a "project" on their site.

We could definitely update the link or project or whatever to be more useful to us. I agree that we should have tracks up individually for people looking for language-specific contributions to make.

**Comment by kotp** [comment]
Sounds good.  Unfortunately, it appears that permissions on the Exercism organization for me are not high enough for me to add my track(s).

**Comment by kytrinyx** [comment]
I'll add all the tracks that we want to add. This will stop being a problem if/when we move the curriculum stuff to a separate organization on GitHub.

**Comment by kytrinyx** [comment]
@kotp When you say that your permissions are not sufficient, where are you trying to add it? I don't see anything on the dashboard or the main 24pullrequests for adding repos.

**Comment by kytrinyx** [comment]
OK, I went to "your suggestions" and suggested github.com/exercism/xruby, and it's already suggested. I don't think it needs admin permissions.

**Comment by kotp** [comment]
Yep, it was the "claim" that was insufficient, but my test on the suggestion did go through about 8 hours ago.

**Comment by kotp** [comment]
Unsure if there is more to do there... than suggest it, don't know what the benefit to claiming would be.

**Comment by kytrinyx** [comment]
> I don't know what the benefit to claiming would be.

Me neither. That said, since Exercism is featured, we could do a lot by having a nice landing page that the 24pullrequests site could point to, to get everyone started.

**Comment by kotp** [comment]
I have a template up in a pull request on exercism/xruby and the track is included in reports.

![selection_003](https://cloud.githubusercontent.com/assets/16747/20781838/4377d9e0-b754-11e6-9e5d-b929a67eeef0.png)

**Comment by tejasbubane** [comment]
> since Exercism is featured, we could do a lot by having a nice landing page that the 24pullrequests site could point to, to get everyone started.

@kytrinyx I can put up a page for this. What all things would you like to have there? We already have http://exercism.io/contribute but we need some stuff catered specifically towards beginners. A few things that pop up my mind are:

* overview of what `exercism` is and the project ecosystem
* list of maintained languages tracks
* some help on adding exercises to languages - maybe [your article](https://www.sitepoint.com/exorcise-your-newbie-demons-by-contributing-to-exercism/)?
* links to gitter channels
* we can prepare a new tag for `24pullrequests` and tag those issues which we think don't need knowledge of entire project. These might not necessarily be for beginners but will be useful for people coming in from `24pullrequests`.
* link to `good-first-patch` issues
* some links for help with git and github in general


I am pretty bad at front-end stuff, so maybe I will whip some layout from `exercism` or even `24pullrequests` itself and tweak it here and there 😄

**Comment by kytrinyx** [comment]
> Could it work like Hacktober fest where we created an issue badge

@IanWhitney Yeah, a 24pullrequests label would be good, that way we can link to it from the page that @tejasbubane is offering to put up.

@tejasbubane that would be excellent!

It might be worth linking to individual documents in https://github.com/exercism/exercism.io/tree/master/docs (not all of them, maybe just [getting involved in a track](https://github.com/exercism/exercism.io/blob/master/docs/getting-involved-in-a-track.md) and [porting an exercise](https://github.com/exercism/exercism.io/blob/master/docs/porting-an-exercise.md)). We have a stub for an overview about Exercism but there's nothing in it yet. We might have something written up elsewhere (in the CONTRIBUTING.md in exercism.io? in x-common? a readme somewhere?)

**Comment by tejasbubane** [comment]
@kytrinyx Sorry. I am travelling this weekend and won't be able to work on this 😞 . 

If anyone wants to work on getting this page up, please do so (since 24pullrequests has already started). I can get back to this on Monday if no one does.

**Comment by kytrinyx** [comment]
@tejasbubane don't apologize for having a life :heart:

**Comment by tejasbubane** [comment]
@kytrinyx Here is my first take at the website: https://tejasbubane.github.io/exercism-24pullrequests/ Kept it quick and short. Please let me know if I missed something or something should be added.

PS: I am pretty bad at these frontend, design and UX things. So all suggestions are welcome! 😄

**Comment by Insti** [comment]
I like what you've done.

From a (I'm not a designer) design perspective, I'd suggest making it less pink. Having a highlight color as a background makes my eyes hurt.

From a 24PRs perspective, my 24PRs are stuff I'd be doing anyway, so I'm not sure how many new contributors a project should expect, or whether this type of page would make a difference, maybe it does. I certainly can't see it causing harm.

But given that it's probably impossible to measure the effectiveness, and 24 pull requests is 25% done, I'd say get it up ASAP.

**Comment by kytrinyx** [comment]
I agree on the pink—I think let's take that off, and then let's link to it!

Next year maybe we can take some time earlier on to think through how people land at the project, and what we can do about these sorts of month-long campaigns like 24pullrequests and hacktoberfest to help people get started.

**Comment by kotp** [comment]
Looks good to me, and yes about the pink.  I am hoping that the [projects board](https://github.com/orgs/exercism/projects) can help with this.

**Comment by tejasbubane** [comment]
Changed the pink to light red.

**Comment by kytrinyx** [comment]
Love it @tejasbubane. I'm editing the description of Exercism to point to this now. I'll check with 24 Pull Requests if we can link to it from there, as well.

**Comment by kytrinyx** [comment]
@tejasbubane If we stick this in an org by itself we could point a pretty CNAME to it.

I've made the org (x24pr) and invited you. I'll make you an admin so you can transfer it.

**Comment by kytrinyx** [comment]
Wait. I'm totally just going to clone it and push it up :-)

**Comment by kytrinyx** [comment]
OK, it's up at http://24pullrequests.exercism.io/

Accept the invite so I can make you admin, @tejasbubane. But you don't need to transfer it.

**Comment by tejasbubane** [comment]
Awesome! 🎉

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, as we're halfway through the month, and we got the great landing page from @tejasbubane
