### ISSUE TITLE
Separate exercism curriculum organization?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#103]
UPDATE: Based on the discussion and a lot of hard thinking, I'm proposing a different approach in the comment below: https://github.com/exercism/discussions/issues/103#issuecomment-306017385

-------

_The original issue:_

@petertseng suggested something interesting the other day:

What if we put all of the Exercism curriculum repositories into a separate GitHub organization?

This might make it easier to contribute to the language tracks and the x-common data, since people would be less likely to stumble across the mishmash of repositories that are unrelated to the curriculum. Each language track could be named for the language, without the leading x: e.g. `exercism-curriculum/haskell` instead of `exercism/xhaskell`, making it easier to search for (and more obvious what it is, without the cryptic x).

This might also make it easier to manage the curriculum. We could have a group of (6-10?) people who all have ownership of the organization and can add new maintainers. This might also make it easier to set up some slightly more well-defined processes for things to do with the exercises and language tracks.

GitHub already does all the redirection that we would need, so we could slowly update all the various references to the repositories and issues that are lying around.

I tested the redirection by creating a repository in the exercism org called sleep100, with one issue and one pull request in it. Then I created a new GitHub organization and moved the repository.

The old links still work:

- `https://github.com/exercism/sleep100`: https://github.com/exercism/sleep100
- `https://github.com/exercism/sleep100/issues/1`: https://github.com/exercism/sleep100/issues/1
- `https://github.com/exercism/sleep100/pull/2`: https://github.com/exercism/sleep100/pull/2

What do you think, @exercism/track-maintainers?

**Comment by ricemery** [comment]
Sounds like a good idea.

-r

**Comment by verdammelt** [comment]
Not sure if I understand. Can you clarify what you mean by 'curriculum'. How does it relate to the x-common exercise metadata, the common test data (if it exists) and language tracks?

**Comment by ErikSchierboom** [comment]
Excellent idea!

**Comment by NobbZ** [comment]
I do like the idea and fully support it. Not only that it will make life
easier for you Katrina, but it will make more clear where stuff belongs to.

Erik Schierboom <notifications@github.com> schrieb am Sa., 26. Nov. 2016
09:50:

**Comment by Insti** [comment]
:+1: to anything that gets rid of the `x`

**Comment by kytrinyx** [comment]
>  Can you clarify what you mean by 'curriculum'

@verdammelt Yeah, anything that is part of the exercise definitions. That is:

- the generic stuff that is the x-common repository
- all the language-specific repositories that contain exercise implementations

**Comment by kytrinyx** [comment]
Oh, also: I'm not at all tied to the word `curriculum`. We could name the organization whatever makes sense, I've just been thinking about it as _curriculum_ for a few years, so that was the terminology that came to mind when I wrote this.

**Comment by bernardoamc** [comment]
Excellent idea! 👍

**Comment by petertseng** [comment]
I originally thought this idea was not so good because it might have meant the track maintainers have to be added to two orgs, but if x-common moves too then everything might just make sense! Then the track maintainers would (normally) only need to be added to the curriculum organisation, very nice.

So I'm surprised to see it received well (not unpleasantly, of course).

Decision to be made: Would the discussions repo move as well?

Note that we will incur a one-time setup cost of having to transfer all the teams and the team<->repository permission mappings, but perhaps y'all consider the long-term benefits worth this one-time cost.

I imagine that as a side-effect the teams would lose their inactive maintainers since they would not be available to accept their invitations to the new org.

**Comment by petertseng** [comment]
> without the cryptic x

Actually, why is that x there in the first place anyway...?

**Comment by kytrinyx** [comment]
> Decision to be made: Would the discussions repo move as well?

Yes. I actually think we should have two discussions repos—one for the website/product/marketing/etc, and one for the curriculum (everything to do with exercises).

We might also end up with other repositories (e.g. a place to nominate maintainers and discuss track health/status).

> Note that we will incur a one-time setup cost of having to transfer all the teams and the team<->repository permission mappings

I'm happy to do this. Also it can be scripted.

> I imagine that as a side-effect the teams would lose their inactive maintainers since they would not be available to accept their invitations to the new org.

Probably. I don't think inactive maintainers are a problem per se. In the future, if they wanted to come back I think we would all be delighted to have them stop by... the problem is where we haven't had very good communication about status, and no process around how to roll off as a core maintainer.

> Actually, why is that x there in the first place anyway...?

I can't remember. I think it was so I had an easy way to filter repos, but then in the beginning there weren't many language tracks. So I don't really know why I did that.

**Comment by kytrinyx** [comment]
Having thought about this for a while, I'd now like to suggest an alternate approach:

1. every language track has "exercism-track" as the topic (I did this today). That way it is easy to find out what is a language track by searching: [`topic:exercism-track`](https://github.com/search?q=org%3Aexercism+topic%3Aexercism-track)
1. Rename each language track to just the slug of the language. There's no need to continue with the naming scheme that I made up on a whim back before I knew Exercism was going to be a real thing.
1. Rename x-common to `problem-specifications`
1. Add probot automation and/or GitHub apps for all of the things that are currently blocked because of the lack of granular permissions

This way we get to keep the unified organization, and we can still optimize both the names of the repositories and the workflows.

**Comment by Insti** [comment]
> keep the unified organization

This is a very good thing.

**Comment by petertseng** [comment]
> That way it is easy to find out what is a language track by searching: topic:exercism-track

Anyone know a way to search for the non-tracks too? I tried:

* [`-topic:exercism-track`](https://github.com/search?q=org%3Aexercism+-topic%3Aexercism-track) Result: gets all 92 repositories.
* [`NOT topic:exercism-track`](https://github.com/search?q=org%3Aexercism+NOT+topic%3Aexercism-track) Result: NOT without search terms isn't allowed.
* [`topic:-exercism-track`](https://github.com/search?q=org%3Aexercism+topic%3A-exercism-track): Result: empty set.

This is not a blocker of course, just a curious question!

> Rename each language track to just the slug of the language.
> Rename x-common to `problem-specifications`

👍 

> Add probot automation and/or GitHub apps for all of the things that are currently blocked because of the lack of granular permissions

Since this is an addition and things will otherwise stay mostly as-is, no reason for me to disagree with this.

In fact, I don't think I'm missing any permission right now, so as far as I'm concerned "do nothing" satisfies this point!

Yes, there is the matter of allowing teams of maintainers to add people to the org (as a prerequisite to adding to the team) without the intervention of the organisation owners. It just seems to me that not having this ability doesn't block this proposal, which is why I made the statement that no-op satisfies this point.

**Comment by kytrinyx** [comment]
> Anyone know a way to search for the non-tracks too?

Per the documentation it should be `-topic:exercism-track`, but you tried that and it didn't work. I've reported this to GitHub. Either it's undocumented, or it's a bug. Either way I'll have more information soon.

> It just seems to me that not having this ability doesn't block this proposal

Agreed. The current state of things doesn't block the proposal, and automation will solve the problem in a way that I think is satisfactory.

**Comment by ErikSchierboom** [comment]
> Rename each language track to just the slug of the language.
Rename x-common to problem-specifications

Great!

**Comment by Insti** [comment]
> Rename x-common to problem-specifications

Are they `problem-specifications` or `exercise-specifications` or just `specifications`?

**Comment by kytrinyx** [comment]
@Insti I think per our discussion last week they could be any of those three. I like "problem" in this context, though, because they are the abstract description of the thing to be solved, not the actual exercise.

**Comment by Insti** [comment]
ok

**Comment by kytrinyx** [comment]
@petertseng I heard back from GitHub support, the negation is supposed to be `-topic:exercism-track`, and this is confirmed and reported as a bug.

**Comment by kytrinyx** [comment]
Per the most recent discussion, it sounds like the best choice is to:

1. Keep everything in the same GitHub organization
2. Rename all the track repositories as well as the x-common repository for clarity
3. Add automation to let track maintainers add more maintainers to their track

**Comment by kytrinyx** [comment]
Actionable issues:

- https://github.com/exercism/meta/issues/1
- https://github.com/exercism/meta/issues/2

**Comment by petertseng** [comment]
> the negation is supposed to be `-topic:exercism-track`

I considered asking whether it was worth it to work around by adding a topic not-exercism-track to all non-track repos, but then we would probably want to remove it when the negation is working. I suppose that would not be worth it.

**Comment by kytrinyx** [comment]
Yeah, let's just leave it as is, I think.
