### ISSUE TITLE
Transition time for solutions - test maching

### ISSUE THREAD

**Issue by kotp** [exercism/discussions#106]
When, and as, exercises transition, and the versions of the tests change, solutions (iterations) keep coming in, over time.  This means that from the fetching of the exercise, to submission, there is a time (this can be an extended amount of time) where the LoL (Lover of Learning) has perhaps test version 2, while when we fetch to review, we get test version 3.

How can we fetch the version 2 test locally, to match what they have?  And how can they fetch the version 3 test, when they want to consider the value that the newer test gives?

This should be achievable via the cli.

**Comment by kytrinyx** [comment]
The easiest way would be to submit the tests along with the solution.

For example:

```
exercism submit
```

Could by default submit everything in the current directory with all the trees, recursively (assuming that you're in an exercism track / problem directory).

Then we might not display the tests by default on the site, but we could let you expand it.

And we could get rid of versions.

**Comment by kotp** [comment]
Yes... get rid of versions!  That is a great advantage to this.  

Submitting everything may be language specific, as it would not be wanted to need to store and download the compiled assets in those compiled tracks.

**Comment by kytrinyx** [comment]
> Yes... get rid of versions! That is a great advantage to this.

@kotp I was hoping you'd say that :-)

> compiled assets

Ahh, we would probably want to have a global .ignore for a language track that the CLI could reference.

We now have support for global files, though, so that wouldn't actually be too bad.

**Comment by petertseng** [comment]
> `exercism submit` Could by default submit everything in the current directory with all the trees, recursively

Oh! I very much wanted the same thing: https://github.com/exercism/cli/issues/370 !

**Comment by kytrinyx** [comment]
We've completely overhauled how we store, deliver, and track versioning of tests and solutions in the new prototype.

In particular: we will _always_ show the version of the test suite that someone downloaded, when someone looks at a solution.

This ultimately means that we can get rid of the _test version_ bookkeeping thing (which makes my heart so happy).

I'm going to go ahead and close this, as I _think_ we've nailed it in the new prototype. That said, if there are subtle edge cases, let's discuss it in the https://github.com/exercism/v2-feedback repo.

**Comment by stkent** [comment]
From the maintenance point of view, is there now a canonical way to store/track currently implemented test suite versions at the track level? It would be nice to be able to write tooling to automatically check when a track test suite has fallen out of sync with the problem-specifications tests.

**Comment by kytrinyx** [comment]
> is there now a canonical way to store/track currently implemented test suite versions at the track level?

There isn't but it would be fairly straight forward to do so, as we now have the concept of a `.meta` directory, which is always ignored.

For example, we could have a `.meta/canonical-test-version.txt` file which contains the version of the canonical json that the test suite is current with, and some tooling to let you know if any canonical data is more recent than the one recorded. We could even have a bot that automatically opens an issue if it changes, though that might cause more work than it's worth.

**Comment by m-a-ge** [comment]
Maybe it isn't that bad idea to have `canonical-test-version.txt`. Because test suites for some exercises are outdated in Python track for example. Checking this automatically and open issues is a must have. I understand that currently the priority for this one is quite low, but it would be great to have this possibility.
Plus not every exercise has `canonical-data.json` :unamused:

@kytrinyx, if you decide to proceed with this idea, I could add this file to Groovy track (at least) since I'm actively working on it.

**Comment by kytrinyx** [comment]
@m-a-ge I'm going to open up a discussion issue about it, specifically, as someone might have a better idea about the implementation.
