### ISSUE TITLE
Copyright/License on submitted solutions

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#107]
@willnorris submitted a pull request (https://github.com/exercism/exercism.io/pull/2975) a few months ago to clarify that since nothing else has been stated, the person who wrote the solution that gets submitted to Exercism owns the copyright to that code.

This is true and should remain true forever and always.

I'd be curious to see what you all think about making solutions (going forward, I presume, but I would talk to a lawyer about that) licensed under the Creative Commons Attribution 4.0 license (http://choosealicense.com/licenses/cc-by-4.0/).

Pros/Cons?

I imagine that this is not possible to do retroactively for existing solutions without a lot of noise, but I wonder if it would be worth it, since despite being code this is in many ways educational content more than it is software.

**Comment by IanWhitney** [comment]
Would it be easier to put text in the submission#show view that says this? Right around here: https://github.com/exercism/exercism.io/blob/master/app/views/submissions/show.erb#L45

I have seen a student put a GPL notice at the top of all of his submissions. Not sure if there's any concern about him stating one license & us stating a different one.

**Comment by willnorris** [comment]
You'd definitely have problems doing that retroactively.  Just look at the mess [StackOverflow went through](http://meta.stackexchange.com/questions/271080/the-mit-license-clarity-on-using-code-on-stack-overflow-and-stack-exchange) with trying to attach a default license to code submissions there.

I wouldn't use CC-BY though... even Creative Commons [discourages using CC licenses for software](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software).  A simple notice style license (MIT, et al) would be the nearest equivalent.

**Comment by kytrinyx** [comment]
> You'd definitely have problems doing that retroactively.

@willnorris Yeah it seems like it would have to be opt-in for older submissions, and only going forward if we did a proper notification on the site, etc.

The thing that I'd like to be able to do is reference code examples with attribution without having to ask each individual up front.

**Comment by willnorris** [comment]
> The thing that I'd like to be able to do is reference code examples with attribution without having to ask each individual up front.

I suppose it would depend on what you mean by "referencing" them as to whether that would fall under fair use (and if anyone would likely care anyway).  But now we're getting into IANAL territory. 🚫 😬

**Comment by kytrinyx** [comment]
@willnorris Yeah, that's fair.

I'm thinking blog posts and conference talks, which would probably fall under fair use.

**Comment by rbasso** [comment]
Considering that most of the users probably don't really care about what people do with the submitted code, I think that it makes sense to force a free license for all new content. If someone is so protective about its code, maybe it should not be submitting anyway.

*Sad times are these when people have to ask permission to use publicly available information...*

**Comment by kytrinyx** [comment]
I'm going to stick with what we have, thanks for weighing in.
