### ISSUE TITLE
Using Github Projects Feature

### ISSUE THREAD

**Issue by kotp** [exercism/discussions#108]
See some back story in #20.

There are currently in the Exercism organization level some [Projects](https://github.com/exercism/discussions/projects) that are being tested.

There are three projects, The 24PullRequests project is multi-track, and so it is possible to manage that relationally.  Though it seems to be manual (I haven't seen a way have it move in a more automated way...)  But at a glance, with the icons and color hints, it (so far) fairly easy to see what needs to be positioned there.

I am not convinced yet that it is the thing to do... in this application.

However, looking at Hacktoberfest project, it may be worthwhile to set up notes, and when it is time convert them to issues... this way we can set up a plan before hand, and activate it fairly simply... set them up over the year as notes, and about a month before hand knock them down by converting them to issues...

The third project that is there is about Teams.  Each of these "Projects" can impact core and track repositories, so I think it is appropriate that it is on the right level.  However, not necessarily, again, convinced that Projects is what we should do... nor what the overhead is.

Thoughts?  Will it help make things easier to find, easier to organize, easier to track at a glance?  Is it too expensive in time and organization and overhead overall?  Or does it give enough of a benefit to maintainers/contributors?

**Comment by kytrinyx** [comment]
I'm not really sure whether or not projects will work for us, but I certainly think it's worth a try!

**Comment by jtigger** [comment]
I've been using Projects for a while now.

I'm finding them useful for organizing a group of maintainers on a track.  On [the Java track](https://github.com/exercism/xjava/projects/2), the maintainers are using it to express priorities of work *they* are doing... separate from other work (like the [good-first-patch](https://github.com/exercism/xjava/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+patch%22) backlog).

Right now, they are only loosely integrated.  For example, there's no way to have newly created issues appear in a list in the Project.  Nor can you define actions to be taken when an issue moves from one list to another (think: workflow actions that label open or close issues by moving them around on the Project).

I suspect that the Project feature will include those capabilities at some point ... wish I knew someone working at GitHub... they might be able to tell us...

**Comment by kytrinyx** [comment]
>  they might be able to tell us...

They might, if GitHub discussed timelines publicly.

**Comment by kytrinyx** [comment]
@kotp I'm going to go ahead and close this. Of course, if you still want to experiment with projects, please feel free to do so!
