### ISSUE TITLE
Surface "good" conversations

### ISSUE THREAD

**Issue by jtigger** [exercism/discussions#109]
**Goal:** surface great conversations while NOT creating a game around what's "great."

*(I'm fighting a flu and just woke in the middle of the night with this idea; this all could be crap.)*

----

What if the "see more submissions of (exercise)" showed the next submission in a hand curated list of "good" submissions? (note: NOT changing the Activity Stream, just what you see when you click "next").

What if that list were not so much "hand curated" but rather "good conversations" were determined by a query that runs once a day that sorts submissions by number of participants, descending where there is at least two participants?

What if that query further were not so much the  strictly sorted list, but a somewhat randomized ordering that tended to favor conversations with more participants (still a a daily job running outside the web traffic)?

What if that query further *favored* submissions with fewer views/more unreads so that when a given conversation has gotten attention, it rotates down in favor of less viewed submissions?

In aggregate, some kind of "score":

`S = rand(n) + ap - bv`

where:
* `n` total number of submissions that have at least 2 participants
* `a` relative weight of participants
* `p` number of participants in this submission (across all iterations)
* `b` relative weight of views
* `v` number views

it may be easier to calculate unreads than views; the `bv` would be additive (and referred to as `bu`).

----

Assuming that a primary source of value of Exercism is the conversations and that conversations with more participants tends to be more interesting (due to the fact there are more perspectives in the mix)...

With this in place and some encouragement to use the "other submissions for this exercise" feature when exploring solutions, this would (in a coarse-grained way) maximize the value a practitioner experiences on Exercism.  At the same time, it avoids any kind of real gamification.

**Comment by kytrinyx** [comment]
I think this is really interesting, and would love to see an experiment that tries something like this out!

**Comment by kytrinyx** [comment]
@jtigger I'm going to go ahead and close this one, as we're digging into this in various ways with the new prototype. Thank you so much for sharing :heart:
