### ISSUE TITLE
Two types of discussions -- should we clarify/normalize/something?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#11]
I just realized that there are two different types of discussions:
1. stuff that is specific to existing exercises (edge cases, errors, clarification of README/problem descriptions, working on write-ups to submit across all the tracks, etc). This concerns all the track maintainers, and occasionally anyone else who happens to be interested in "curriculum-y" type stuff.
2. roadmap, features, process, marketing, anything that has to do with exercism at a higher-level.

I think that it would make sense to discuss anything curriculum-related in the x-common repo. That way @exercism/track-maintainers can watch that repository if they want to, without being notified about everything that has to do with higher-level/feature/roadmap stuff if they don't want to.

Thoughts?

**Comment by kotp** [comment]
x-common or discussions.  We have two places for that, and x-common should really be for when the changes are ready to become reality, I think.

**Comment by kytrinyx** [comment]
That makes sense to me. I can go through and move everything with the "discussions" label from `x-common` to `discussions`.

**Comment by petertseng** [comment]
I think I don't mind either of the proposed criteria (either "exercise-related discussions should go in x-common" or "immediately actionable items should go in x-common"), though it might be nice to categorise discussions in this issue tracker with labels if this one gets too big.

**Comment by kytrinyx** [comment]
Yeah, we could definitely have labels here to help people navigate and situate themselves.

**Comment by kotp** [comment]
I can't get to the labels here, to label.  or perhaps there simply are no labels to work with.

**Comment by kytrinyx** [comment]
No, let me give all the track maintainers access to this repo.

**Comment by kytrinyx** [comment]
Done.

**Comment by kytrinyx** [comment]
I think the conclusion is:

If it's something that everyone involved in Exercism needs to know about or be a part of, then discuss it in the discussions repository, including cross-track concerns.

Anything that is specific to the common pool of exercism problem specifications, then it goes in the x-common pool.

I'm closing this in favor of issue 150, listed above.
