### ISSUE TITLE
Exercism team for rikki?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#110]
@mhelmetag @kotp I think we might be ready to consider a more community-based approach to rikki :-)

Want to be in a rikki team?

My thinking is that everyone on this team should have access to the heroku apps for the analyzers:

- crystal-analyzer
- ruby-analyzer

Also, access to the server where rikki is running (demogorgon) on rackspace to troubleshoot or deploy

And we should probably document stuff (maybe in the rikki repo)

- how to integrate a new language
- how to deploy rikki
- how to set up a new server to run rikki against

What am I missing?

-------

_Updated to add todo list_

- [x] rename analysseur to ruby-analyzer
    - [x] on heroku: create new app, exercism-ruby-analyzer
    - [x] on DNSimple: create CNAME ruby-analyzer.exercism.io
    - [x] in rikki: rename flags and variables and references
    - [x] edit rikki.conf on rackspace
    - [x] deploy rikki, this restarts the app and uses the new config
    - [x] verify that rikki can respond to an issue in hamming
        - see: http://exercism.io/submissions/09e516247e9843ec9ae4aadb7ad03160
- [x] create team `@exercism/rikki`
    - [x] `mhelmetag`
    - [x] `kotp` (pending confirmation)
- [x] give access to team members to deploy crystal analyzer, ruby analyzer
    - [x] `mhelmetag`
    - [x] `kotp` (pending confirmation)
- [x] give access to team members to deploy rikki to rackspace via public/private keypair
    - [x] `mhelmetag`
    - [x] `kotp` (pending confirmation)
- [x] test deploy crystal analyzer, ruby analyzer to heroku
    - [x] `mhelmetag`
    - [x] `kotp`
- [ ] test deploy rikki to rackspace
    - [ ] `mhelmetag`
    - [x] `kotp` (pending confirmation)

**Comment by kytrinyx** [comment]
Oh, access to all the rikki-related repos that we have.

**Comment by mhelmetag** [comment]
> I think we might be ready to consider a more community-based approach to rikki :-)

Yay, rikki 🎆  

> access to the server where rikki is running (demogorgon) on rackspace to troubleshoot or deploy

Is rikki the only thing still running on rackspace now?

> And we should probably document stuff (maybe in the rikki repo)

I can definitely help with that.

In terms of setting up the team with server and repo access, this all sounds good to me!

Should we fork crystal-analyzer into exercism so that all the rikki related things are in the org?

**Comment by kytrinyx** [comment]
> Is rikki the only thing still running on rackspace now?

Yepp, that's it.

> I can definitely help with that.

Excellent! I started documenting deploy stuff in a DEPLOYMENT.md document in the rikki repo a while back, and I also wrote a very rudimentary deploy script that has totally worked for me for 18 months or so. It's in the rikki repo as well, under `bin/`.

> In terms of setting up the team with server and repo access, this all sounds good to me!

Excellent, I'll get that sorted, then.

> Should we fork crystal-analyzer into exercism so that all the rikki related things are in the org?

Only if we're going to be developing on the fork. If not I'd rather it lived in your account, and that we document it clearly in rikki's README.

The Ruby analyzer API lives in the exercism org, but it depends on analysis code written by Jacob Richardson, so it's not all in the same place anyway.

**Comment by dvberkel** [comment]
Rikki seems really cool!

**Comment by kytrinyx** [comment]
Thanks @dvberkel it's been a great experiment, and I think it's turning into something a lot more useful than I first imagined.

**Comment by kytrinyx** [comment]
I created a checklist in the original issue. The next steps on the list to move this forward are:

- @kotp if you want to be in on this, let me know and I'll add you in the various places. If you have a heroku account already let me know which email address to use for you there.
- @mhelmetag: would you try deploying the ruby analyzer? Try using the documentation in exercism/rikki to figure out where the repo is and what it's deployed to on heroku—I suspect that we need to improve that, and the easiest way to get it right is if we dogfood it.
- I need a public key to stick on the rackspace server. Would you email this to me?

**Comment by mhelmetag** [comment]
> would you try deploying the ruby analyzer?

Sure! I'll give it a shot!

> I need a public key to stick on the rackspace server. Would you email this to me?

Email sent.

**Comment by mhelmetag** [comment]
Is it intentional that exercism-crystal-analyzer also has help.exercism.io pointed to it?

![dns_question](https://cloud.githubusercontent.com/assets/8609429/21071800/bb395972-be61-11e6-9756-2db9c7d19e83.png)

**Comment by kotp** [comment]
@kytrinyx You can grab the public key for any user that has submitted one: `GET /user/keys/:id` for your own, and `GET /users/:username/keys` for anothers keys.

The Heroku e-mail account is the same e-mail address you have for me on gmail.

**Comment by kytrinyx** [comment]
> Is it intentional that exercism-crystal-analyzer also has help.exercism.io pointed to it?

LOL, no, not at all. I had a problem creating new apps (because of an ENV var, it turns out), so I repurposed the old help app and turned it into crystal-analyzer. I've removed it now:

```
$ heroku domains
=== exercism-crystal-analyzer Heroku Domain
exercism-crystal-analyzer.herokuapp.com

=== exercism-crystal-analyzer Custom Domains
Domain Name                   DNS Target
────────────────────────────  ───────────────────────────────────────
crystal-analyzer.exercism.io  exercism-crystal-analyzer.herokuapp.com
```

> Also, I think we can remove the config vars because it's not a rack app anymore.

Agreed. I've removed both `LANG` and `RACK_ENV`.

> Also also, I was thinking of creating docker images for rikki, ruby-analyzer, etc etc so that (if wanted), they could all be spun up together using the existing docker-compose setup. Thoughts?

I've not necessarily felt the need for it, but if it's something that would make development easier, we should definitely consider it.

> You can grab the public key for any user that has submitted one

@kotp I had no idea, this is great! I'll get you set up everywhere so you can test your access.

**Comment by kytrinyx** [comment]
@kotp @mhelmetag your public SSH keys should now be on the authorized list on demogorgon. I'm sending you the IP address.

**Comment by mhelmetag** [comment]
@kytrinyx , I seem to have done goofed a bit. It seems I jumped the gun a bit and didn't look at my heroku logs well enough. It seems that I don't have access to `crystal` on heroku and I was relying on a system call... My fault. Hopefully I can fix this with some buildpack stuff.

Looks like rikki hasn't made any Crystal comments as of yet (besides on my tests). So I think we'll just have to do a temporary back out...

Ugh. Very my fault...

**Comment by mhelmetag** [comment]
Updated the `exercism-crystal-analyzer` to be hardcoded so that we don't make rikki comments in error... ugh 👎 

I will solve this!

**Comment by kytrinyx** [comment]
@mhelmetag Gah, I didn't see this. Where do you not have access? Where did you update the exercism-crystal-analyzer to be hard-coded?

**Comment by mhelmetag** [comment]
I have all the access I need. I was able to deploy the quick patch for this with no problems.

I just hard coded the analyzer's method to check the format of the solution so that it always thinks it's valid (and skips the system call).

I think I have a fix for this (using heroku containers so I get more control of what's installed on the server). Should be not much different.

In the long term, I should find out what Crystal lib makes the command line tool click and use that.

**Comment by kytrinyx** [comment]
Ah, OK cool. Thanks for the update.

**Comment by kotp** [comment]
@kytrinyx Yes for heroku.  Unsure the deploy to rackspace process.

**Comment by kytrinyx** [comment]
@kotp Probably? I haven't looked into pipelines at all, but that would certainly be worth looking into.

**Comment by kotp** [comment]
What is the location of the documentation for deploying to Rackspace?

**Comment by kytrinyx** [comment]
It's in https://github.com/exercism/rikki/blob/master/DEPLOYMENT.md We should probably point to it from the README now that you mention it...

**Comment by mhelmetag** [comment]
@kytrinyx, yeah, I was able to deploy rikki to rackspace (using `bin/deploy`) just now with no problems.

The only thing I could find was that `bin/deploy` wants you to have a ssh alias, setup for the rackspace server, called "demogorgon".

I set that up by adding this to my `~/.ssh/config`:
```
Host demogorgon
  HostName <rikki_rackspace_ip*>
  User root
```

* fill in with the rackspace server ip

I could add that to deployment doc?

**Comment by Insti** [comment]
Better to edit the deploy script to contain the configuration.
(depending on how secret that ip address should be.)

**Comment by kotp** [comment]
@mhelmetag that is exactly what I did too, with the config.  It is how I connect to the server.  Can you check and see if I killed rikki? :crying_cat_face:

**Comment by mhelmetag** [comment]
Hmmm... I'm not sure if rikki is happy now... I did see it restart and pickup redis when I deployed but... well here's some output from `/var/log/upstart/rikki.log`:
```
/proc/self/fd/9: 9: /proc/self/fd/9: /usr/local/rikki/current/rikki: not found
/proc/self/fd/9: 9: /proc/self/fd/9: /usr/local/rikki/current/rikki: not found
/proc/self/fd/9: 9: /proc/self/fd/9: /usr/local/rikki/current/rikki: not found
/proc/self/fd/9: 9: /proc/self/fd/9: /usr/local/rikki/current/rikki: not found
/proc/self/fd/9: 9: /proc/self/fd/9: /usr/local/rikki/current/rikki: not found
/proc/self/fd/9: 9: /proc/self/fd/9: /usr/local/rikki/current/rikki: not found
```

That doesn't look great to me but... mind chiming in @kytrinyx ?

**Comment by kotp** [comment]
Can you redeploy @mhelmetag

**Comment by kotp** [comment]
It is back up and running.  Did it manually rather than through script, but it is using the 2017-01-05 version... feel free to deploy your changes though, if any, please.

**Comment by mhelmetag** [comment]
Thanks, @kotp. I wouldn't have been able to get to it until after work! Much appreciated!

**Comment by kotp** [comment]
Docker sounds good to me.. Anyone using Docker for this?

**Comment by mhelmetag** [comment]
Yeah Docker would be cool. I'm working on getting crystal-analyzer running on the beta heroku for containers.

**Comment by kotp** [comment]
I think if the exercism.io and the rikki (and whatever other servers are running) can be setup as containers, perhaps there can be a "quick" or "easy" way to get these running together to be able to easily review changes on the site, test exercise deployments, rikki feedback, etc.

**Comment by ErikSchierboom** [comment]
I was looking into creating a Rikki analyzer for C# or F#, but unfortunately I found the documentation a bit, eh, lacking. If possible, I'd love to see a step-by-step instruction on what an analyzer should do and how to implement/add one.

**Comment by kotp** [comment]
@ErikSchierboom That is actually a really good point, and probably should be a separate issue.

**Comment by kytrinyx** [comment]
Opened an issue for this on the rikki repo.

**Comment by ErikSchierboom** [comment]
Nice, thanks!

**Comment by kytrinyx** [comment]
I think we're good on this one. We have an open issue about documentation.
