### ISSUE TITLE
I will be going radio silent from December 15-Jan 1

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#111]
I will not be responding to email or GitHub issues or reviewing pull requests for the second half of December.

I will be deploying updates to the language tracks as a part of my daily routine, but I will not be reachable unless there's a crisis, in which case I can be reached by SMS. A few people have my number, I will check with them if they'll be checking email and GitHub notifications, and I'll post back here with instructions about what to do in the case of emergency.

This is the first time I'm taking a break since the inception of the project in June 2013. There have been times in those 3.5 years where I've accidentally not responded to Exercism issues or email for days at a time while being slammed with other things, but that's different, because I was slammed and feeling guilty, not taking a break.

This is going to be an actual break where I don't work. Not for work, not for Exercism.

/cc @exercism/track-maintainers

**Comment by Insti** [comment]
How do you want us to handle PRs? Do you want us to merge them? Tag them as 'ready'? or just let them all pile up until you get back?

**Comment by ErikSchierboom** [comment]
Enjoy your break!

**Comment by kotp** [comment]
Indeed enjoy your break.

You have some pretty good henchfolk here so things should mostly go smooth.

**Comment by kytrinyx** [comment]
@Insti You have all been making great decisions ✨ :heart: despite my lack of having communicated a good vision for the web portion of things. Go ahead and merge things! Thank you so much :heart:

**Comment by Insti** [comment]
Great. Thanks. Have a good break! :christmas_tree:

**Comment by robkeim** [comment]
That's definitely a well earned time off :) Enjoy and see you next year!

**Comment by parkerl** [comment]
🎉 That is great!

**Comment by bernardoamc** [comment]
Enjoy the break Katrina! ❤️ 🎉

**Comment by behrtam** [comment]
Great decision! Enjoy your time off.

**Comment by rchavarria** [comment]
Enjoy your break!! 🎉

**Comment by jtigger** [comment]
More than well-earned, @kytrinyx!  Clearly "the shop" is in good hands while you're taking a proper rest. ☺️

**Comment by troubalex** [comment]
Enjoy your break! ☃️  I'm sure it will be glorious. ❤️

**Comment by kytrinyx** [comment]
FYI @bernardoamc and @parkerl have my number. If there is an emergency and I need to be involved, please post an issue and `@`-mention them or email them if their email is on their GitHub profile, and they know how to get ahold of me.

**Comment by kytrinyx** [comment]
Also: thank you everyone :heart:

**Comment by kytrinyx** [comment]
I'm back, thank you everyone for keeping everything running so smoothly. :sparkles:
