### ISSUE TITLE
Open Source Fellowship (Hacker Paradise)

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#112]
Hacker Paradise reached out to me recently about their new open source fellowship.

> The Open Source Fellowships will cover a month of accommodations, workspace, our events, and a stipend for living expenses for you to join our South America trip and work full-time on an open source project of your choosing.

Read more here: http://www.hackerparadise.org/blog/2016/11/17/open-source-fellowship/

The application deadline is December 21st.

So, first: If you have a project or an idea and the time to participate, go for it. Apply. You don't need me for that.

Second: If you're interested in this, but not really sure what you would do, then I **might** have a proposal for you if you happen to belong to an underrepresented group in open source. 

And if you don't belong to an underrepresented group in open source, I still love you, OK?

OK.

I have three Exercism-related projects in mind that I think would make lovely 1-month projects. None of these are traditional hunker-down-in-South-America-and-ship-a-bunch-of-code type projects. Almost all of Exercism's biggest problems are non-technical, right now, and the technical ones are not 1-month projects). These are all things that would likely be ideal for people who are pretty new to the industry, since you'd be bringing all sorts of handy skills to the table from previous careers and lifetimes.

The three projects are very roughly:

* Coordinate an effort to work out a **sustainable plan** for maintaining all of Exercism's language tracks and the Exercism curriculum. I have a bunch of resources to start with, and you would not be alone, but you would be the only person working on it full time. (Skills that could help here: communication skills, organizational skills, process definition, research)
* Develop an Exercism Meetup Kit and Exercism Workshop Kit that people could use to bring the Exercism curriculum into the offline world. Again, other people would probably be delighted to contribute, but you would be the only one working on it full time for a month. (Skills that could help here: pedagogy, organization, marketing, design, communication)
* Develop an Exercism Feedback Guide for a language track, based on _existing conversations, solutions, and feedback_. This would likely involve building out some tools to help organize and explore the data, and it would have to be done in a language track with lots of submissions and discussion in order to be useful. (Skills that could help here: research, pattern recognition, technical writing, programming). This feedback guide could be used to help people on Exercism get over the barrier to actually giving feedback, and it might also be a first step towards creating resources for high-school math teachers who are informed by their principals that they'll be teaching programming, but who are not given resources to do it. Which happens all the time, apparently.

So here's the deal. If...

- ... this time in your life is one where you could take a 1 month trip to South America to work full time on an open source project, **and**
- ... you happen to belong to an underrepresented group in open source, **and**
- ... one of these projects is appealing to you and matches *some part* of your skill set (like I said: these are weird ones)

... then I would be interested in helping craft an application for this.

Notice that I'm saying *some part of your skill set*. I've never done any of these things before, I don't expect anyone to magically have all the skills you might imagine would come in handy (and who knows what they are anyway). If you think you could take a reasonable stab at moving this forward: that's awesome. Email me. Tell me things about what you're excited about, which of these ideas you're interested in and why, some ideas that you have about what would go into this, or a story about something you did that this reminds you of. Or something. I just want to get a feel for who you are and what working on this would look like for you.

My email address is on my GitHub profile.

Please note that **I don't have any say in who gets selected**, I don't know the company or organization or the people involved, but I think this sounds like a potentially interesting/exciting opportunity.

**I won't be managing this process here in the issue.**

The caveat is that if I get a bunch of people who are interested, I might have to tell a bunch of folks "no" which sucks, but doesn't at ALL reflect on you.

------

For a bit of inspiration take a look at Anjuan Simmons' most excellent talk **Lending Privilege** from GitHub Universe this year: https://www.youtube.com/watch?v=8Nvg-MMtN_A

**Comment by dvberkel** [comment]
Can I retweet something to draw peoples attention to this?

**Comment by kotp** [comment]
@dvberkel please do.  It is publicly posted, and will help get the word out to the right folks, the people that need to hear it.
