### ISSUE TITLE
All tracks that have discussed whether to have stubs or not

### ISSUE THREAD

**Issue by petertseng** [exercism/discussions#114]
Hello. If your track ever had any discussions regarding whether to provide stub files to students, I would be pleased if you would comment on this issue with what you decided. Or, even better, if you have records of these discussions in an issue or PR, you could add a link to the below list.

* https://github.com/exercism/exercism.io/issues/960 - first support for stub files

Track | Issue | Stubs? | If yes, contents?
--|--|--|--
C | https://github.com/exercism/xc/issues/43 | hello world | signatures
C++ | https://github.com/exercism/xcpp/pull/4 | no? | inconclusive
C# | https://github.com/exercism/xcsharp/issues/138 | all | signatures or empty classes
Clojure | https://github.com/exercism/xclojure/issues/121 | ~~all~~ | names
Clojure | https://github.com/exercism/xclojure/issues/136 | first 5 | names
Crystal | https://github.com/exercism/xcrystal/issues/63 | all | blank
Erlang | https://github.com/exercism/xerlang/issues/145 | all | signatures
F# | https://github.com/exercism/xfsharp/issues/229 | all | first few: signatures. rest: blank
Go | https://github.com/exercism/xgo/issues/148 | first few | signatures
Go | https://github.com/exercism/xgo/issues/279 | first few | signatures
Haskell | https://github.com/exercism/xhaskell/issues/181 | all | signatures
Java | https://github.com/exercism/xjava/issues/178 | first 10+10 | signatures
Lisp | https://github.com/exercism/xlisp/issues/20 | all | signatures
PureScript | https://github.com/exercism/xpurescript/pull/8#discussion_r91789830 | all | names
Python | https://github.com/exercism/xpython/issues/210 | no
Python | https://github.com/exercism/xpython/issues/272 | all | names
Ruby | https://github.com/exercism/xruby/issues/541 | pending
Rust | https://github.com/exercism/xrust/issues/117 | all | empty (some w/ sigs)
Rust | https://github.com/exercism/xrust/issues/200 | all | continued
Rust | https://github.com/exercism/xrust/issues/269 | all | continued
Scala | https://github.com/exercism/xscala/issues/137 | all | first 10: signatures. rest: blank
Standard ML | https://github.com/exercism/xsml/issues/32 | all | signatures
Swift | https://github.com/exercism/xswift/issues/245#issuecomment-274295656 | all | blank

**Comment by petertseng** [comment]
I feel like I should close this issue since there is never any "completed" state for it (*maybe* if all tracks wanted to standardise on whether to provide stub files or not, and we decided to come together and make it happen), and I wouldn't want it to clog up the issue queue. I'm still happy to hear your comments though, don't let the fact that the issue is closed stop you!

**Comment by petertseng** [comment]
EBWODP:

1. I would also like to hear what you *decided*. To this end, I have edited the list in my initial comment to be:

* [exercism.io](https://github.com/exercism/exercism.io/issues/960) - first support for stub files
* [C](https://github.com/exercism/xc/issues/43) - stub first few exercises
* [Clojure](https://github.com/exercism/xclojure/issues/121) - all exercises
* [Go](https://github.com/exercism/xgo/issues/148) - first few exercises
* [Go](https://github.com/exercism/xgo/issues/279) again - still first few exercises
* [Haskell](https://github.com/exercism/xhaskell/issues/181) - all exercises
* [Java](https://github.com/exercism/xjava/issues/178) - first few exercises
* [Python](https://github.com/exercism/xpython/issues/210) - no stubs
* [Python](https://github.com/exercism/xpython/issues/272) again - still no stubs, I think
* [Rust](https://github.com/exercism/xrust/issues/117) - all exercises, I think?
* [Rust](https://github.com/exercism/xrust/issues/200) again - although there are some exercises where we decide not to
* [Scala](https://github.com/exercism/xscala/issues/137) - first few exercises

2. My Scheme link was not a discussion of whether to have stubs (it was about a generator that made generating the stub easy), so it has to be removed from the list,

**Comment by petertseng** [comment]
In general, it seems stubs may be provided for at least two reasons:

1. If the submission file **needs to be placed in a certain directory** due to the language or build tool's project structure, having a stub file (empty or not) saves the student the busy-work of having to create the directory structure then create the file. Note that this busy-work has been described as [supremely annoying](https://github.com/exercism/xrust/issues/200#issuecomment-246203023). I think this is always a good reason to have a stub file.
2. The stub file could possibly **provide the expected signatures**. There is healthy debate about whether it is a useful learning experience for the student to figure out the expected signatures versus just busy-work. As a middle ground, some tracks may decide to place the expected signatures in a comment in the test file, or in HINTS.md such that it becomes included in the README. Of course, tracks that do not wish to do this can just include an empty stub file, which at least will cause the directory structure to be preserved.

**Comment by petertseng** [comment]
Crystal added: https://github.com/exercism/xcrystal/issues/63

**Comment by petertseng** [comment]
Lisp's exercism/xlisp#20 has been added.

**Comment by petertseng** [comment]
PureScript has been added: https://github.com/exercism/xpurescript/pull/8#discussion_r91789830

**Comment by kytrinyx** [comment]
FYI @exercism/track-maintainers interesting discussion/analysis here about stub files. If you have anything to add (including links to discussions in your respective tracks), please add it here.

**Comment by masters3d** [comment]
Swift just moved to stub blank files for all excercises.
https://github.com/exercism/xswift/issues/245#issuecomment-274295656

**Comment by robkeim** [comment]
@petertseng I updated your original comment with the related discussion in [C#](https://github.com/exercism/xcsharp/issues/138) and [F#](https://github.com/exercism/xfsharp/issues/229).

 FYI @ErikSchierboom who created these issues.

**Comment by Insti** [comment]
Re-opened this because it's still under active discussion and it would nice if it was more discoverable. We can close it again once it gets old and we've all worked out what we're doing about our stubs.

**Comment by ErikSchierboom** [comment]
The concensus of the C# and F# track was that we will be using stub files, where the earlier ones will already be providing the exact required functions, and later on you will have to add them yourselves.

**Comment by verdammelt** [comment]
The Lisp track uses a stub file for all exercises as the boilerplate to set up the package is not something we are teaching.  I think this is important to do. It is analogous to the issues of specific directory structures in other languages.

Currently all our exercises contain functions with the correct signature but no body. I'm thinking now that dropping these off after the first set of exercises would be safe to do.

**Comment by petertseng** [comment]
Editing into above post about rationale for stub files:

For statically-typed languages, typically the entire test suite must type-check before it can be run. Therefore, to make the test suite runnable, tracks of statically-typed languages tend to choose one of the following options:
    * nothing (as a consequence, students must figure out the signatures from reading the tests and write them all before any work can be done on the first test)
    * provide stubs with the signatures: saves student the above work, but also removes that part of the learning process
    * use conditional compilation to make the compiler not perform type-checking for later tests. This is not possible in all languages.

**Comment by petertseng** [comment]
SML added, Erlang added. Deleting this comment.

**Comment by petertseng** [comment]
> There is healthy debate about whether it is a useful learning experience for the student to figure out the expected signatures versus just busy-work.
> As a middle ground, some tracks may decide to place the expected signatures in a comment in the test file, or in HINTS.md such that it becomes included in the README.

A vision of the future...

What if I, as a student, could express a preference (possibly per-track) for what kind of stub file the API delivers:

* Always with signatures
* Always without signatures (and/or always empty, though these two might not always be the same)
* The track maintainers' recommendation (may differ based on exercise)

Catering to the preferences and needs of different audiences (Those who say "I think it's educational and valuable to think carefully about the signatures" versus "I think it's useless busy-work to have to divine the signatures from the test file")

**Comment by IanWhitney** [comment]
That would be cool. If someone (not it!) wants to do the work, I would support it.

**Comment by petertseng** [comment]
updated today:

coq (new track)
javascript (found the discussion I missed, though it's a quick one)
julia (found discussion I missed)

state of table today:

Track | Issue | Stubs? | If yes, contents?
--|--|--|--
C | https://github.com/exercism/xc/issues/43 | hello world | signatures
C++ | https://github.com/exercism/xcpp/pull/4 | no? | inconclusive
C# | https://github.com/exercism/xcsharp/issues/138 | all | signatures or empty classes
Coq | https://github.com/exercism/xcoq/issues/4 | all | signatures
Clojure | https://github.com/exercism/xclojure/issues/121 | ~~all~~ | names
Clojure | https://github.com/exercism/xclojure/issues/136 | first 5 | names
Crystal | https://github.com/exercism/xcrystal/issues/63 | all | blank
Erlang | https://github.com/exercism/xerlang/issues/145 | all | signatures
F# | https://github.com/exercism/xfsharp/issues/229 | all | first few: signatures. rest: blank
Go | https://github.com/exercism/xgo/issues/148 | first few | signatures
Go | https://github.com/exercism/xgo/issues/279 | first few | signatures
Haskell | https://github.com/exercism/xhaskell/issues/181 | all | signatures
Java | https://github.com/exercism/xjava/issues/178 | first 10+10 | signatures
JavaScript | https://github.com/exercism/xjavascript/issues/318 | first 2 | signatures
Julia | https://github.com/exercism/xjulia/issues/2#issuecomment-262652167 | all | signatures
Lisp | https://github.com/exercism/xlisp/issues/20 | all | signatures
PureScript | https://github.com/exercism/xpurescript/pull/8#discussion_r91789830 | all | names
Python | https://github.com/exercism/xpython/issues/210 | no
Python | https://github.com/exercism/xpython/issues/272 | all | names
Ruby | https://github.com/exercism/xruby/issues/541 | pending
Rust | https://github.com/exercism/xrust/issues/117 | all | empty (some w/ sigs)
Rust | https://github.com/exercism/xrust/issues/200 | all | empty (continued)
Rust | https://github.com/exercism/xrust/issues/269 | all | empty (continued)
Scala | https://github.com/exercism/xscala/issues/137 | all | first 10: signatures. rest: blank
Standard ML | https://github.com/exercism/xsml/issues/32 | all | signatures
Swift | https://github.com/exercism/xswift/issues/245#issuecomment-274295656 | all | blank

**Comment by petertseng** [comment]
Track | Issue | Stubs? | If yes, contents?
--|--|--|--
C | https://github.com/exercism/xc/issues/43 | hello world | signatures
C++ | https://github.com/exercism/xcpp/pull/4 | no? | inconclusive
C# | https://github.com/exercism/xcsharp/issues/138 | all | signatures or empty classes
Ceylon | https://github.com/exercism/xceylon/pull/11 | all | signatures
Coq | https://github.com/exercism/xcoq/issues/4 | all | signatures
Clojure | https://github.com/exercism/xclojure/issues/121 | ~~all~~ | names
Clojure | https://github.com/exercism/xclojure/issues/136 | first 5 | names
Crystal | https://github.com/exercism/xcrystal/issues/63 | all | blank
Erlang | https://github.com/exercism/xerlang/issues/145* | all | signatures
F# | https://github.com/exercism/xfsharp/issues/229 | all | first few: signatures. rest: blank
Go | https://github.com/exercism/xgo/issues/148 | first few | signatures
Go | https://github.com/exercism/xgo/issues/279 | first few | signatures
Haskell | https://github.com/exercism/xhaskell/issues/181 | all | signatures
Java | https://github.com/exercism/xjava/issues/178 | first 10+10 | signatures
JavaScript | https://github.com/exercism/xjavascript/issues/318* | first 2 | signatures
Julia | https://github.com/exercism/xjulia/issues/2#issuecomment-262652167 | all | signatures
Lisp | https://github.com/exercism/xlisp/issues/20 | all | signatures
PureScript | https://github.com/exercism/xpurescript/pull/8#discussion_r91789830 | all | names
Python | https://github.com/exercism/xpython/issues/210 | no
Python | https://github.com/exercism/xpython/issues/272 | all | names
Ruby | https://github.com/exercism/xruby/issues/541 | pending
Rust | https://github.com/exercism/xrust/issues/117 | all | empty (some w/ sigs)
Rust | https://github.com/exercism/xrust/issues/200 | all | empty (continued)
Rust | https://github.com/exercism/xrust/issues/269 | all | empty (continued)
Scala | https://github.com/exercism/xscala/issues/137 | all | first 10: signatures. rest: blank
Scheme | https://github.com/exercism/xscheme/pull/1* | all | signatures
Standard ML | https://github.com/exercism/xsml/issues/32 | all | signatures
Swift | https://github.com/exercism/xswift/issues/245#issuecomment-274295656 | all | blank

**Comment by petertseng** [comment]
(this message will be deleted) one year should be enough

**Comment by petertseng** [comment]
current table:


Track | Issue | Stubs? | If yes, contents?
--|--|--|--
C | https://github.com/exercism/xc/issues/43 | hello world | signatures
C++ | https://github.com/exercism/xcpp/pull/4 | no? | inconclusive
C# | https://github.com/exercism/xcsharp/issues/138 | all | signatures or empty classes
Ceylon | https://github.com/exercism/xceylon/pull/11 | all | signatures
Coq | https://github.com/exercism/xcoq/issues/4 | all | signatures
Clojure | https://github.com/exercism/xclojure/issues/121 | ~~all~~ | names
Clojure | https://github.com/exercism/xclojure/issues/136 | first 5 | names
Crystal | https://github.com/exercism/xcrystal/issues/63 | all | blank
Erlang | https://github.com/exercism/xerlang/issues/145* | all | signatures
F# | https://github.com/exercism/xfsharp/issues/229 | all | difficulty 1-3: signatures+types; 4-7: signatures; 8-10: empty
Go | https://github.com/exercism/xgo/issues/148 | first few | signatures
Go | https://github.com/exercism/xgo/issues/279 | first few | signatures
Haskell | https://github.com/exercism/xhaskell/issues/181 | all | signatures
Java | https://github.com/exercism/xjava/issues/178 | ~~first 10+10~~ | signatures
Java | https://github.com/exercism/java/issues/977 | difficulty < 5 | signatures
JavaScript | https://github.com/exercism/javascript/issues/128 | first 2 | signatures
JavaScript | https://github.com/exercism/javascript/issues/424 | pending | pending
Julia | https://github.com/exercism/xjulia/issues/2#issuecomment-262652167 | all | signatures
Lisp | https://github.com/exercism/xlisp/issues/20 | all | signatures
Perl6 | https://github.com/exercism/perl6/issues/76 | all | first few: signatures. rest: blank
Pony | https://github.com/exercism/pony/issues/37* | all | signatures
PureScript | https://github.com/exercism/xpurescript/pull/8#discussion_r91789830 | all | names89830 | all | names
Python | https://github.com/exercism/xpython/issues/210 | no
Python | https://github.com/exercism/xpython/issues/272 | all | names
Ruby | https://github.com/exercism/xruby/issues/541 | pending
Rust | https://github.com/exercism/xrust/issues/117 | all | empty (some w/ sigs)
Rust | https://github.com/exercism/xrust/issues/200 | all | empty (continued)
Rust | https://github.com/exercism/xrust/issues/269 | all | empty (continued)
Scala | https://github.com/exercism/xscala/issues/137 | all | first 10: signatures. rest: blank
Scheme | https://github.com/exercism/xscheme/pull/1* | all | signatures
Standard ML | https://github.com/exercism/xsml/issues/32 | all | signatures
Swift | https://github.com/exercism/xswift/issues/245#issuecomment-274295656 | all | blank
TypeScript | https://github.com/exercism/typescript/issues/57 | all | blank

**Comment by LegalizeAdulthood** [comment]
Regarding C++, I think the conclusion is no.

**Comment by petertseng** [comment]
> Regarding C++, I think the conclusion is no.

Good. Next step is if there is any better issue than https://github.com/exercism/cpp/pull/4 that documents the decision, to say what that issue is. If there is no better issue, there is no need to respond.

**Comment by petertseng** [comment]
EBWODP: It's not clear what "better" means. Instead, I mean "in detail".

Good. Next step is if there is any issue other than https://github.com/exercism/cpp/pull/4 that documents the decision in detail, to say what that issue is. If there is no such issue, there is no need to respond.

**Comment by tuxagon** [comment]
> What if I, as a student, could express a preference (possibly per-track) for what kind of stub file the API delivers
@petertseng I find this a fascinating idea. One of the biggest complications, I think, is the tests would require a specific signature, especially for statically-typed languages. I'm not sure it wouldn't ever *not* be busy-work under those conditions. The concept of "catered" problem solving is really interesting, though.

**Comment by petertseng** [comment]
EBWODP:

current:


Track | Issue | Stubs? | If yes, contents?
--|--|--|--
Bash | https://github.com/exercism/bash/issues/87 | hello world | signatures
C | https://github.com/exercism/c/issues/43 | ~~hello world~~ | signatures
C | https://github.com/exercism/c/issues/252 | first two | signatures
C++ | https://github.com/exercism/cpp/pull/4 | no |
C# | https://github.com/exercism/csharp/issues/138 | all | signatures or empty classes
Ceylon | https://github.com/exercism/ceylon/pull/11 | all | signatures
Coq | https://github.com/exercism/coq/issues/4 | all | signatures
Clojure | https://github.com/exercism/clojure/issues/121 | ~~all~~ | names
Clojure | https://github.com/exercism/clojure/issues/136 | ~~first 5~~ | names
Clojure | https://github.com/exercism/clojure/issues/205* | all | names
Crystal | https://github.com/exercism/crystal/issues/63 | all | blank
Dart | https://github.com/exercism/dart/issues/82 | pending
Elm | https://github.com/exercism/elm/issues/206* | all | signatures
Erlang | https://github.com/exercism/erlang/issues/145* | all | signatures
F# | https://github.com/exercism/fsharp/issues/229 | all | difficulty 1-3: signatures+types; 4-7: signatures; 8-10: empty
Go | https://github.com/exercism/go/issues/148 | first few | signatures
Go | https://github.com/exercism/go/issues/279 | first few | signatures
Haskell | https://github.com/exercism/haskell/issues/181 | all | signatures
Java | https://github.com/exercism/java/issues/178 | ~~first 10+10~~ | signatures
Java | https://github.com/exercism/java/issues/977 | difficulty < 5 | signatures
JavaScript | https://github.com/exercism/javascript/issues/128 | first 2 | signatures
JavaScript | https://github.com/exercism/javascript/issues/424 | pending | pending
Julia | https://github.com/exercism/julia/issues/2#issuecomment-262652167 | all | signatures
Lisp | https://github.com/exercism/lisp/issues/20 | all | signatures
Perl6 | https://github.com/exercism/perl6/issues/76 | all | first few: signatures. rest: blank
Pony | https://github.com/exercism/pony/issues/37* | all | signatures
PureScript | https://github.com/exercism/purescript/pull/8#discussion_r91789830 | all | names
Python | https://github.com/exercism/python/issues/210 | no
Python | https://github.com/exercism/python/issues/272 | all | names
Ruby | https://github.com/exercism/ruby/issues/541 | pending
Rust | https://github.com/exercism/rust/issues/117 | all | empty (some w/ sigs)
Rust | https://github.com/exercism/rust/issues/200 | all | empty (continued)
Rust | https://github.com/exercism/rust/issues/269 | all | empty (continued)
Scala | https://github.com/exercism/scala/issues/137 | all | first 10: signatures. rest: blank
Scheme | https://github.com/exercism/scheme/pull/1* | all | signatures
Standard ML | https://github.com/exercism/sml/issues/32 | all | signatures
Swift | https://github.com/exercism/swift/issues/245#issuecomment-274295656 | all | blank
TypeScript | https://github.com/exercism/typescript/issues/57 | all | blank

**Comment by sshine** [comment]
OCaml: exercism/ocaml#285, stubs for all files, containing signatures.
