### ISSUE TITLE
Turn on CircleCI for Objective-C, Swift Tracks. 

### ISSUE THREAD

**Issue by masters3d** [exercism/discussions#116]
TravisCI is great but the macOS builds are extremely slow. There is always a backlog that can take hours to run the macOS builds. https://www.traviscistatus.com/ The linux builds are pretty fast. 

I've noticed that other mac open source problems are using circleCI in addition to travis but I am not able to turn this on myself. 

![image](https://cloud.githubusercontent.com/assets/6539412/22124212/a6191ad0-de43-11e6-8325-5a9996245ac6.png)

**Comment by kytrinyx** [comment]
I don't have an OS X plan on Circle CI, since those are paid plans.

**Comment by kytrinyx** [comment]
I'll contact them and see if they have any discounts for open source projects.

**Comment by masters3d** [comment]
Ah okay. I thought it was free for Mac as well. Thanks.

**Comment by kytrinyx** [comment]
I talked to Circle CI and they've granted us Mac builds under their open source plan. I _think_ I've configured things correctly, so that they build on mac now.

**Comment by masters3d** [comment]
yay! Thanks!

**Comment by masters3d** [comment]
@kytrinyx it looks like no osx plans selected. Do you mind checking again?
![image](https://cloud.githubusercontent.com/assets/6539412/22606444/c6c0a4f8-ea08-11e6-92c2-e1df9deba199.png)

**Comment by masters3d** [comment]
All working now :) 👍
