### ISSUE TITLE
Process for requesting new tracks

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#118]
I've been asking people to email me when they want to add a new track, and finally decided to formalize the process a bit.

I've created a repo https://github.com/exercism/request-new-language-track which contains the template for a new language track, as well as a script that will bootstrap a new track repository. Since the script creates a repository on the Exercism organization, only organization admins can run it.

I've added an [issue template][issue-template] to help collect the information we need in order to kick off a track.

Are there any other questions we should ask people before we bootstrap a new track?

Should we have a buddy system, where we assign an existing track maintainer to help mentor the new maintainer?

[issue-template]: https://github.com/exercism/request-new-language-track/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by rpottsoh** [comment]
> Should we have a buddy system, where we assign an existing track maintainer to help mentor the new maintainer?

@kytrinyx, speaking from experience as a new track maintainer and having never maintained a track before I have to say yes to this point.  @kotp has been very helpful and instructive on how to go about maintaining a track and how to go about commenting on student submissions; and I'm still learning.

**Comment by kotp** [comment]
I like the new repository for track requests... I think having the ability for current maintainers to assign themselves is a good thing.  And I am (as well as apparently others) are available on the gitter chat room for support and encouragement.

**Comment by kytrinyx** [comment]
Yeah, I like having the requests out in the open. And if we go with the separate organization for curriculum (#103), a lot more people will have the rights to create repositories.

**Comment by jtigger** [comment]
This is grand, @kytrinyx!

> Should we have a buddy system, where we assign an existing track maintainer to help mentor the new maintainer?

I swear I hadn't read this before I sent you that email this morning that said the same thing. :)

I think this is a critical piece for a couple of reasons.

1. maintaining an Exercism track skillfully means being collaborative: inclusive, encouraging, skeptical and open-minded.  Conveying this attitude is best done by example — mentors can do that.
2. communities risk losing their culture if they grow faster than their ability to absorb and align individuals' motivations.  If a language enthusiast (not already an Exercism maintainer) cannot be paired with a mentor, that's a clear indication that we've hit a growth speed limit.

❤️  this!

**Comment by kytrinyx** [comment]
How should we get mentors involved?

1. Ask people who are willing to mentor to watch the repository and then volunteer if they've got capacity?
1. Create an `@exercism/maintainer-mentors` (or something) team that can be mentioned?
1. ???

**Comment by kotp** [comment]
As far as the template goes, for the request-new-language-track, it looks OK to me, but time will tell using it, what are the questions we end up asking over and over again... we will naturally know.  (Kind of like not paving the courtyard until a year after it is open, to learn the natural paths that occur).

**Comment by kytrinyx** [comment]
> Kind of like not paving the courtyard until a year after it is open, to learn the natural paths that occur

Exactly. OK, cool :-) We'll leave it like that for now.

**Comment by kytrinyx** [comment]
The new process for requesting language tracks is much better. I've opened a new issue about the buddy/mentor question here: https://github.com/exercism/discussions/issues/152
