### ISSUE TITLE
Out of Office - Feb 24-27

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#119]
I tore a ligament in my ankle, and will be getting a bit of surgical repair done tomorrow. I expect to be completely offline for a few days following the surgery, and possibly slow to respond for a few days after that.

At the moment I'm the only one deploying, so it may take a few days to see changes in the exercises make it up to the site.

**Comment by kotp** [comment]
Sorry  :cry: to hear about damage done to your ankle.

Meh, we gotta fix that single point of deployment... but with that said, we definitely understand health before exercism!

Feel better soon, can't wait for you to be back on your :footprints: !

**Comment by bernardoamc** [comment]
Ouch, sorry to hear that Katrina! 😢 

Good luck on your surgery and I hope you can recover super fast! <3

**Comment by ErikSchierboom** [comment]
Good luck with the surgery and your recovery!

**Comment by jtigger** [comment]
Best of luck and a fast recovery, Katrina! 💐 

Joanna (my wife) tells me stories of how when she or one of her siblings were laid-up they were given a little bell to beckon their mother. 🛎   Strangely, that has yet to materialize in our house. :)

**Comment by kytrinyx** [comment]
I'm back home (and fairly heavily medicated). They've asked that I don't make any decisions or do my taxes for the next few days. I'm pretty sure if they knew what open source was they'd warn me off that as well :-) I'll check back in on Tuesday.

**Comment by kytrinyx** [comment]
(A bell! Now there's an idea...)

**Comment by kotp** [comment]
Why we no have :spewing coffee out your nose: emoticon?
