### ISSUE TITLE
Close the loop on exercise deprecation

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#120]
We have had a bunch of conversations about deprecating exercises across many different repositories and issues. I believe we've figured out how to deal with it, but it's undocumented and incomplete.

**Would someone volunteer to take responsibility for completing the current work on deprecation?**

The primary responsible party (PRP) doesn't necessarily have to do all the work, but would help figure out exactly what needs done, and then drive it to completion.

I think this would involve the following steps:

- go through https://github.com/exercism/discussions/issues/40 and reading all the issues that are linked from that page
- list out who has been involved in the discussions—these are the people to `@`-mention with questions when you are unsure how to move forward
- document exactly what was decided and how deprecation now works (here in the issue is fine; writing a more official bit of documentation in https://github.com/exercism/exercism.io/tree/master/docs is much easier once we have collected the information in one place)
- figure out which exercises are deprecated, and what needs to be done to get the deprecation completed across all the tracks
- make a plan and suggest it here
- (then probably) create individual issues for specific tasks that can be tackled

There are also folks hanging out in https://gitter.im/exercism/dev who can probably help puzzle things out.

**Comment by stkent** [comment]
Confirming that deprecation of strain is planned ([1](https://github.com/exercism/x-common/issues/588#issuecomment-279275431), [2](https://github.com/exercism/xjava/issues/297#issuecomment-282514117)).

**Comment by SarahDHealey** [comment]
@kytrinyx I am willing to take this on and to work through the steps outlined above. Please note: I do not have any prior experience in documentation.

**Comment by kytrinyx** [comment]
@SarahDHealey Awesome! If you have questions or get stuck or just feel like you need to think out loud, do not hesitate to holler or post comments here as you go along.

This is the first time I've made a "detective work needed" issue, so I'd be excited to hear how it goes and what we could do better next time to make it easier for someone to tackle.

**Comment by SarahDHealey** [comment]
@kytrinyx Thanks! I will take it on and start organizing. I'll keep you posted and holler out when I get stuck or run into issues.

**Comment by kytrinyx** [comment]
@SarahDHealey just checking in to see how you're doing on this. Any initial thoughts about what you've found so far?

**Comment by SarahDHealey** [comment]
Here is the spreadsheet that I put together with the conversations, will need to keep going to document all of them: https://docs.google.com/spreadsheets/d/1StkN65SJckvfPZU-tw-N0YjjiEamuV-zkCwEZBEH08w/edit?usp=sharing

**Comment by SarahDHealey** [comment]
I've got another summary going here: https://docs.google.com/document/d/10kUdbPCT7zBJ1QydHFQouIZa-DH7zHuBH3n7iCgEojo/edit?usp=sharing
So far, it has still been just notes and wrapping my head around it. I'll be working more on the documentation today and through the weekend. My thoughts are to document 1. the steps for the name change. 2. the steps for how hamming was deprecated and 3. If all-your-base was deprecated, how the steps were taken to deprecate all-your-base.

**Comment by kytrinyx** [comment]
@SarahDHealey This is so good!

One thing to note is that `all-your-base` is the replacement that deprecates the four similar exercises: `binary`, `trinary`, `octal`, and `hexadecimal`. So `all-your-base` isn't deprecated.

**Comment by jtigger** [comment]
Wow, this is a really thorough treatment of the topic, @SarahDHealey !  Thanks for taking the time to amass all this!

I have a general question: do we every truly want to allow an exercise's identity to be mutable?  This comes-up prominently in the "Change Name" scenario.  What would happen if we consider an exercise, despite its near identical content to another exercise merely as a new one?  Old submissions stay with the old exercise; new stay with the new.

**Comment by kytrinyx** [comment]
> What would happen if we consider an exercise, despite its near identical
content to another exercise merely as a new one? Old submissions stay with
the old exercise; new stay with the new.

That would be much cleaner. We could give people access to both if they do
either of them (some sort of cron job. Maybe not indefinitely).

Or have @rikki- post a comment about the deprecation on all the submitted
old ones saying "hey, rewoork this and submit to..."

>

**Comment by kytrinyx** [comment]
We've got this sorted with the new site. Closing! Thanks y'all.
