### ISSUE TITLE
Introduction to the benefits of reading and reviewing code

### ISSUE THREAD

**Issue by nilbus** [exercism/discussions#125]
As part of an effort to motivate peer review (#88) by introducing game design elements (#123), we would like to introduce our users to the benefits of reading and reviewing code, in the form of both asking questions and providing feedback.

Motivation
---

In terms of game design, this onboarding step should help motivate reviewers by helping them understand how their underlying motivation (learning a language) is very directly connected to the goal asking them to set (code review). Understanding how doing code reviews accomplishes their own goals for being here will bolster their intrinsic motivation to do it and increase quantity and quality of reviews. To accomplish this goal, the wording must be presented as informational (this should help you accomplish what you really want), rather than controlling (please do reviews for the sake of our system).

Other connected desires may include:
- Become a more respected and helpful peer reviewer at work
- Learn how to ask the right questions, such that you get the understanding you're seeking
- Hate reading others' code less, by becoming good at it
- Get better at expressing and explaining what good code looks like, and why
- Increase speed of understanding others' code
- Better recognize code smells, both in your own code and others'
- Altruistically wanting to provide feedback to others who want it

@kytrinyx suggested these in #88 as likely reasons for others' non-participation. There may be others as well—please suggest.

> * They don’t realize the benefit. You learn more from giving feedback than getting it. It forces you to:
>   * Read code. Like actually, really read it.
>   * Recognize code smells.
>   * Articulate your thoughts and opinions about readability, simplicity, performance, design, idioms, conventions. This pushes you to a much deeper understanding of concepts, and uncovers those  areas where you don’t actually understand something (which can lead you to go learn about it).
> * They are intimidated.
>   * They might be wrong. People might be smarter than them. They might get laughed at or ridiculed. People might say mean things.
> 

How/when to deliver the message
---

My initial thought is to introduce a new modal dialog that appears _only once_ for each user or session. This should appear at a relevant time as early in the process as possible (so it's not missed completely)j sign-up? front page? first time looking at others' submissions? Any of these, so long as it's dismissed only once? What about in the cli or gui clients? What are your thoughts?

Message wording
---

Could some pull this information together into a compelling explanation of the benefits of reading and reviewing code?

**Comment by StudentOfJS** [comment]
I think there is concern about offending others by offering advice when it is not wanted. A simple flag or opt-in for users wanting advice per submission would illuminate who wants help. It would remove potential reviewers concerns and simple list of "reviewable submissions" would make it obvious where to start reviewing. Taking it one step further, the entries on that list with the least reviews could get bumped to the top of the list. Although this last idea could be tricky if there were a sparse amount of  reviews.

Just brainstorming here, but allowing anonymous comments that are private unless approved by the owner of the submission could also alleviate any psychological barriers.

**Comment by nilbus** [comment]
@StudentOfJS Good thoughts. There's a good discussion of unwanted advice in #55. I also remember another thread that suggests your idea of explicitly requesting review, and I agree that would be helpful in getting reviews where they are most wanted.

**Comment by kytrinyx** [comment]
@StudentOfJS it sounds like you're brainstorming—would you do that in a separate (new) issue if there are no relevant ones that are open? This issue is specifically focused on writing copy to explain the benefits of code review.

**Comment by kytrinyx** [comment]
@nilbus we're tracking this as a requirement for the redesign / new prototype.

/cc @nicolechalmers if you have any extra notes you want to take based on this one, now's the time :)

I'm going to go ahead and close this, as we're tracking it separately.
