### ISSUE TITLE
Rethinking 'status'

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#13]
Right now the `exercism status` command is a bit of a mess. I'm not sure how helpful it is (for one) and the messaging is confusing.

I'd like to rethink this from the ground up.

What are the different use cases? What states can people be in, and what would be useful for the person to know?

See https://github.com/exercism/cli/issues/308

**Comment by tejasbubane** [comment]
These can be included in the status command  for a particular language:

* Number of attempted, completed and total problems
* Last submitted, current and/or next problem

**Comment by kytrinyx** [comment]
Yeah, the status command is a great place for the next problem.

**Comment by Tonkpils** [comment]
We should think about what `status` means in each context (global, track, problem). In each of those contexts we could scope down what the command displays in a much better way. That is unless we want to just keep it a one specific context?

**Comment by kytrinyx** [comment]
No, I think that all commands should probably be considered in each of the contexts (global, track, problem).

**Comment by kytrinyx** [comment]
I'm closing this in favor of a much more comprehensive rethinking of the entire user interface of the CLI: https://github.com/exercism/discussions/issues/35
