### ISSUE TITLE
Submissions with multiple files are displayed always alphabetically.

### ISSUE THREAD

**Issue by kotp** [exercism/discussions#130]
@rbasso commented on [Mon Nov 28 2016](https://github.com/exercism/exercism.io/issues/3277)

I'm not sure if this was intentional or an *accidental feature*, but solutions submitted with multiple files are always displayed with the files ordered alphabetically, despite the order supplied to the command line client.

Step to reproduce:

```bash
$ cd exercism/foo/bar
$ touch a b c
$ exercism submit b c a
$ exericsm open foo bar
```

This behavior is undesirable, because it doesn't allow users to put what they consider more important first, and also forces reviewers to scroll down searching for the most critical parts.

---

@kytrinyx commented on [Mon Nov 28 2016](https://github.com/exercism/exercism.io/issues/3277#issuecomment-263422738)

This is unintended (I totally never thought about it)—and I think it's worth thinking about a fix.

Implementation detail: we store the files as a hash / dict / map which by definition is unordered. Right now we're using Ruby, and ruby hashes happen to be ordered, but it's not something we can rely on. So we would need some explicit way of ordering them or defining an order.

---

@kytrinyx commented on [Thu Mar 30 2017](https://github.com/exercism/exercism.io/issues/3277#issuecomment-290501216)

The recommendation here is to store (and submit) the files in the order that they are submitted. I think that is the correct behavior.

In order to fix it, though, we're going to need to discuss how to tackle it, and it's likely going to involve both CLI and API changes.

@rbasso would you mind moving this to the discussions repo so that we can hash out the details there, and then open prescriptive/actionable issues in the correct places once we figure that out?

**Comment by Insti** [comment]
Some breadcrumbs: 

The [cli api submits](https://github.com/exercism/cli/blob/master/api/api.go#L172) files to:
`http://exercism.io/api/v1/user/assignments`

Which is handled by [`api/v1/routes/iterations.rb`](https://github.com/exercism/exercism.io/blob/master/api/v1/routes/iterations.rb#L43) in the [exercism.io](https://github.com/exercism/exercism.io) repository.

Questions: Does exercism.io receive the files in the correct command line order?

**Comment by kytrinyx** [comment]
> Questions: Does exercism.io receive the files in the correct command line order?

No, it's a `map` type, which is deliberately randomized. If we want to preserve order, we would need to make it a `Slice`.

**Comment by kytrinyx** [comment]
I've added this to the list of concerns we need to take into account with nextercism, as well as in the CLI redesign issue. I'm going to close this issue.
