### ISSUE TITLE
Is anyone coming to OSCON in Austin, TX (USA) on May 10-11?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#132]
I'm applying to be a part of the Open Source Alley at OSCON.

Are there any maintainers / active contributors who will be in Austin on May 10th-11th who would be interested in helping out at an Exercism stand for 4 hours one of those days?

If we get selected, I need **one person** in addition to myself to help staff the booth/stand. An expo pass would be provided, if you don't have one.

I'm already going to be at OSCON for work.

**Comment by ryanplusplus** [comment]
Damn, I'd love to help out, but this is the first year in a while that I will not be going.

**Comment by kytrinyx** [comment]
Thanks everyone. I think I've got this sorted.
