### ISSUE TITLE
Feedback (python track survey)

### ISSUE THREAD

**Issue by behrtam** [exercism/discussions#137]
I conducted a small survey in the Python track for the last ~7 days. One of the questions was about possible feedback. I thought I share this part with all of you.

`Do you have any feedback? What could be improved? What do you like about exercism?`

You can find the other questions here: [Micro Survey 1/2017](https://gist.github.com/behrtam/9b1aaae227b5e67dd145ecd5f74e58eb)

> I love the exercises. They're a very good way for me to practice while learning python. The only difficult part is finding a way to get feedback from other developers. I don't know if there is a way to improve that. It's the only part about the experience that's difficult.

> More links to resources on how to learn Python, more discussion of programming theory (object-oriented and why it's such a big deal, approaches to programming "pythonically", e.g. things Python does that other languages do not do).

> I hope I can set hard level when I fetch exercise to do. and I want to know the most pythonic way to the exercise.

> It's a great tool for learning. I have about half my team at work using it on a regular basis. Not sure I have any useful criticisms.

> I once saw totally different test cases when I looked at the python repo because they got changed. Is there a way to update the test files I already downloaded?

> I really like exercism especially because of the CLI. This way I can easily use Sublime instead of some wired online editor. It would be great to have categories for the exercises and a way to pick exercises from a certain category instead of just the default order.

> If Python is my first try for Exercism, I would stuck with Meetup etc., but it's best for someone who learn additional programming language. Even if my Ruby experience is not so long, Ruby Exercism experience helped me a lot on Python Exercism. I do not think this simply means Exercism should prepare easier version, rather I think this simply means 1) we all need some efforts (even it's little hard) to master new things, and 2) learning multiple languages is the best way to understand the programming.

> Maybe it's me, but once I leave feedback for someone, I don't know how to go back and look if they've replied.

> I like the current exercises. Maybe include exercises with some applicability like math, stats, working with files, poltting... But i understand that is hard to test.

> I love that it's done from the command line. Greatly simplifies my user experience.

> Exercism is nice service. thank You for your developing!

> The recent effort to generate more feedback seems somewhat forced to me. It's better to let people comment when they feel like it than try to push them to comment. Also, I'd like to be able to submit new iterations to projects even after moving on to newer problems; it seems like I only get suggestions for improvement on old projects. Most importantly, the Linux version of Exercism should have man pages.

> put some more indrustry-oriented exercises that use API's, just for practice

> It might be a good idea to propose the exercism again to to force retreat after a first review or a number of exercisme.

> I think, exercism is great, thank you! To improve something like badges/achievements/challanges can be used - people like to participate in competitions :)

> I always use exercism as one of the first steps to discover new languages. Some comments (if there are any, sadly) really helped me.

> I really like Exercism because it gives simple instructions on setting up the development environment and tests. The tests provide a concrete sense of progression. Feedback is also helpful but sometimes uncommon -- i.e. there are one or two frequent commentators on the Haskell and Rust tracks, and if they took a break or lost interest, those tracks would lose interest/focus. Getting people to review and comment on other people's exercises would be great!

> Thank you so much for Exercism, it's fantastic! If I can wish for improvements, it would be exercises that require me to do something more than purely implementing an algorithm, i.e. writing more of a fleshed-out application. I don't have any real-life work experience in programming, and I think exercises that required a bit more planning and foresight would be extremely valuable to me.

> Encourage more senior people to comment on posts and help people code more pythonically. Sometimes I feel like I'm writing Java in python or that my solutions are very hackey but I don't get a lot of feedback.

> I like these exercises and working well.

**Comment by kytrinyx** [comment]
This feedback is so valuable! Thank you so much for making the survey, fielding it, and sharing the results.

**Comment by iHiD** [comment]
This is awesome. Thank you @behrtam! 💙

**Comment by kytrinyx** [comment]
We used this (and other useful feedback) in the process of developing the new site. I'm going to go ahead and close this. Thank you 💙 💛 💙
