### ISSUE TITLE
I will be away for a few days

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#138]
Something unexpected came up, and I will not be available for the next few days.

I apologize in advance for dropping the ball on things.

**Comment by iHiD** [comment]
💙

**Comment by robphoenix** [comment]
Life has a way of taking over, no need to apologize.

**Comment by kotp** [comment]
We all hope it is unexpected happy things!  Either way, our thoughts are with you.

**Comment by kytrinyx** [comment]
I'm kind of back. My availability is still greatly reduced, but I am slowly starting to go through the backlog of things, and I can be reached.
