### ISSUE TITLE
Can we offer synchronous time to each other?

### ISSUE THREAD

**Issue by kotp** [exercism/discussions#14]
@kytrinyx and I were chatting today, and we are considering how we would let people know that we are available for pair programming or one on one help.

The question is:

> So what do you think we can do to let people know that they can have "synchronous time" with some of us?

I have paired with a few folks that either aren't (yet) contributors, want to contribute but aren't sure how, or are now contributors, or even maintainers on Exercism.  

But it isn't easy to know what is the appropriate way, or even if you should, contact someone to lend a hand.

We would like to find out if, and how, we can let people know that we are human, we are available, and we want to help them help us with the site, in whatever way they would like to.

Do we use the gitter support room?  Do we have a page here with some kind of status indicator?  How do we get the word out?  How do we keep that word out there?

What are your thoughts?  How do we let people know that we are willing and available?  Or willing, but not available, at the moment.  But inviting, and welcoming to that kind of behavior?

**Comment by k4rtik** [comment]
One option is to maintain a common [Doodle](http://doodle.com) page. Haven't used Gitter much, but I am aware of a scheduling tool for Slack/Hipchat -- https://meekan.com

**Comment by kytrinyx** [comment]
I think that this is an admirable suggestion, but I don't know that I would like to manage this centrally in any way, as we've already got a ton of overhead trying to manage the asynchronous discussions.

I'm going to go ahead and close this, however I have opened a discussion in https://github.com/exercism/exercism.io/issues/4111 specifically to discuss the possibility of more synchronous discussions for maintainers.
