### ISSUE TITLE
create general .gitignore

### ISSUE THREAD

**Issue by katrinleinweber** [exercism/discussions#140]
Hello, and 1k thanks for providing the exercisms :-)

It seems that [many people like to version-control their [exercisms](https://github.com/search?q=exercism&ref=opensearch). Because: 

1. from a learner's point of view, some files of each problem are effectively static, and
2. those files' history is captured here by the Exercism maintainers,

I think offering a general `.gitignore` on [gitignore.io](https://www.gitignore.io) would be a neat service to help learners focus the version control on their own problem solving work. Is that something that would be of interest to your project? I'm not affiliated with them (just an avid user) and their [contribution guidelines](https://github.com/github/gitignore#contributing-guidelines) mention "projects" specifically.

I started an example based on some random `Hello, World!` problems: [katrinleinweber/gitignore/excercism/Excercism.gitignore](https://github.com/katrinleinweber/gitignore/blob/excercism/Excercism.gitignore). My idea would be to work through the problem files to identify more of the "static" ones, and then [open a PR](https://github.com/github/gitignore/compare/master...katrinleinweber:excercism?expand=1).

What do you think? Open questions from my point of view would be:
- [ ] Is there a single download of all languages and all problems? Tried `exercism fetch all` &  `exercism fetch *`
- [ ] Should a potential `Excercism.gitignore` be considered [global](https://github.com/github/gitignore#folder-structure)?

Cheers!

**Comment by petertseng** [comment]
Specific tracks have gotten this question before... okay, I'm exaggerating, just one track: https://github.com/exercism/xrust/issues/192

I wonder if this could be provided as a track-wide file as in https://github.com/exercism/x-api/issues/29 / https://github.com/exercism/cli/issues/388 since different files will likely be appropriate for different tracks. Of course if there is a way to come up with a catch-all then so much the better.

**Comment by katrinleinweber** [comment]
Thanks for the hints! So, the general .gitignore could be an intermediate solution, until the tracks bring their own, I presume.

I don't know an automatic way to generate the rules (nor to [deduplicate them](https://stackoverflow.com/questions/32375307/is-there-an-automatic-way-to-deduplicate-gitignore-rules)), but reading up on the file types I don't know about yet, might be a good execism in itself ;-)

**Comment by ErikSchierboom** [comment]
Good suggestion! Although it would be possible to create a single `.gitignore` file for all languages, I would prefer not to do that. IMHO, there are a two main disadvantages of having one, global file:

1. It will become *huge*, making editing it very inconvenient.
1. It will have to be maintained in x-common, whereas it really is track-specific and should thus logically be maintained in the track repository.

The ideal solution should thus be a track-specific file that is maintained by the track maintainers themselves, or possibly even using the default gitignore as specified on gitignore.io.

Unfortunately, there is no support for track-specific files at the moment. I do think it would be great if someone could work on implementing the track-specific files, as that would be a great feature that can also be used for lots of other scenarios.

**Comment by kytrinyx** [comment]
> Although it would be possible to create a single .gitignore file for all languages, I would prefer not to do that.

I second that.

> there is no support for track-specific files at the moment.

We're very close. We have support for it in the API, but we don't have support in the CLI yet. The open issue for it is https://github.com/exercism/cli/issues/388

**Comment by katrinleinweber** [comment]
OK, thanks for the info. I conclude that neither an intermediate solution is still really necessary, and a general one would be inadvisable. No worries :-)

**Comment by kytrinyx** [comment]
@katrinleinweber Thanks for kicking off the discussion and shepherding it to a close!
