### ISSUE TITLE
Probot and stale issues.

### ISSUE THREAD

**Issue by kotp** [exercism/discussions#141]
Now that we have had the Probot up and working for long enough, I have noticed the following things:

Probot will remove the label that it gives when marked stale if it moves the issue to closed.  I feel this gives the wrong communication.  Just because it is closed does not make it less stale.  If someone wants to look at the stale issues, it should be something that they can do.  It wasn't decided to close the issue and not fix the problem, as in a 'wontfix' label would communicate.

It should be clear that it was closed only due to it being stale. Removing that label removes that communication.

**Comment by petertseng** [comment]
I don't have Probot stale on any track I'm a maintainer of, but I couldn't help but notice that at https://github.com/exercism/cli/issues/227#issuecomment-298192319, and other issues in exercism/cli, the issue was closed by probot **without** removing the label. How does this reconcile with the above?

**Comment by petertseng** [comment]
If there is a desired behaviour change, should it be filed at https://github.com/probot/stale ? Is this a place for us to discuss whether there is a desired behaviour change, before filing at the repo?

**Comment by petertseng** [comment]
Note that since the label was not otherwise configured in https://github.com/exercism/cli/blob/master/.github/stale.yml, it is wontfix, and the label remains on that issue.

**Comment by petertseng** [comment]
What should we take away from this discussion?

**Comment by kotp** [comment]
I thought the same thing intially about filing at the probot repository, but wanted to confirm that the behavior that I am noticing is something to report.  They likely have a lot more exposure in how others use it, I want to confirm how we want to use it.  I have jumped the gun a little bit though, since what I thought I saw was not what I saw.

The behavior on that cli issue you mentioned is a good indicator that it is working.  At the moment, I think it is the team that is closing the stale ones, instead of letting them self-close.  I just checked the Ruby track, and every one that has the probot message in it and are closed were closed by humans (me included).

**Comment by petertseng** [comment]
So the circumstances under which the action (remove the label) is taken were not what they appeared to be. Nevertheless, it could still be the case that there could be an improvement in the behaviour.

One idea might be "the bot can refrain from removing the label from closed issues when it otherwise would", if I understand correctly.

**Comment by Insti** [comment]
See: https://github.com/exercism/cli/issues/53
Probot left the `wontfix`(/stale) label on the issue when it was closed, but commenting on the issue caused the `wontfix` label to be removed.

> the bot can refrain from removing the label from closed issues

Sounds about right.

**Comment by kotp** [comment]
Or re-labeling when that label is removed.

**Comment by kytrinyx** [comment]
I think it's worth discussing here for clarity before opening an issue in probot/stale. If we do have a suggestion, we should open an issue there.

I think that at the moment the behavior seems correct: Probot removes the "stale" label (whatever it's configured as) if a human takes action.

**Comment by kotp** [comment]
Should there be something that indicates that even though it is in the closed section, that it is still potentially up for grabs?  The 'stale' flag would do this, but if Probot removes it (even if we place it back on) then there is something else that may need to be done.

**Comment by kytrinyx** [comment]
> The 'stale' flag would do this, but if Probot removes it (even if we place it back on) then there is something else that may need to be done.

I don't understand why probot would remove it.

If the issue is stale and probot closes it, it will have the stale label on it.

**Comment by kotp** [comment]
Because of activity.  I think @Insti can describe this better, as he was kind of fighting with it at one point.

It shows that behavior here on one that was manually closed, but then I changed the status to "stale" to show that we would accept work on it, it is just stale, and Probot immediately removed the label.

![selection_006](https://cloud.githubusercontent.com/assets/16747/26184802/f8a74448-3b54-11e7-9dc0-5ebb403d06db.png)

**Comment by kytrinyx** [comment]
Right, I believe that at the moment probot's label can only be used by probot. If you manually add a `stale` label to something that has recent activity, then it's by definition not stale, and so the label will be removed.

The interesting edge case here is for `wontfix`, which is the default label, and which might be used for many other reasons than something being stable. In that case, if probot removes the label, I think that would be considered a bug.

**Comment by kotp** [comment]
The interesting edge case is why I changed the Ruby track to "stale" rather than wontfix.  But yes, probot will remove the wontfix label as well, if that is the default, if there is any communication/activity on the issue... so it is definitely undesired in that case as well.

**Comment by kytrinyx** [comment]
@kotp This to me is the clearest explanation of why it might not be desirable. I'd suggest opening an issue over on the probot/stale repo to discuss whether or not it's a problem / how to potentially address it.

**Comment by kotp** [comment]
Great, yeah, I wasn't sure if it was something that really is a problem, so it is good that it is articulated here first.

Good talk. :wink:

**Comment by kotp** [comment]
I find that probot/stale#7 is addressing this complaint.

**Comment by Insti** [comment]
Did you mean: https://github.com/probot/stale/issues/18

**Comment by kotp** [comment]
Update: Confirmed that ~~we are~~ I am no longer needing to fight with the Probot!
