### ISSUE TITLE
Alternative submissions to exercises

### ISSUE THREAD

**Issue by rmoorman** [exercism/discussions#142]
If I am not mistaken, there is currently no way to submit a solution to an exercise without marking it as an _iteration_.
In my view, a series of iterations is a progression from one stage of implementation to another where the first iteration is often less "ready" than the iterations that come after it.
Oftentimes, however, there are multiple solutions to a given problem, depending on the point of view (e.g. requirements on runtime efficiency, memory consumption, reusability, ux ...) and problems could be approached from a different angle.
(being quite new around here, I don't know if there are exercises which could be implemented differently though, so please correct me if I am mistaken :-))
Those solutions are not iterations of each other.

One could use multiple solution files (one file per solution) but then iterations that have been made on each of the solutions independently end up as iterations of the "whole". 
So how about making it possible to submit a solution as alternative solution (opt in) and iterate on each solution independently?

**Comment by iHiD** [comment]
@rmoorman Great point! This is something we're actively addressing in the [Exercism redesign](https://github.com/exercism/discussions/issues/113). We haven't exactly worked this out from a UI POV yet, but we have determined that it needs to factor into the data model, and that it will be part of the UX.

**Comment by ErikSchierboom** [comment]
Great idea!

**Comment by kytrinyx** [comment]
Since this is in the works, I'm going to go ahead and close the issue. Thanks 🌷

**Comment by rmoorman** [comment]
Great! I am looking forward to it :-)
