### ISSUE TITLE
Clarify terminology: exercise, problem, specification, implementation

### ISSUE THREAD

**Issue by Insti** [exercism/discussions#145]
Now we have a glossary: https://github.com/exercism/docs/blob/master/glossary.md

It defines the following terms:

> specification - a language-agnostic description of a problem. These live in the x-common repository

> exercise - a language-specific implementation of a specification. Typically consists of a test suite and a README

Would it be a good idea to rename the `x-common/exercises` directory to `x-common/specifications` to match this naming scheme?

**Comment by Insti** [comment]
One downside would be that `exercises` is pretty widely used.

Non exhaustive list:
* Trackler
* Generators (multiple language tracks)

**Comment by petertseng** [comment]
I was thinking what might happen is that `description.md` would change name to `specification.md`, with no changes to `exercises`. Likely can get away with only editing Trackler then

**Comment by iHiD** [comment]
I'm a big big fan of this.

**Comment by kytrinyx** [comment]
I could go either way: `specifications/` directory, or a `specification.md` file. I'd love to hear it if anyone has thoughts about pros/cons.

**Comment by Insti** [comment]
Today I feel strongly in favour of `specifications/`

Reasoning:
* `exercises` is the term that we are trying to avoid misusing.
* `specification.md` still requires changing something, but doesn't eliminate the problem of `exercises` being overloaded/misused.
* Consistency is important.
* The fix is a "simple" `s/exercises/specifications/`
* I don't think anyone has ever claimed the Exercism "API" is stable and will not be changed.

**Comment by petertseng** [comment]
I should have noticed it before, so sorry for not noticing! Yes, it is because the usage of `exercises/` as a directory definitely conflicts with the glossary's definition of an exercise!

I notice that we may also incorrectly use the term "exercise" in prose as well. I might often say "the Hamming exercise" without having a specific language's implementation in mind. It seems like I will need to adjust my thinking.

As you can see, my old thinking was based on exercises being language-independent as well, and consisting of a specification plus other things. I'm at a loss as to what I might propose the "other things" are. Is metadata separate, or part of the specification?

So if we look at the two proposed results right now:

```
specifications/*/description.md
specifications/*/metadata.yml
specifications/*/canonical-data.json
```

```
exercises/*/specification.md
exercises/*/metadata.yml
exercises/*/canonical-data.json
```

It would be all about which seems to make sense to people.

I can certainly see now that the former is more consistent with the current glossary.

The latter is not inconsistent with my current way of thinking (this isn't an argument for it, just acknowledging the absence of an argument against it), but also shows that my way of thinking is in contravention of the glossary. Sorry about that.

**Comment by Insti** [comment]
How much of how we currently refer to things is due to fundamental "exerciseness" and how much is due to familiarity?

The main problem is distinguishing between what are currently defined as `specifications` and `exercises`

Suggestions for different definitions are encouraged/welcome.

**Comment by Insti** [comment]
"Spitballing"
Generic: exercise
Track specific: assignment

**Comment by Insti** [comment]
Further thought:
Renaming `exericses/` in x-common will be less painful than needing to rename `exercises/` in all tracks.

**Comment by mhinz** [comment]
Why do we need a new term "specification" at all?

Prior to this we had "problem" for theory and "exercise" for practice. The difference is easy to explain to every new user.

When I started looking into Exercism a few days ago, I actually liked that the directory is called `x-common/exercises`, as for every other track. (Although the  repo should have been called `xcommon`, but I bet that came up in other discussions before. :>)

This organization has many repositories and lots of documentation, so I'd like to keep the glossary as small as possible and the introduction of "specification" seems rather arbitrary. Well, maybe not _arbitrary_, but the term seems a bit too specific (pun intended) for its own good.

I just don't see how this new term would help to make any conversation clearer, and if it doesn't, it's perhaps not needed at all.

If we had to rename `x-common/exercises`, I'd vote for `x-common/problems` instead.

**Comment by Insti** [comment]
Thanks @mhinz, this is a very good argument against changing anything.

> I just don't see how this new term would help to make any conversation clearer

It is currently needed by trackler, x-api and exercism.io but I agree the distinction is not important (and possibly unhelpful) at the abstraction level that a track maintainer deals with.

If we don't end up changing the directory name, I still think `specification` should remain in the glossary as documentation of the internal usage.

**Comment by kytrinyx** [comment]
For the past 18 months or so I've been using `problem` for the generic term (language-agnostic) and `implementation` for the language-specific implementation of a problem, with `exercise` being a catch-all for talking about either at an abstract level in casual conversation or prose.

I can't remember off the top of my head why @Insti thought this was a bad idea.

**Comment by kytrinyx** [comment]
I also wanted to say: I should have opened a discussion here about the glossary before creating it. I've been making up terms on my own, but we really need more perspectives to get the best set of terms. I should not have just decided that out of the blue.

My apologies!

**Comment by mhinz** [comment]
> I should not have just decided that out of the blue.

A common wisdom in many texts about productivity is that sometimes it's better to just get to a decision quickly and backpedaling later if one must, because that's still faster than discussing about it for weeks (and then maybe still deciding for the wrong thing).

That surely doesn't work for every decision, but I think it does for this one.

Often it's these small details that keep people from being more productive. (Oh how often I finished a commit quickly and then wasted time finding the best variable names.. [Pareto](https://en.wikipedia.org/wiki/Pareto_principle) and all that.)

So.. I'm really fine with either decision as long as people stick to it. :-)

**Comment by kytrinyx** [comment]
> A common wisdom in many texts about productivity is that sometimes it's better to just get to a decision quickly and backpedaling later if one must

In this case I'd rather open up the question for discussion for a week and then make the decision. In general within the first few days there's either no discussion (usually because it doesn't seem to matter much either way), or a few great insights and arguments that make a good direction obvious. It's not always the case, but I'd rather leave it open for a few days to guard against my lack of perspective.

**Comment by Insti** [comment]
> For the past 18 months or so I've been using `problem` for the generic term (language-agnostic) and `implementation` for the language-specific implementation of a problem, with `exercise` being a catch-all for talking about either at an abstract level in casual conversation or prose.

> I can't remember [...] why @Insti thought this was a bad idea.

In itself, this is not a bad idea, and if it was how the concepts were consistently referenced there would be no issue, however there are inconsistencies in the way these terms are used throughout the codebase.

[trackler](https://github.com/exercism/trackler) uses `Problem` and `Implementation`
Which is helpful in the context of trackler but less so for exercism.io

The [exercism.io domain knowledge (glossary)](https://github.com/exercism/exercism.io/blob/master/docs/overview-architecture.md#domain-knowledge)  is consistent with the current glossary apart from its coverage of problems/exercises where it states:

>   * Problem is an Exercism exercise.

This makes no distinction between implemented and unimplemented problems.
And "problem" is generally used as if it were an implementation.

This causes code contributors confusion and leads to things being implemented in the "wrong" place making the code more complex than it need be, and harder to build upon.

The suggestion to move toward using `Specification` and `Exercise`, see https://github.com/exercism/trackler/issues/40 was an attempt to try and resolve some of this confusion without adding to it by changing the meaning of "problem" for either codebase.

Thanks to @mhinz, I am beginning to suspect that the distinction between implemented and unimplemented specifications is not as important as it appears and getting unimplemented exercises should just be a case of doing something like: "fetch all problems where track is null"

I have development branches of the various repositories where I am exploring this concept.

For the issue in the topic: My current opinion is that we should NOT rename the `exercises` directory.

**Comment by kytrinyx** [comment]
> Which is helpful in the context of trackler but less so for exercism.io
> [...]
> an attempt to try and resolve some of this confusion without adding to it by changing the meaning of "problem" for either codebase.

The exercism.io codebase should not be relevant here in any way. I've said this before. It's confusing. It's going to go away. It's not relevant. If Exercism.io is truly a problem for people, then we should discourage people from contributing until we have a new codebase in place. I really don't want that mess to influence our choices.

I wrote Trackler from the ground up trying to make it consistent with how I used terminology. Then everything else can get updated to use the same terminology. Trackler is the only part of Exercism that I'm mostly happy with in terms of understandability. Mostly.

> This causes code contributors confusion and leads to things being implemented in the "wrong" place making the code more complex than it need be, and harder to build upon

Yes, that's fine. If I wanted the exercism.io codebase to become simpler, I would refactor it. But I'm not going to do that. x-api and exercism.io are both going to go away. Not that x-api is much of a problem, to my mind.


> For the issue in the topic: My current opinion is that we should NOT rename the exercises directory.

So should we clarify the glossary to remove the term _specification_? Should we go back to _problem_ and _implementation_ for the language-agnostic problem definitions and language-specific exercise implementations? Is it OK to use _exercise_ as a catch-all term for a problem or an implementation depending on the context?

**Comment by mhinz** [comment]
> So should we clarify the glossary to remove the term specification? Should we go back to problem and implementation for the language-agnostic problem definitions and language-specific exercise implementations? Is it OK to use exercise as a catch-all term for a problem or an implementation depending on the context?

\**nods\**

Putting the glossary that I have in mind into sentences:

---

People come for the **exercises** and each exercise consists of the **problem** to solve and its concrete **implementation**.

Problems evolve over time, so they're versioned.

A **solution** (or the **iterations** it consists of) is an implementation of a problem in a certain **language**.

---

And although `x-common` doesn't provide implementations, just problems, I'd be okay with keeping the directory name `x-common/exercises`, because of the familiarity mentioned a few comments above. (Argument being that using the same directory hierarchy makes it instantly feel like any other track repo.)

In my mind _problem_ and _specification_ can be used interchangeably and we should decide for one of them.

**Comment by kytrinyx** [comment]
@Insti I like this.

> People come for the exercises and each exercise consists of the problem to solve and its concrete implementation.

Based on this, I think it would be fine to keep the name `exercises` in x-common, though I do see where it can make it feel like any other track.

> In my mind problem and specification can be used interchangeably and we should decide for one of them.

Yeah, that sounds right to me. I don't care strongly about problem vs specification, but lean towards problem because it's what I've used for a while.

**Comment by Insti** [comment]
> So should we clarify the glossary to remove the term specification? Should we go back to problem and implementation for the language-agnostic problem definitions and language-specific exercise implementations? Is it OK to use exercise as a catch-all term for a problem or an implementation depending on the context?

"Exercise" is a good catch-all term, "problem" and "implementation" are adequate terms and I would have no issue with continuing to use them if they could be used consistently.

That said.

Consideration 1:  Abstraction Level

There is an abstraction level mismatch in these names.

> People come for the exercises and each exercise consists of the problem to solve and its concrete implementation.

(I also like this)

But if I can rewrite it slightly for my example, hopefully without changing its meaning:
People come for the exercises and each exercise consists of the specification **of a problem** to solve and a concrete implementation **of that problem**.

"specification" and "implementation" are the words that describe properties of a problem 

And if we were to use them as properties of an exercise:

specification of an exercise - OK
problem of an exercise - this sounds completely wrong to me.

Consideration 2: Usage

2a: Dependency
You can have a specification without an implementation, but you cannot have an implementation without a specification, and if you have an implementation you always want the specification. This thinking lead to the trackler pull request: [An Implementation is a Problem](https://github.com/exercism/trackler/pull/38)

2b: Frequency
The most common thing to deal with in exercism.io (version 1 and, I assume, the proposed version 2) is/will be implementations ("Implementation" is a strange word to use on its own as in this context it is essentially always followed by "of x"). The term commonly used to describe an implementation is "problem", which seems to me like a reasonable thing to want to do. 
Current code example:
```
track.implementations.each do |problem| 
```
(I know kytrinyx wants the current exercism.io to go away, I think this demonstrates the intention to want to talk about "problems".)


These 2 points lead me to my initial proposal: https://github.com/exercism/trackler/issues/40 which was for:
'Trackler::Problem' => 'Trackler::Specification'
'Trackler::Implementation' => 'Trackler::Problem'

The main problem with this being changing the existing meaning Problem, but I don't think this is insurmountable and is probably better if it can be resolved before version 2 begins to be implemented. 

@kytrinyx suggested Specification/Exercise which would avoid this and I think that's where this thread started.

A secondary problem with Specification/Problem is an abstraction level mismatch similar to above, but it does not bother me so much here for some reason I have yet to work out.
Possibly due to "problem" being a more familiar term and the possibility of an unimplemented "specification" still being able to be a "problem".

Options:

So I think I've now identified 4 options. (and I'm sure we could think of more.)

1. Problem/Implementation
2. Specification/Implementation
3. Specification/Problem
4. Specification/Exercise

I would rank these: 3 > 2 > 4 > 1


> problem and specification can be used interchangeably and we should decide for one of them.

If this is the choice, I strongly prefer specification for reasons argued above.

**Comment by kytrinyx** [comment]
> But if I can rewrite it slightly for my example, hopefully without changing its meaning:
People come for the exercises and each exercise consists of the specification of a problem to solve and a concrete implementation of that problem.

I do like this.

> 1. Problem/Implementation
> 1. Specification/Implementation
> 1. Specification/Problem
> 1. Specification/Exercise

Given the description above, only 2 works. The other mix levels of abstraction in problematic ways.

If we're talking about "specification of problem" (or "specification of exercise") and "implementation of problem" (or "implementation of exercise") then "problem" and "exercise" are both high-level, generic terms. The only thing that makes sense to me in this context is "Specification/Implementation".

**Comment by Insti** [comment]
> The only thing that makes sense to me in this context is "Specification/Implementation".

I agree. 
Can we put a "policy" tag on that?


Which I think leaves us only to choose between:

---
A:

People come to Exercism for the exercises and each **exercise** consists of the **specification** of a problem to solve and a concrete **implementation** of that problem.

Exercises evolve over time, so they're versioned.

The **solution** to an **exercise** is made up of one or more **iterations**

---


---
B:

People come to Exercism for the problems and each **problem** consists of the **specification** of the problem to solve and a concrete **implementation** of that problem.

Problems evolve over time, so they're versioned.

The **solution** to a **problem** is made up of one or more **iterations**

---

Or something else? Or even allow problem/exercise to be interchangeable.


I prefer "A:" as I have a slight preference for "exercise" as something you do and "problem" as the abstract concept.

**Comment by kytrinyx** [comment]
> Can we put a "policy" tag on that?

Good call. Done.

I like A:

> People come to Exercism for the exercises and each exercise consists of the specification of a problem to solve and a concrete implementation of that problem.

> I have a slight preference for "exercise" as something you do and "problem" as the abstract concept.

Yes, that is a good distinction.

> Exercises evolve over time, so they're versioned.

This is where it gets tricky for me. We said just above that exercises consist of the specification and implementation. The implementations are versioned. As is the canonical data (which, I guess, is part of the specification). These versions are independent of each other.

**Comment by Insti** [comment]
It's probably not necessary to mention the versioning in this short summary.

**Comment by Insti** [comment]
People come to Exercism for the exercises and each **exercise** consists of the **specification** of a problem to solve and a concrete **implementation** of that problem.

The **solution** to an **exercise** is made up of one or more **iterations**

**Comment by Insti** [comment]
I think this can be closed now.
Since this has a policy tag I don't know if we want to update the subject to better reflect the content of the discussion.
