### ISSUE TITLE
Add hover text to language icon and/or include language name in code preview

### ISSUE THREAD

**Issue by HarrisonMc555** [exercism/discussions#146]
I was looking at someone else's code and I realized that I didn't remember what language it was written in. I looked around and saw the logo but no other indication of what language was being used. The only reason I recognized the water drop logo as the Elixir logo was because of my time here at exercism.io.

Would it be useful to include a hover text to the language icons to indicate what language they are? And/or include some textual indication on the code/discussion page of what language is being used? I think most places that include the language's icon also have the language name, but the code/discussion preview page doesn't.

This is an example:
![exercism_icon_hover](https://cloud.githubusercontent.com/assets/22666187/26515076/9e4ad26e-423c-11e7-9f70-bfe67813d12a.png)

**Comment by kytrinyx** [comment]
> Would it be useful to include a hover text to the language icons to indicate what language they are?

Yes! That would be very useful ❤️

**Comment by Insti** [comment]
This would be done via a PR to the https://github.com/exercism/exercism.io repository.

Starting point hint:
https://github.com/exercism/exercism.io/blob/master/app/views/submissions/show.erb#L4 

The language should be available via `submission.language` (If it's not let me know.)

**Comment by HarrisonMc555** [comment]
Ok I'll see if I can figure out how to do it, if I get stuck I'll let you guys know or ask for help on gitter.
