### ISSUE TITLE
Teams: Public or Private or Secret?

### ISSUE THREAD

**Issue by Insti** [exercism/discussions#148]
## Context: 
In https://github.com/exercism/exercism.io/issues/3550
> Per [#3522](https://github.com/exercism/exercism.io/issues/3522) it seems private team names should not be revealed at all. However when viewing someone's profile, private team names appear in the listing under teams.

## Definitions:

Public - Can request membership, Searchable, Membership visible on profile.
Private - Must be invited, Membership visible on public profile.
Secret - Must be invited, Membership hidden on public profile.

The difference between public and private teams is that you must be invited to join a private team, but there is a button to request membership of a public team.

private teams are not searchable, (mainly because you can't ask to join one?)

secret teams are currently not supported.

## Questions:

Should private team membership be visible on a profile?
Should secret teams be supported?

**Comment by Insti** [comment]
My current opinions:

> Should private team membership be visible on a profile?

Yes.

> Should secret teams be supported?

No.

Secret teams are against the public code review nature of Exercism.
If you want a secret team, share your solution links via email.
What information are you trying to hide by having team membership be secret that is not available due everybody’s solutions and comments being publicly visible.

**Comment by edwardbartholomew** [comment]
Thanks for starting this discussion @Insti  I think perhaps there may be a little confusion over what Private team membership meant from myself and some co-workers. I think supporting Secret Teams would be nice but not an important feature in my mind. Maybe having the definition of what a Private Team is or isn't somewhere could be added?

**Comment by kytrinyx** [comment]
> Maybe having the definition of what a Private Team is or isn't somewhere could be added?

I think you're right that clarifying this on the website is the best fix.

My suggestion is to figure out where on the website we're currently explaining stuff about teams and adding it there. Or, having a single page of documentation about teams, and linking to it from the various places.

**Comment by kytrinyx** [comment]
We're completely overhauling teams in the new prototype, and I've made a note that we need to consider the differences between public/private/secret.

Thanks so much for bringing it up, @Insti, as I had not made the distinction between private and secret prior to this discussion.

I'm going to go ahead and close this, and once we launch the team stuff in the beta/prototype, we'd love your thoughts and observations on it.
