### ISSUE TITLE
We need a buddy-system for launching new language tracks

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#152]
In the discussion about how to start new tracks, I asked:

> Should we have a buddy system, where we assign an existing track maintainer to help mentor the new maintainer? 

@jtigger responded:

> I think this is a critical piece for a couple of reasons.
> 
> 1. maintaining an Exercism track skillfully means being collaborative: inclusive, encouraging, skeptical and open-minded.  Conveying this attitude is best done by example — mentors can do that.
> 2. communities risk losing their culture if they grow faster than their ability to absorb and align individuals' motivations.  If a language enthusiast (not already an Exercism maintainer) cannot be paired with a mentor, that's a clear indication that we've hit a growth speed limit.

I think that this is important, and I'd like some suggestions about how we should organize this.

How should we go about organizing this to make it happen? How do people volunteer or indicate interest? In the other issue I suggested the following options:

1. Ask people who are willing to mentor to watch the repository and then volunteer if they've got capacity?
1. Create an @exercism/maintainer-mentors (or something) team that can be mentioned?
1. ???

**Comment by kotp** [comment]
How do we find out if people are interested in mentoring?

1. We see them in the gitter chat rooms
2. We see their contributions and feedback on the website
3. We see their issue and pull request submissions on Github

I think all three of the resources that we use is a great recruiting area.  We get to know people through interactions, we get to know their quality of feedback and their quality of code.

**Comment by kytrinyx** [comment]
I'm talking about specifically mentoring new track maintainers as they ramp up a track. That means that the buddies need to be track maintainers (or have been track maintainers previously), because this is to catch all the little "oh, please do X", "here's how to git", "forgot to mention Y" and be available to answer questions about all the nuanced details. And then open issues and PRs in the docs repo to clarify and add missing documentation.

People in the gitter chat rooms + contributors + feedback on the website are great for mentoring new contributors, but not for making sure that the new track maintainers have solid footing.

**Comment by rpottsoh** [comment]
@kytrinyx said:

> I'm talking about specifically mentoring new track maintainers as they ramp up a track. That means that the buddies need to be track maintainers (or have been track maintainers previously), because this is to catch all the little "oh, please do X", "here's how to git", "forgot to mention Y" and be available to answer questions about all the nuanced details. And then open issues and PRs in the docs repo to clarify and add missing documentation.

What you have described is precisely what I have experienced since last October to a T, when the Delphi track was created.  You tapped @kotp to work with me.  What was the thought process you went through when you approached him?  Would that be germane to this discussion?

**Comment by kytrinyx** [comment]
@kotp did this on his own initiative—I'm so glad to hear that it was useful, which just emphasizes even more that we actually do need this!

**Comment by kytrinyx** [comment]
Alright, I'm going to add this to the list of things we need to find out, but since we're not actively tackling it in the near term, I'm going to go ahead and close this.
