### ISSUE TITLE
New website codename?

### ISSUE THREAD

**Issue by Insti** [exercism/discussions#153]
Do we have/want a codename for "the new website" and or project?

From [the roadmap](https://github.com/exercism/docs/blob/master/roadmap.md)

> we will implement the new website completely from scratch, focusing on clean, simple, idiomatic code, and good performance.

I find myself wanting to reference the new website project while commenting on a lot of issues/PRs and 'the new website' seems too vague.

I'd also like to be able to ask sensible questions about api/cli changes that might be required as part of this.

**Comment by kytrinyx** [comment]
Yeah, a codename would be useful!

I've been calling it "The Reboot", but that's kind of the whole process.

Any suggestions?

**Comment by Insti** [comment]
Nothing I really like yet.

Bad name increment puns: `Y-ercism` `Whyercism` `Exercis-N` 
Acronyms: `EV2` (Exercism Version 2) `NEW` (new Exercism Website) `NEWT` (New Exercism Website two)
"Ex" words: `exfoliate` `extrinsic` `extract` `extracate` `Exhibit B` `excision` `exciting`
Giving up: `Version 2` `Demon slayer` `Sunshine` `Rainbows` `Puppies`

**Comment by kytrinyx** [comment]
Puppies :-)

How about `exercism-reloaded`?

**Comment by rpottsoh** [comment]
[Eldorado](https://www.poetryfoundation.org/poems-and-poets/poems/detail/48634)

**Comment by tleen** [comment]
Internally i've been calling it nextercism.

**Comment by kytrinyx** [comment]
@tleen To quote a family member of mine... Oh. My. Godness. 🌺 :-)

**Comment by rpottsoh** [comment]
:+1:  for `nextercism` too.

**Comment by kotp** [comment]
* DIvIDEnd	 the Devil Is In the Details: Exercism
* Creme Six (anagram of Exercism)
* the existentialism chiseled diver (anagram of "The devil is in the details: Exercism"

**Comment by kytrinyx** [comment]
Let's go for "nextercism". It's funny while not being too cryptic (you kind of get the idea of what it's about from the name).
