### ISSUE TITLE
Allow users to self-identify themselves as newbies, experts, etc.

### ISSUE THREAD

**Issue by ryanplusplus** [exercism/discussions#16]
Many of the submissions I review are people from my office that I know personally. I've found that I tailor the types of review comments I make based on what I know (or at least suspect) they're looking to get out of exercism. I can't usually make the same adjustments for the vast majority of users on exercism, so I try to limit the types of comments that might be appreciated by an expert but could be discouraging for someone who is just starting out.

If there were some way to identify yourself and your goals with a badge, label, etc., I think it would make it easier for submitters to get kind the feedback they're looking for and for reviewers to make more effective suggestions. It may also make it easier for newbies to become reviewers because they can focus on reviewing submissions from people they can relate to.

Thoughts?

**Comment by petertseng** [comment]
I would see if there are any prior takeaways from https://github.com/exercism/exercism.io/issues/2164 and https://github.com/exercism/exercism.io/issues/2594 worth mentioning here; I do not yet have time to evaluate these myself and/or contribute new thoughts to this discussion; will be next week at the earliest before I am able

**Comment by ryanplusplus** [comment]
Thanks @petertseng, I hadn't seen those issues.

I think this is pretty clearly related to https://github.com/exercism/exercism.io/issues/2164, but focuses more on what the user is looking for than declaring mastery to short-circuit the requirement to actually do the exercises.

I think it's more or less a duplicate of https://github.com/exercism/exercism.io/issues/2594, but that was closed as a duplicate of https://github.com/exercism/exercism.io/issues/2164 which I think has important differences. So... :)

**Comment by petertseng** [comment]
I see. It seems clear to me now that when I suggested the two issues may be duplicates, I only looked at the end result and not the reason why the result was wanted. Indeed you are right that the reasons for requesting the change are different. Nice catch.

**Comment by kytrinyx** [comment]
Can we extract the main ideas from both of those issues here, close both and then figure out what the best action item(s) would be to actually address the underlying issues? Then we can create new, focused issues that are easier to tackle.

**Comment by ryanplusplus** [comment]
I haven't forgotten about this, but I want to quickly add that the inclusion of newbie and experienced badges/tags/whatever here is intended to gel with these two "paths" for onboarding users as discussed in https://github.com/exercism/discussions/issues/18.

**Comment by kytrinyx** [comment]
Having thought more about this I think it's _incredibly important_ that we do this, in particular because the kind of feedback you typically are looking for is different depending on your context. I watched a talk by Alex Harms last week and they mentioned that great feedback is information intended to help the person receiving it _achieve their goals_. For that to work you have to have some idea what their goals are.

**Comment by ryanplusplus** [comment]
I think the two tickets are different enough to stay separate.

The goal of this ticket is to enable giving and receiving better feedback. I think this can be achieved by communicating your goals and background to other users.

I think the goal of the other ticket is to increase reviewer participation by allowing a reviewer to communicate to Exercism that they are expert enough to review exercises without having done them.

While both involve communicating one's level of expertise, the targets are different and one can be accomplished without the other.

**Comment by kytrinyx** [comment]
Yeah, that's a good observation.

**Comment by kytrinyx** [comment]
Ref: https://github.com/exercism/discussions/issues/34

**Comment by stantoncbradley** [comment]
I think this would go a long way for #2803 as well

**Comment by kytrinyx** [comment]
This is being tracked as part of the nextercism redesign (see #113 and #154).
