### ISSUE TITLE
Track name consistency

### ISSUE THREAD

**Issue by kotp** [exercism/discussions#161]
It is the only one other than `dlang` that I have found with the 'lang' attached.  <sub>I think "Erlang"
 doesn't count.</sub> References made to "golang" but not as a repository name.

As these are the only two names that are appended with the 'lang' part (their websites likely did this to differentiate from other common things, such as the sites for "Go" and other languages that are a common part of common language).

Should we keep the "lang" off of the track repository names?

Carried over from exercism/dartlang#4

**Comment by kotp** [comment]
My vote is to keep the 'lang' off, especially since it is not a "language repository" it is a track dedicated to that language.

**Comment by kytrinyx** [comment]
@petertseng @SuperPaintman How do you feel about renaming `dlang` to `d` and `dartlang` to `dart`?

**Comment by SuperPaintman** [comment]
Positively, I'm all for it.

**Comment by petertseng** [comment]
I think it will not matter to me. The `lang` is not necessary for us since we don't need to differentiate against any other kind of `d` or `dart` or `elm` or `go`. Do whatever is best.

(Yes, if you forced me to pick, I would not have suffixed with `lang`)

**Comment by kytrinyx** [comment]
I'll go ahead and rename them to remove the `lang`. Thanks y'all!

**Comment by kytrinyx** [comment]
FYI @exercism/dlang @exercism/dartlang I'm renaming both the repositories and the teams to d and dart respectively.
