### ISSUE TITLE
Shall we create a team for "curriculum"?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#162]
We recently changed the team structure so that all the maintainer teams for the individual Exercism tracks are nested underneath the `track-maintainers` team.

```
track-maintainers/
├── bash
├── # 61 more teams
└── vimscript
```

This is handy, as it means that you automatically get the correct permissions to some of the shared repositories like discussions and docs. If we add you as a maintainer, and we don't have to explicitly add you to two teams. If you stop maintaining the track you're on and leave that team, you're no longer a member of the track-maintainers team—which makes sense.

On the other hand, it means that you _can't opt out of mentions to the track-maintainers team_ by just leaving it.

I don't think that the track-maintainers team should be used for mentions on a regular basis, there are too many people involved, and it's pretty rare that everyone cares or needs to know about a thing.

The most common use for a mention to this team has historically been for cross-cutting concerns and questions about exercises such as "is Hello World too complicated for a first exercise" or "should we have algorithm exercises".

We have also used this a fair amount in the exercism/problem-specifications repository.

The thing is, just because you maintain a track, doesn't mean that you should care about the broader concerns around the Exercism curriculum.

I think it would make sense to have a curriculum team that track maintainers can opt into if they're interested.

This team would likely be the natural maintainer team for the problem-specifications repository, and also the team to mention about cross-cutting exercise-related concerns.

We could manage this with some automation so that nobody has to manually manage the team.

Thoughts?

**Comment by ErikSchierboom** [comment]
Seems like a good idea. I like that this doesn't force the notifications upon those who are not interested in them.

**Comment by NobbZ** [comment]
I do fully support this as well!

**Comment by jonmcalder** [comment]
Seems like a good approach to me too!

**Comment by kytrinyx** [comment]
I've thought about this off and on for the past year, and I've decided I want put this on ice for a bit until have time to think properly about how we can better develop curriculum overall.
