### ISSUE TITLE
How to tell when the site was last built.

### ISSUE THREAD

**Issue by rpottsoh** [exercism/discussions#166]
Is there a way to see when the site was last built, is it displayed somewhere? If not, it might be a nice piece of information to display. 

My thinking here is, when I think the site is stale, maybe it really isn't... 

#### Clarification: 

Supposing the site has been built recently but there may be some problem with the build, like an update to a track didn't get included. If I could see that indeed the site hasn't been built in `X` days and my track update is `N` days old, if `X-N` is negative then I can assume that for some reason my changes did not get included in the build (assuming X < N) and @kytrinyx should be notified of the observation. On the other hand I can assume the site has not been built since my changes were made so I should just be patient, eventually a build will occur and all will be right.

Would knowing when the site was last built be useful information to people?

**Comment by iHiD** [comment]
Nice idea It would be nice to have this as a README badge, rather than something that shows on the website itself.

**Comment by petertseng** [comment]
I use:

* http://x.exercism.io/
* look at build_id
* find that commit in https://github.com/exercism/x-api
* look in Gemfile.lock as of that commit, find trackler version
* look at https://github.com/exercism/trackler as of that version

**Comment by rpottsoh** [comment]
Quite a scavenger hunt.  :smile:   Looks like about 20 hours right now.

Build ID: 5a829df
Gemfile.lock: 2.1.0.53
version.rb: bumnped to 2.1.0.53

So there is a build issue.  I have changes that were submitted to the Delphi track 9 days ago that do not appear on the site.  So there is merit to this idea....

In all fairness @kytrinyx is already aware of the build issue as I mentioned it to her in an email earlier today.

**Comment by kytrinyx** [comment]
There was definitely a build issue—trackler was bumping the version, but the submodules weren't getting updated.

I see two problems here:

1. When did the site last get deployed? (A badge would be awesome)
2. What is the SHA of the submodule that is deployed... this problem is going away. In nextercism we will be delivering exercises directly from git (potentially with a caching layer if performance becomes an issue), so we won't have to deploy in order for new exercises to show up on the site. If it's on master in the track, it will be live within a minute or so.

**Comment by Insti** [comment]
http://exercism.io/version will give you the short sha1 of the live exercism.io build.
(but you still need to do the scavenger hunt to determine track status.)

**Comment by kytrinyx** [comment]
The new site deploys changes to tracks (and to website-copy) automatically, which makes things a whole lot easier. I'm going to close this one 💙
