### ISSUE TITLE
We need GitHub teams for people who are familiar with Windows and Linux

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#169]
I've never worked on Windows, and it's been almost 10 years since I had a Linux machine. There are a lot of times where we could use help with opinions, suggestions, and verifying things on Windows/Linux.

I've made two new teams, @exercism/linux and @exercism/windows - these don't have any repositories associated with them, they're just interest groups.

If you are familiar with, use, or love either of these platforms please _please_ let me know so I can add you to the correct team, and we can ping you when we are stuck on something.

**Comment by iHiD** [comment]
Should we also have /mac as well to spread the burden there?

**Comment by kytrinyx** [comment]
We could, but from my observations a lot of contributors are on mac and we rarely (? never?) have questions about it.

**Comment by kytrinyx** [comment]
@jwood803 @blueelvis earlier I've asked you about Windows things. Are you up for this?

@kotp you seem to be a prime candidate for the Linux one. How do you feel about being pinged about this?

**Comment by Smarticles101** [comment]
I'm moderately familiar with Linux

**Comment by robphoenix** [comment]
I use Linux for personal and Windows for work, I'd be happy to be added to both teams. I'm no expert in either but am happy to at least attempt to resolve any queries.

**Comment by stkent** [comment]
cc @FridaTveit maybe?

**Comment by rpottsoh** [comment]
Windows here.  Zero mac, and very little Linux experience.

**Comment by Theodus** [comment]
I use multiple distributions of Linux on a daily basis and would be glad to help where I can.

**Comment by HarrisonMc555** [comment]
I really like using Linux. I'm no expert but I can probably help with a lot of beginner questions. Most of my work in exercism (in several language tracks) has been in Linux.

**Comment by yurrriq** [comment]
I use macOS daily, am quite familiar with a few flavors of Linux, and have little experience or interest in Windows.

**Comment by tleen** [comment]
Linux here.

**Comment by iHiD** [comment]
Would any of you lovely people like to help us with #170, which is very linked to this?

**Comment by mienaikage** [comment]
Happy to join Linux. Can probably help a bit with Windows too, but I typically only use that for gaming. (When I was last writing code on Windows I went out of my way to use bash in WSL...)

**Comment by FridaTveit** [comment]
Happy to join both Windows and Linux :)

**Comment by catb0t** [comment]
I use Windows (7 and 10) and desktop Linux every day, so I'm very familiar with both of them.

**Comment by NobbZ** [comment]
I'm primarily a linux guy, as I am using Funtoo and Ubuntu for personal use and also CentOS and Fedora at work.

But besides the VMs running on CentOS or Fedora at the office, the host box is running on a Windows 10.

So I'd applicable for both teams, would prefer to be only in linux though ;)

**Comment by kytrinyx** [comment]
Thanks everyone, I've added you all to the teams you've suggested. I'm going to leave this open so I can think of how to document this such that others know that they can join these if they want to help out.

**Comment by kotp** [comment]
Yes, for Linux for me.

**Comment by rahulagrawal97** [comment]
I use Windows and would be glad to help where I can.

**Comment by kabiir** [comment]
Happy to work on windows.

**Comment by marnen** [comment]
We should have a Mac team too, no? I'd be happy to be on it, and probably the Linux team too.

**Comment by marnen** [comment]
Ah, I missed @kytrinyx's earlier comment about a Mac team. I have more Mac experience in general than Linux, but I usually do Exercism on Linux instances on Cloud 9, so most of my Exercism experience is on Linux.

**Comment by m-a-ge** [comment]
As for me, I'm currently using Windows, but planning to move to Linux world soon (I'll install Ubuntu)

@marnen it's a good idea to use Cloud 9 👍

**Comment by Stargator** [comment]
Windows experience, no access right now.

Currently using Linux - Ubuntu

**Comment by katrinleinweber** [comment]
What about the `Request to join` button(s) on the teams' pages: @exercism/linux and @exercism/windows? OK to use, or is a mini-application here favored?

**Comment by kytrinyx** [comment]
_Request to join_ works for people who are already part of the organization, which might be good enough.

**Comment by opheliagame** [comment]
Linux, for me!

**Comment by coriolinus** [comment]
My daily driver machine is Windows, but 100% of my development happens within WSL, which is fundamentally linux. Feel free to add me.

**Comment by kytrinyx** [comment]
Great, thanks @opheliagame and @coriolinus -- done!

**Comment by kytrinyx** [comment]
For anyone who wants to be added to these teams in the future, please open an issue in http://github.com/exercism/exercism.io/issues and we'll get you sorted!
