### ISSUE TITLE
Difficult to find the terminal commands I need to use when I've been away for a while...

### ISSUE THREAD

**Issue by siakaramalegos** [exercism/discussions#17]
I asked the RailsConf scholars group if they had any feedback about the site since it has been a while since I signed up and wanted to get a fresh perspective. One of the scholars said this:

> I often forget the terminal commands when I've been away for awhile -- how to submit and how to pull down the next exercise for a track I'm working on. They're not the easiest to find on the site.

I haven't necessarily felt this way, but wanted to put it out there for discussion in case others have. It looks like it's easy to find on the experiences coder instructions but probably less so in the others, so maybe the solution is to make them share the exact same instructions (like via partial).

**Comment by kotp** [comment]
http://exercism.io/cli has the title for this, on the website (and it is in the footer so available from every page) but does not have the "CLI" help you may expect there.  A quick mention of using `exercism --help` may definitely be useful there.

**Comment by siakaramalegos** [comment]
You can close this and my other contributions. I don't think I'm interested in being a contributor anymore. Thanks.

**Comment by kotp** [comment]
I hope you will stick around.  You are bringing up good ideas.  I am sure you are full of others, too!

**Comment by kytrinyx** [comment]
@siakaramalegos Thank you so much for asking the RailsConf scholars—that's great. I totally agree about making it more obvious how to find the overview of the CLI commands. There's still so much about the user interface / user interactions that is non-intuitive, and getting the fresh perspective is really helpful.

**Comment by jtigger** [comment]
We'd love to hear more from @siakaramalegos.  Will re-open this issue if we do.

**Comment by siakaramalegos** [comment]
I didn't necessarily agree with the suggestion anyway - I was more passing it on. I think it's fine to keep this issue closed.
