### ISSUE TITLE
How do people use Exercism Teams?

### ISSUE THREAD

**Issue by iHiD** [exercism/discussions#172]
As part of the reboot, we are currently considering Teams. We want to gain a better understanding about how people are currently using teams and what their use-cases are.

If you use teams, could you please post a comment with the reason you use teams (e.g. Bootcamps, work-team, etc) and the way that you use them (e.g. you all do an exercise and comment on each others' work).

Thank you!

**Comment by IanWhitney** [comment]
We had a group of programmers at work that were going through the exercises. Using a Team gave us two nice features:

- An easy list to see who else in the group had done an exercise
- The ability for a user to see solutions done in other languages

**Comment by robphoenix** [comment]
I just started a team for Go track maintainers: https://github.com/exercism/go/issues/721

**Comment by tmikoss** [comment]
We have recently started using exercism in my company to check out different languages - choose a track, work on it for some time, then discuss the pros and cons of that language.

Exercism.io teams fit in as a way to keep eye on my coworkers progress, and comparing solutions.

**Comment by iHiD** [comment]
@IanWhitney @tmikoss  Thank you both for replying.

So would it be fair to say that you're fundamentally looking for a way to easily track the progress of a group of people? If you could star people (aka Github) would that meet your requirements, without having to set up a formal team?

Do you actively comment on each others solutions at the moment?

**Comment by DoggettCK** [comment]
We're using it at CoverMyMeds to help get new hires up to speed with Elixir (and Ruby, for our legacy stuff), and I like the team stuff. I like it as a filter so I can see only my teammates at a glance if I want, and help guide them through learning the language, though I do participate in the wider community as well.

**Comment by tmikoss** [comment]
@iHiD starring would not be the same - a team can be set up by one for all, while starring has to be done by every person on their own.

And yes, we comment on each others solutions.

**Comment by ErikSchierboom** [comment]
I used teams just as an easy way to keep track of the progress of some friends.

**Comment by ceddlyburge** [comment]
Hi there. We are currently using exercism as part of embedding a culture of routinely writing quality code. I think it will also be useful for new recruits, next time we have one.

**Comment by kytrinyx** [comment]
Thanks everyone for responding to this, it's been really helpful as we rethink the teams for the new Exercism site.

I'm going to go ahead and close this. In the next few weeks we'll be sharing designs and thoughts about the new teams stuff—please keep an eye on the [v2-feedback](https://github.com/exercism/v2-feedback/blob/master/README.md) repo if you're interested in helping explore anything related to the new site.
