### ISSUE TITLE
Track config and exercise ordering

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#177]
We've been working on improving the tooling for tracks, and in particular Configlet has gotten a lot of love in the last few weeks.

@robphoenix is in the process of adding a `fmt` (formatting) command that we can use for all the track configurations, which will make it easier to script certain changes across the board without running into silly conflicts and huge irrelevant formatting diffs in the pull requests.

The thing with this is that Go orders the fields in the JSON alphabetically. This is great for reproducibility, but it potentially kind of sucks for looking at a config and understanding what order the exercises are actually going to be delivered in.

As a counter-balance to this, though, we're also talking about improving Configlet by adding commands that will read the tooling in and show a tree representation (core exercises -> associated non-core exercises) and a list representation (ordered by difficulty).

My gut feeling right now is to go with the formatter even though it will alphabetize the config, and rely on the tooling for visualizing/understanding the exercise progression.

@exercism/track-maintainers this affects you all. Thoughts?

**Comment by robphoenix** [comment]
> it potentially kind of sucks for looking at a config and understanding what order the exercises are actually going to be delivered in

The formatter won't alphabetise the exercises, as this is a list rather than a `key:value` map/dict type, which do get alphabetised. So whatever order the exercises are in in the `config.json` file will stay the same. I've added a function that alphabetises the topics within each exercise though.

The Go track [config.json](https://github.com/exercism/go/blob/master/config.json) formatted, as an example:

```json
{
  "active": true,
  "exercises": [
    {
      "core": false,
      "difficulty": 1,
      "slug": "hello-world",
      "topics": [
        "Strings"
      ],
      "unlocked_by": null,
      "uuid": "19957346-dedf-441e-85ea-656cac0d96d8"
    },
    {
      "core": false,
      "difficulty": 1,
      "slug": "leap",
      "topics": [
        "Booleans",
        "Control-flow (conditionals)",
        "Integers",
        "Logic"
      ],
      "unlocked_by": null,
      "uuid": "fee57b09-2b67-4483-a2e5-3dfec0568b15"
    },
    {
      "core": false,
      "difficulty": 3,
      "slug": "clock",
      "topics": [
        "Equality",
        "Mathematics",
        "Text formatting",
        "Time"
      ],
      "unlocked_by": null,
      "uuid": "7d2de21e-bf67-495e-8d90-05e1a35d5b99"
    },
[TRUNCATED FOR BREVITY]
    {
      "core": false,
      "difficulty": 5,
      "slug": "change",
      "topics": [
        "Algorithms",
        "Arrays",
        "Control-flow (loops)",
        "Mathematics",
        "Searching"
      ],
      "unlocked_by": null,
      "uuid": "94a21509-ebd5-4a66-bb0e-0341e57e3c73"
    },
    {
      "core": false,
      "difficulty": 5,
      "slug": "bowling",
      "topics": [
        "Algorithms",
        "Arrays",
        "Control-flow (conditionals)"
      ],
      "unlocked_by": null,
      "uuid": "8d5aaf47-7503-4797-85ed-d35a8755cfd4"
    },
    {
      "deprecated": true,
      "slug": "binary",
      "uuid": "bf2dcbc4-266f-4cad-9cd7-76d446360a5d"
    },
    {
      "deprecated": true,
      "slug": "counter",
      "uuid": "9a06556b-a661-4329-97a1-b5d0f0c7590c"
    },
    {
      "deprecated": true,
      "slug": "hexadecimal",
      "uuid": "0c9cef3d-57f6-479a-aca4-25f310426d6a"
    },
    {
      "deprecated": true,
      "slug": "octal",
      "uuid": "4840c889-ebe5-4082-98c0-b9ed8618f6eb"
    },
    {
      "deprecated": true,
      "slug": "trinary",
      "uuid": "52af9f03-8b6b-4d75-a363-124f3269dccd"
    }
  ],
  "foregone": [
    "space-age",
    "linked-list",
    "simple-linked-list"
  ],
  "ignore_pattern": "example(?!.*test)",
  "language": "Go"
}
```

**Comment by kytrinyx** [comment]
> The formatter won't alphabetise the exercises, as this is a list rather than a key:value map/dict type, which do get alphabetised.

Oh, in that case I think that we're definitely fine.

**Comment by iHiD** [comment]
>  This is great for reproducibility, but it potentially kind of sucks for looking at a config and understanding what order the exercises are actually going to be delivered in.

Looks like you have this sorted, but as a reminder and for future reference, exercise order is now meaningful, as it dictates the order that core exercises appear on the website. So alphabetising the exercises is not an option.

**Comment by kytrinyx** [comment]
Yepp—I somehow forgot that it's a list, not a hash. We're all good.

**Comment by ErikSchierboom** [comment]
Things are all good then :)

**Comment by SaschaMann** [comment]
The current config.json layout does not present the exercise ordering/progression well. Without external tools it's really annoying to find out the order. When I updated the order of the Julia track, I found myself constantly uploading the config.json to the visualisation tool. This could be solved easily by choosing a config-format that represents the order better.

Instead of having `unlocked_by`-strings, perhaps we should consider a less flat layout of config.json that shows the order on first glance.

Having the unlocked exercises as part of the core exercise would make it more readable, e.g.:

```json
  "exercises": [
    {
      "uuid": "a668410d-41aa-4710-a68f-54521da6486d",
      "slug": "hello-world",
      "core": true,
      "difficulty": 1,
      "topics": [
        "strings"
      ],
      "unlocks": {
        "uuid": "878e9897-c4b6-40ff-9034-8f2aedf07a91",
        "slug": "hamming",
        "core": false,
        "unlocks": null,
        "difficulty": 1,
        "topics": [
          "generators",
          "strings",
          "exceptions"
        ]
      }
    },
    {
      "uuid": "c64e03cc-1952-4b2d-9a53-25c43187a4e6",
      "slug": "gigasecond",
      "core": false,
      "unlocks": null,
      "difficulty": 1,
      "topics": [
        "dates"
      ]
    }
  ]
```

Alternatively, a file that contains _just_ the order of the exercises in a more readable and convenient format than JSON could be used.

**Comment by tleen** [comment]
@SaschaMann it may be a matter of having the existing tooling catch up to the new complexity. Prepping for Nextercism is probably the most intense reworking of the config.json file any of us have had to deal with and has certainly demonstrated the need for visualization help. We are in the middle of the same process the Go track and feel your pain!

There are a [few](https://github.com/exercism/configlet/issues/33) [issues](https://github.com/exercism/configlet/issues/41) [already](https://github.com/exercism/discussions/issues/178) open about adding those functionalities which may be just the thing. [configlet](https://github.com/exercism/configlet) seems to be the place where this functionality would live.

**Comment by SaschaMann** [comment]
@tleen I know there's work on proper tooling to help with it. What I was proposing was a change of the config in a way so that you don't need any tooling because the order is obvious from the structure of the file. The information in the file would be the same, just in a more human-friendly structure.

**Comment by iHiD** [comment]
@SaschaMann @tleen I feel a bit confused about this whole issue, because in my head this is really simple, but everyone else is seeing it as complex. 

The `core` exercises are ordered by the order that they appear in the file. So if we put core exercises at the top, then that's really easy to visualise. Then for the other exercises there is no order - they're just unlocked by things. People can attack those in whatever order they choose.

I feel like I'm not communicating this well, so could you please explain where the complexity is arising for you both, and I can try and explain more (or realise I'm missing something!). Thank you 💙

**Comment by tleen** [comment]
@iHiD I believe @SaschaMann is focusing more on the tree structure being represented by a flat array with unlocked_by pointing to the parent node, rather than having the unlocked exercises nested under the parent?

**Comment by iHiD** [comment]
OK - so not ordering, but the unlocking. That makes much more sense. Thank you for explaining.

**Comment by kytrinyx** [comment]
Ah, yes. I see your point. Thank you!

It's a pretty big change, and right now we'd need to make changes to both the old and the new site, and in the configlet lint command. We'd need to support both the current structure and the new structure in order to get the tracks migrated, and we'd need to support this in all three places.

That doesn't mean it's not worth it, but I'd want to think about the trade-offs first.

**Comment by SaschaMann** [comment]
@tleen Yes, exactly. The config.json right now is completely flat, with the `unlocked_by` being the only reference to the tree progression. I was suggesting a different structure of the config.json, so that you can see the tree layout in the file itself easily.

**Comment by ryanplusplus** [comment]
What if the the config we're split into two files: one that documents each track (topics, uuid, etc.) and one that documents the track structure that made the progression obvious? This definitely would have helped me when setting up the progression in Lua as I needed to create a tree in another document and then transfer that into config.json.

**Comment by tleen** [comment]
I'm loathe to see direct configuration information split up into multiple files. The files will eventually get out of sync. I would personally lean towards visualization tooling in this case.

**Comment by kytrinyx** [comment]
I would find multiple files harder to reason about.

I did find it pretty hard to actually go through the core/unlocked_by process for the Bash track. I found it very hard to keep it all in my head and reason about each thing along the way. So I definitely hear where you're coming from @SaschaMann.

I think tooling would fix that for me (and I don't mind command-line tooling, but I edit within my terminal, so I might be the odd duck out here. I do tend to mind if I have to switch windows and click stuff).

@ErikSchierboom @rpottsoh @rchavarria @ozan you have all gone through the process of setting core exercises and deciding what gets unlocked by what. Would you weigh in here about how you felt about the process?


These are the trade-offs I can think of:

**Mental overhead**: I don't know if this is going to be highly personal or not. My gut feeling is always that everyone is exactly like me, and my gut feeling is inevitably wrong :)

**Diffs**: they're bigger in the nested structure, smaller in the flat one. _On this one I really don't care either way, because the diff is going to be clean, even though it's bigger._

**Deprecation work**: we need to change several codebases to handle both the old format and the new format for the duration of the change-over process. _This is work, but it's also worth it if the resulting change is better. I'm fine with that._

**Jerking people around**: You've already done the work one way, we'd be asking you to do it another. _On this one I can script the change, so I don't actually think that maintainers would be affected much._

**Comment by ryanplusplus** [comment]
@tleen Synchronization can be minimized by making sure both files share only the list of exercises. Configlet could check fairly easily and wouldn't require contributors to set up client side tooling (if that's what's being suggested).

**Comment by ryanplusplus** [comment]
@kytrinx I understand about jerking people around, but I'm more concerned with the current (painful for me) configuration process. I felt that it made it difficult for me to create a sane structure and if I found it didn't work well I'd hesitate to go through any rework to improve it.

**Comment by kytrinyx** [comment]
> I understand about jerking people around, but I'm more concerned with the current (painful for me) configuration process.

Yeah, I totally agree. I also found it painful. I'd like to hear from the others who have also gone through this process, too before making a call on this one.

**Comment by ErikSchierboom** [comment]
The configuration process was actually quite painful, especially since the tracks I worked on had so many exercises. Tooling would definitely have helped, although having the structure encoded in the JSON file would also have helped. I'm fine with either option, with a slight preference for having tooling on a flat JSON file. The reason I like the tooling option, is because the tooling can also do more than the hierarchical encoding can. It could suggest exercises, or even try to automatically determine which non-core exercises get unlocked by which core exercises (by using their topics and difficulty). This is something the JSON hierarchy by itself cannot do, it would still need tooling for that. So if we still want to have tooling, why not use it for the whole process.

**Comment by dsudia** [comment]
I think, having just gone through the config process, that it would be nice to be able to see (as easily as possible) in the config file how many core exercises there are, and what is unlocked by them. A visualization tool would be fine, but that's one more tool to add to the process, so I would lean toward a tree structure. It would just be nice to see "oh, this branch has 2 unlocked exercises and that one has 9, I need to find more transformation exercises." That's the end feature that would matter to me, however it gets implemented.

**Comment by rpottsoh** [comment]
@dsudia, @jonmcalder came up with nice little [app](https://jonmcalder.shinyapps.io/exercism-config-viz/) that allows you to visualize which exercises are your core exercises and which are unlocked by the cores.  A very good visualizer for the config.json file.  Jon shared this with us in #175.

**Comment by dsudia** [comment]
thanks @rpottsoh!

**Comment by kytrinyx** [comment]
I'm leaning for both a tree structure in the config and good tooling for visualization, so that we can do the basics without as much pain and also can have fancier help when we need it.

This is going to mean some extra work to not break the existing site _and_ make sure the importer in v2 works, etc, etc, so I'm holding off on making the final decision until I can spend some time actually looking at the effort involved.

**Comment by tleen** [comment]
Damn buttons.

**Comment by stkent** [comment]
`configlet` now supports structure visualization! 👏

**Comment by kytrinyx** [comment]
It seems like this has been solved with the visualization tools. I'm happy to revisit the question in the future. If so, go ahead and open an issue in http://github.com/exercism/exercism.io/issues to summarize the pains! Thanks everyone.
