### ISSUE TITLE
Track config - add maintainer's description

### ISSUE THREAD

**Issue by tleen** [exercism/discussions#178]
As we are working with config.json to order the exercises I believe it may be worth considering allowing for each exercise is some sort of optional *maintainer's* description field.  

When # number of exercises in a track get large enough it is hard to remember which exercise is which via the name alone. Topics help, but something like a "description" field would be very helpful, just in scanning the config and also in the visualization tools. Sort of like commenting the exercise. This would not be the same as the exercise description in the problem-specifications, rather a internally used maintainer-focused description about what the exercise is teaching particularly in the language of the track. In Go for example:

```json
{
      "uuid": "73da448c-33b7-4565-ab48-1de5020d65ab",
      "slug": "etl",
      "core": false,
      "unlocked_by": null,
      "difficulty": 1,
      "purpose": "Explores the Map data type by requiring both an input and output map inverting the keys and values.",
      "topics": [
        "Control-flow (loops)",
        "Maps",
        "Transforming"
      ]
}
```
I could see this being useful in the visualization tools as sort of a tooltip style descriptor of the exercises. It may be easier than having to go back and forth with the problems to figure which one they are and how they apply to the track? 

The downside is that it may end up being redundant information.

**Comment by kytrinyx** [comment]
I do like the idea of having a purpose field. I think that with the config.json, it's probably fine to have additional fields that other tracks don't have, as long as the standard ones are there. So... if (say) the Go track wanted to experiment with this for a while and report back, I think that would be a useful experiment.

I would hesitate to mandate this across the board, but I think it would be really useful to see if it helps and in what way.

**Comment by robphoenix** [comment]
@tleen I'm all for experimenting with this in the Go track :+1:

**Comment by tleen** [comment]
Yep I think this may be helpful for us in organizing stuff. I'll issue it on the track so everyone knows. If it works out we can re-open this.
