### ISSUE TITLE
Programming languages - official/unofficial logos (time sensitive: do you have 5 minutes this weekend?)

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#179]
Want to help with a quick project?

We're hoping to get a definitive answer about the logos for each language represented on Exercism.

TL;DR: If you know anything about the logos, or have time to contribute a few minutes worth of research in the next day or two, this would be an enormous help.

The project is listed here: https://github.com/exercism/meta/issues/24, and contains a separate issue for each individual language, to make it easy to track what's done and not.

**Comment by m-a-ge** [comment]
I'll be glad to help with this one, already added my findings for some  of the languages

**Comment by kytrinyx** [comment]
Quick note from Andrew Nesbitt:

> We've found quite a few for librariesio: https://libraries.io/languages all available as a rails asset gem: https://github.com/librariesio/pictogram

@m-a-ge that should help for a lot of these!

**Comment by m-a-ge** [comment]
`librariesio/pictogram` is awesome and I believe the author might have vectors as well

**Comment by m-a-ge** [comment]
Ok, I've made some progress and I'm going to finish with the rest languages tomorrow. 
It took more time than I expected :unamused:

**Comment by kytrinyx** [comment]
> I've made some progress

@m-a-ge understatement of the year. This is such an amazingly huge help! This has freed us up to make progress on the prototype all weekend instead of doing this research, and we absolutely needed that time. Thank you so much for taking the time and energy to dive into it!

**Comment by m-a-ge** [comment]
I've finally finished :checkered_flag: with [exercism/meta#24](https://github.com/exercism/meta/issues/24)

It was a bit tedious (sometimes it was hard to find information for some languages because even official websites\repos didn't provided it), but I hope it helped on the road to a new version of exercism.io.

I'll be glad to help with something else

**Comment by kytrinyx** [comment]
@m-a-ge You are a total star. THANK you!

✨ ⭐️ ✨ ⭐️⭐️⭐️ ✨ ⭐️ ✨
