### ISSUE TITLE
The new prototype is ready for you

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#183]
We're launching the "nextercism" site to contributors, maintainers, and Exercism power users.

For a full overview of what we're launching, how you can help, and where to provide feedback please take a look at [exercism/v2-feedback](https://github.com/exercism/v2-feedback/blob/master/README.md).

**Comment by stkent** [comment]
The gopher eyes 😍

**Comment by jonmcalder** [comment]
This just made Friday even more awesome! Well done @kytrinyx and the Thalamus team! This is looking amazing!

**Comment by BigChief45** [comment]
Great stuff! But I tried opening it on my phone, it seems the design is not responsive?

**Comment by kytrinyx** [comment]
@BigChief45 nope, not yet. We've explained our reasoning here: https://github.com/exercism/v2-feedback/issues/34

**Comment by Smarticles101** [comment]
It looks awesome! 😀
