### ISSUE TITLE
Adding exercise from other sources

### ISSUE THREAD

**Issue by chinmayshah99** [exercism/discussions#188]
nifty.stanford.edu has some amazing exercise. These exercises directly or can be bit modified and implemented into exercism

**Comment by kytrinyx** [comment]
@chinmayshah99 do you know what the license is on those?

**Comment by chinmayshah99** [comment]
I tried contacting professor but he hasn't replied yet. But here's the extract from the official webpage: 

> At the SIGCSE conference, I would often see a neat assignment idea go by as a peripheral part of a talk. Knowing that great assignments are such a tricky and time-consuming part of putting together a course, it was natural to create a forum focused on the very practical problem of finding the best assignments within the CSE community and making their materials freely available.

**Comment by kytrinyx** [comment]
Thank you. "freely available" can mean so many things!

**Comment by NobbZ** [comment]
Until there has been an answer by the creator of the exercises, I'd be carefull and consider “freely available” as “everyone can pick the exercises and solve then on their own free of charge”, not as “everyone can redistribute them”.

**Comment by kytrinyx** [comment]
Yes, if there is no license, then by default the content is under copyright.

**Comment by chinmayshah99** [comment]
If someone else is able to contact professor and verify that, it'll be great. It really has some good content.

**Comment by chinmayshah99** [comment]
This what the professor replied: 

> the copyright is still held but the authors, but they are distributed with the intention that they are used by others. A more formal copyright / CC type license is possible.

**Comment by kytrinyx** [comment]
Thank you so much for following up, @chinmayshah99!

In conclusion, we would not be able to include these exercises under the current circumstances, since they are under copyright. I think that if it were under a free CC type license, we could potentially use it, but it would have to be compatible with the MIT license that our exercises are licensed under.

**Comment by kytrinyx** [comment]
If they license the exercises under CC-BY-4.0, then we could likely use the exercises provided that we explicitly attributed with the following text:

> includes text from [foo] by [foo author name] under CC-BY-4.0), preferably with links.

See https://creativecommons.org/licenses/by/4.0/legalcode#s3a for details
