### ISSUE TITLE
Hacktoberfest is coming up - how should we prepare/participate this year?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#190]
I'm up for any suggestions, my only concern is that it should be mostly track-related since we're hoping to get v2 to a place where it can launch publicly in the next month or so.

Also, you're going to need to self-organize, as I'm hitting a threshold on mental bandwidth. If you need me for anything (create labels, add things to the newsletter, add people to teams, etc, let me know, I'm still great at following directions :-) even with lack of bandwidth).

**Comment by Stargator** [comment]
What's the best way to reach users and let them know our top "please, for the sake of our souls, help us" items are?

**Comment by jpreese** [comment]
I'm not sure theres more we need to do other than throw together a Hacktoberfest page on the exercism site, blog post, or <insert social media medium here> listing how they can contribute. 

Potentially focusing on tracks that might not get as much love. Even better, getting a track in the planning stages out the door to a full fledged available track.

**Comment by kotp** [comment]
Nice timing on this, I was just coming to post this very same issue.

**Comment by kotp** [comment]
The Ruby track has a Hacktoberfest label for this purpose last year... #76 should have some hints to help promote this for this year as well.

**Comment by Stargator** [comment]
@kotp Good idea. A Hacktoberfest label would be good. Which reminds me some repos have labels like "for beginners" and others to note help is wanted and what kind of experience is needed.

**Comment by rootulp** [comment]
The [Hacktoberfest](https://hacktoberfest.digitalocean.com/) site recommends:
> Apply the label ”Hacktoberfest” to issues in your GitHub project that are ready for new contributors to work on.

I'm wondering if that might help get track repos featured under the Hacktoberfest projects section.

**Comment by jpreese** [comment]
The C# repo added the hacktoberfest label to our test generator issues a while back. Looking at the projects page, we definitely have some presence there now.

**Comment by kytrinyx** [comment]
This GitHub App looks pretty great: https://probot.github.io/apps/first-timers/

Could help add more first-timer issues easily.

**Comment by tleen** [comment]
FYI, Digital Ocean is [offering a free t-shirt](https://hacktoberfest.digitalocean.com) for Hacktoberfest if you make 4 PRs.

**Comment by bdw429s** [comment]
I've made a screencast that walks anyone through contributing more exercises to the CFML track
https://www.youtube.com/watch?v=ntjfJWAhVfY

But I don't have issues created for missing exercises, that didn't seem right.  Maybe I should create a handful of issues just for the next exercises in line that are most likely to be created??

**Comment by wwest4** [comment]
I gather that exercism/scheme might be lightly staffed, so posting this here. I made an attempt at implementing a missing exercise: https://github.com/exercism/scheme/pull/67

**Comment by tleen** [comment]
Digital Ocean mentioned Exercism in a e-mail newsletter about Hacktoberfest! The link went to the [I would like to help section](https://github.com/exercism/docs/blob/master/finding-your-way.md#i-would-like-to-help) in the "finding your way" doc.

![screenshot from 2017-10-13 15-20-43](https://user-images.githubusercontent.com/1599679/31562615-1c4c149c-b02a-11e7-8f6e-85be04884769.png)

**Comment by m-a-ge** [comment]
Python track is quite popular (from official stats https://hacktoberfest.digitalocean.com/stats):
![image](https://user-images.githubusercontent.com/6649477/31565433-7f077b2c-b06f-11e7-88f2-9b86708e6e37.png)

**Comment by kytrinyx** [comment]
That's so cool, I had no idea they'd stick it in the newsletter!

**Comment by Insti** [comment]
Hacktoberfest is over, should we close this issue?
Does anyone have any success stories to share?

**Comment by wolf99** [comment]
The C track got launched! 🙌 
(technically it was launched after October, but the work was done leading up to that in October)

**Comment by m-a-ge** [comment]
@Insti I've already removed this labels to avoid confusion.
As for success stories, during Hacktoberfest 2017 two new maintainers joined Python track and they are doing great work. Moreover, I've seen a lot of first-time contributors, which is a sign of good exposure of our project. I think it's the most important thing about the event

**Comment by tleen** [comment]
The Go track had a good number of first time contributors. Hacktoberfest works!

**Comment by ferhatelmas** [comment]
@tleen I wish they will also stick around later.

**Comment by cmccandless** [comment]
>A search using a date range will give you an indication of how many issues/PRs were created in a repository during October: created:2017-10-01..2017-10-31

The Python track had over 300 PRs for the month of October!

**Comment by Stargator** [comment]
The dart track completed a milestone to meet requirements to get launched. We also had two new maintainers join up before Hacktoberfest

**Comment by kytrinyx** [comment]
Forgot to close this after Hacktoberfest ended 😁
