### ISSUE TITLE
Maintainers: Call for a few good-first-patch issues

### ISSUE THREAD

**Issue by nywilken** [exercism/discussions#196]
Hello Exercism maintainers, I'm an active contributor to the Exercism configlet, and just recently cli, project. I try to contribute as much as possible and would like to try and help out a few other projects. I'm part of the Open Source Working Group, within my organization, and will be hosting an internal OSS hack night where members can learn about and contribute to OSS projects we use and come to love. 

In the upcoming event, set for 9/28, I will be championing Exercism where I will be working with engineers in reviewing and possibly opening up some PRs against open issues labeled as good-first-patch. 

At this time, I would like to ask if maintainers could spot-check open issues and ensure that they are labeled appropriately. Before the event, I will compile a list of issues to present (ranging from feedback, documentation changes, to track implementations). If there are issues that are being worked on, or if there are any issues I should not look into please call them out here (especially any old no longer relevant issues) and I will gladly oblige. 

Thanks

**Comment by Insti** [comment]
What languages are you interested in working with?

**Comment by bdw429s** [comment]
I just launched a ColdFusion track that could use some new exercises added to it! :)

**Comment by nywilken** [comment]
> What languages are you interested in working with?

I purposely did not include any languages to not limit the scope of the issues, as the idea of the hack night is to encourage contributions on various levels (e.g documentation edits, issue triage, to possible track implementations) and to grow awareness in supporting OSS communities. 

With that said, the engineering teams have exposure to a number of technologies, but our day-to-day is JS (name your flavor), Ruby, Python, Swift, and Objective-C. 

Feel free to call out any particular language tracks you might have in mind. I make no promise that we can contribute if it is something the team is not familiar with, but I will definitely survey the issues to see if we can help in any way. All that I ask is that the contributing, and setup. docs be up to date. If that's what needs help then we will take a stab at that as well. 


Thanks for any feedback and support.

**Comment by nywilken** [comment]
@bdw429s thanks for calling out the ColdFusion track. I'll float the language around the team to see if anyone has experience with the language. If so I will ping you back with any plans for the exercises we plan to attack. 

On a side note, great work on starting the new track.

**Comment by tleen** [comment]
This may align closely with Hacktoberfest (#190)?

**Comment by NobbZ** [comment]
I have some [`good-first-patches` in the erlang track](https://github.com/exercism/erlang/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+patch%22), but to be honest, I am thinking to remove them, as for me it has a semantic similar to “first timers only” and I am really not sure why I've choosen one over the other…

The only reason why I'm using this label at all is, that it also implies some beginner level difficulty.

**Comment by bdw429s** [comment]
>  I'll float the language around the team to see if anyone has experience with the language.

@nywilken If their experience isn't recent, they probably wouldn't recognize it :)  CFML reads very similar to JavaScript these days in its script form with loose typing, closures and such, just with classical OO constructs.  Let me know if I can help you.  Here's an example, probably foreign to anyone who did the old, tag-based ColdFusion stuff back in the late 90s, but familiar to anyone just looking at it as a modern scripting language.
https://github.com/bdw429s/coldfusion/blob/master/exercises/largest-series-product/Solution.cfc

**Comment by Stargator** [comment]
@nywilken The Dart track is still maturing.
* We have [one new exercise in [](PR](https://github.com/exercism/dart/pull/38)) (need 2 more to be submitted of any difficulty)
* [One issue labeled good first patch](https://github.com/exercism/dart/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+patch%22)
* And some issues[ labeled discussion](https://github.com/exercism/dart/issues?q=is%3Aopen+is%3Aissue+label%3Adiscussion) for feedback on some topics and goals

Additionally, the documentation was drafted last month, so any feedback or issues found within them would be greatly appreciated.

[About Page](http://exercism.io/languages/dart/about)
[Installation](http://exercism.io/languages/dart/installation)
[Running Tests](http://exercism.io/languages/dart/tests)
[Learning Dart](http://exercism.io/languages/dart/learning)
[Useful Resources](http://exercism.io/languages/dart/resources)

[README](https://github.com/exercism/dart/blob/master/README.md)

**Comment by nywilken** [comment]
Thanks for the comments and support. 

@NobbZ @bdw429s @Stargator the provided information is super helpful.

@tleen I'll checkout out the issues labeled Hacktoberfest.

**Comment by Smarticles101** [comment]
The [Java](https://github.com/exercism/java) track is doing well, but we have a bunch of good first patch issues that just opened up for adding topics, and then we have some other, older ones too!

**Comment by nywilken** [comment]
> The Java track is doing well, but we have a bunch of good first patch issues that just opened up for adding topics

@Smarticles101 thank you I saw these yesterday and plan to have the group take on a few. I'll let you know if I have any questions. Thanks a million.

**Comment by nywilken** [comment]
@Stargator thanks again for calling out the docs. I'll work with the group to step through them and provide feedback/PR where possible.

**Comment by bdw429s** [comment]
@nywilken Just a quick update, if anyone wants to help contribute exercises for the ColdFusion (CFML) track, here's a new screencast I just pubished that will show them the entire process :smiley: 
https://www.youtube.com/watch?v=ntjfJWAhVfY

**Comment by nywilken** [comment]
Thanks again to everyone for the support and help - the night went really well. While there were not a lot of contributions made on Thursday (only two),  I managed to grow awareness of Exercism and showed a number of engineers how to contribute to tracks. Participation was high, so I hope to see contributions trick in for Hacktoberfest. 

Nothing but ❤️ for Exercism community.
