### ISSUE TITLE
Student Body Growth Rate?  

### ISSUE THREAD

**Issue by rpottsoh** [exercism/discussions#197]
I have been tracking the number of downloads that have occurred for the Windows Installer for the CLI.  The latest release was published on August 20th and as of right now it has been downloaded 1155 times.  See https://api.github.com/repos/exercism/windows-installer/releases/latest look for tag "download_count" in the "assets" section.

This installer only installs either the 64 bit or 32 bit version of the Windows CLI.  So I have been observing this similar information for the CLI, see https://api.github.com/repos/exercism/cli/releases/latest.  In the "assets" section there is a "download_count" tag for each of the different flavors of the CLI.  The 64 bit Windows version sees the most number of downloads followed by the 64 bit linux version.  The other versions see very little download activity compared to the other two.

I am wondering if Exercism is seeing student body growth rates that in any way reflect/mirror these download counts?  The latest release version of the CLI has been available since the beginning of July and the Windows Installer a little more than a month.

This is just an observation that caused me to wonder.  I realize some of the CLI downloads are the result of `exercism upgrade` calls so it is not really possible to distinguish between first time downloads and upgrade downloads.

**Comment by iHiD** [comment]
This is new users and all sessions on Windows from July 2015 until last month:

<img width="949" alt="screen shot 2017-09-27 at 16 08 56" src="https://user-images.githubusercontent.com/286476/30921347-35eb02ac-a39e-11e7-805c-0cac2c5d5f20.png">

**Comment by rpottsoh** [comment]
Thanks @iHiD.  This is interesting, quite an uptick in activity at the beginning of the year, wonder if that is an annual thing?  Anyway I can access this?  Or can we focus this in starting in July '17 till the present on a weekly rate instead of monthly?  Who knows, a daily rate might be interesting to look at too.

**Comment by iHiD** [comment]
I can't see anything notable from July. Graphs attached.

<img width="940" alt="screen shot 2017-09-27 at 16 46 29" src="https://user-images.githubusercontent.com/286476/30923378-9d36b9d8-a3a3-11e7-8bc8-c937ac88b0de.png">
<img width="952" alt="screen shot 2017-09-27 at 16 47 34" src="https://user-images.githubusercontent.com/286476/30923380-9d41033e-a3a3-11e7-97cd-96341078fc4c.png">

**Comment by rpottsoh** [comment]
I agree.  @iHiD thanks for pulling the information.  Let's see if anyone else has any thoughts on the issue.  I'll give it a couple of days and then close it.

**Comment by Smarticles101** [comment]
These are really interesting and awesome stats

**Comment by iHiD** [comment]
Yep.
