### ISSUE TITLE
Recommended Solution

### ISSUE THREAD

**Issue by samir-majhi** [exercism/discussions#198]
Many times I feel that my solution could have been written better. But to find out how, I have to wade through other people's submissions. Those tend to have a lot of variety (which is useful), but it's hard to find the best solution among them.

If one of the submission could have been marked as the recommended solution by the track owner, or even the track owner submitting the recommended solution themselves, it would save me a lot of time and anguish. Then I could go through that solution and learn faster.

**Comment by katrinleinweber** [comment]
The `example.R` in each exercise could already be interpreted that way. But I think elevating that or one of the solutions as recommended, would be very difficult and not useful. 

Many exercises allow several approaches or or optimizations for one or the other goal (performance, readability, deduplication, etc.). I like Exercism for the diversity of these solutions.

Have you tried going for the number of `👍 Looks great!` button clicks and the comments? Checking these indicators might slow you down, but I think they are better learning opportunities than individual track mainainters' opinions.

**Comment by iHiD** [comment]
Thank you for the feedback/suggestions :)

> Many times I feel that my solution could have been written better. But to find out how, I have to wade through other people's submissions. 

We're failing here by you not getting mentorship to help you through this. v2 has been built to address exactly this and ensure that you get actionable feedback to help you through. We're also making it easier to find other solutions to look at.

> If one of the submission could have been marked as the recommended solution by the track owner, 

The beauty of the exercises is that there's rarely a "perfect way". I used the Food Chain in Ruby exercise as an interview question at got loads of different great solutions. Equally, my solution and @kytrinyx's solution are very very different, but I think both are great (arrogantly ;)). Making it easy to find the best possible solutions is a key aim of exercism and something we're working on.

**Comment by samir-majhi** [comment]
example.R? I haven't come across any such file in the first 5 exercises of Ruby. Where may I find it?

There might not be one recommended way. But there could be a group of answers that are good. Currently those are hard to find. Till now I've looked at those that have many comments. While it doesn't help me find a good solution, it does help me learn more from the discussions. 
 
Looks great! are only visible in the individual solution page, not in the list of solutions for an exercise. Which makes searching for solutions that have many Looks great! hard.

By the way. I love exercism. I came here to find open source to contribute to. But I ended up doing the exercises for fun ! Thank you for creating/maintaining this !

**Comment by katrinleinweber** [comment]
> example.R? I haven't come across any such file in the first 5 exercises of Ruby. Where may I find it?

On [github.com/exercism](https://github.com/exercism), search for the language you want, and click through to the exercise you are interested in. There should be an `example` file with the language's file extension (e.g. `.R`), or a some similarly named sub-folder (`.meta/solutions` in the Ruby track).

**Comment by Insti** [comment]
Note that the Ruby example solutions are not necessarily good solutions or examples of good Ruby. You are much better off browsing through as many of the submitted solutions on the Exercism site as you can.

**Comment by samir-majhi** [comment]
So should we do this? Or should we merge this into exercism/v2-feedback#99.?

**Comment by kytrinyx** [comment]
@samir-majhi I think your suggestion of merging this into the v2-feedback issue is the best way forward on this one.

**Comment by samir-majhi** [comment]
Alright. Closing this one.
