### ISSUE TITLE
Issue triage and useful labels

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#20]
The issues on exercism have been pretty chaotic since the start, but lately a few patterns have started emerging, and I have some ideas about how to become better at this.

The **language-specific repositories** should have tickets that are specific to that language track on Exercism. This is likely related to continuous integration for that track, improvements to exercises, calling dibs on porting an exercise from other tracks, or track-specific documentation that gets included in the exercism.io/languages/:track_id page.

Sometimes we have issues that will affect all of the implementations of a given exercise. For example, if we discover that we're missing an edge case in the poker exercise, this will currently affect Go, Python, Ruby, and Swift. We have started developing a process around how to do this in a way that will keep track of things while still making it easy for anyone to go tackle just one of these.

The short version of this is that first we figure out what the problem actually is and how we want to address it. Then we write up an issue that can be submitted to each of the individual language repositories using the [blazon](https://github.com/exercism/blazon#tips) tool. This issue will link back to a "top-level" issue so that we have a visual checklist of open/closed issues.

There are three things that I've been thinking about with respect to the issues on the exercism/exercism.io repository.
1. **label support** I think it's perfectly fine to have support questions here, we just need to get better at adding labels, that way it's easier to either find them or ignore them (depending on your goals).
2. **move discussions** If the action item is "figure out" or "decide" then we should move it into the discussions repository. This includes things like Gamification where I don't intend to implement it, but it comes up a lot. I'd like to be able to point people towards the full discussion with all of the various pros and cons.
3. **flesh out action items** Everything that is not a fuzzy discussion or a support ticket should be something that anyone who isn't particularly familiar with the project could come in and tackle. That means including enough context: why is this important? What happens to people because we don't have it? Where in the workflow is it? Where in the codebase is it?
4. **bugs? and bugs** If someone submits something that seems like it is a bug, we should make it clear whether we need more information, or need reproduction steps.

**Open Questions**
- Should we discuss messy (unclear, not yet actionable) cross-track issues in the x-common issues and tag them with "discussion", or should we discuss these things here in the discussions repository (which is intended for messy discussions).
- What labels would be useful in the exercism.io repository? At the moment I don't think the labels are particularly good.
- Can we get help from people to triage all the open issues? E.g. if someone could suggest which issues should be moved, which issues need more information, etc, that would be a huge help.

**Comment by IanWhitney** [comment]
I would find it easier if we had a clear, documented difference between X-common and Discussions. I think you've gotten at it with your 2nd point. If we can stick with that, then I'll feel more able to close issues on x-common and port them to discussions.

In terms of support, would you be interested in something like [high five](https://github.com/nrc/highfive), which is a bot that the Rust community uses to auto-assign issues and some other automated stuff. Auto-assigning to active track maintainers might improve our response time to issues.

**Comment by kytrinyx** [comment]
> I would find it easier if we had a clear, documented difference between X-common and Discussions.

Yeah, agreed. I personally think that everything that is a discussion should go in the discussions repository, including the things that are currently tagged "discussion" in the x-common repository.

I wish there were a way to move issues without having to do a lot of manual work :/

> In terms of support, would you be interested in something like high five

I'd be very interested in that. Auto-assigning to active track maintainers would help, and also I saw someone talking about how it would be possible to have the bot let us know when it's someone's first pull request. Something like that would be lovely, as it would help us be more verbose and explicit with people who are new to the whole process.

**Comment by kytrinyx** [comment]
I think that it would help immensely if people could look at the exercism/exercism.io issues and make one determination:

- Is this fundamentally a TODO (bugfix, small enhancement or change)?
- Or is it a suggestion or discussion, something where the action is to _decide_ something? (Might be that we need to decide how to handle a problem, or whether or not a feature is important, or even whether or not a problem is important, or just a generic discussion about possibilities and features).
- Or is it really unclear?

On top of this, we need a further distinction for TODOs:
- is it actionable as is? 
- do we think it can be closed without any further action?
- do we need more information or context?

If people would be willing to jump in and read an issue or two, and then post what it sounds like the status is, then we can label issues, and then slowly start to process them:

- dig into things that might be closable, to see if they really can be.
- figure out who might have more information (bug? Maybe we need reproduction steps)
- discussions can be moved to the discussions repository (summaries of the important points, anyway).

Finally, we could set a delay and say that anything that needs information from the original poster can be closed after X weeks (I'm thinking 2. Things can always be reopened later if need be).

This would move as many discussions as possible out of the main repository, which would give us a much better idea of what's on people's minds, and it would also make it easier for people to come into the main repository and see what could be tackled.

**Comment by kytrinyx** [comment]
For issues that are requesting a feature that we know we want to implement, or are describing a bug, it would be great to have a label that indicates that _yes, please make it so_, as well as another label that says something like _help describe what work needs to be done_.

E.g. in this issue: https://github.com/exercism/exercism.io/issues/2945

I think that the feature would be a huge win, and I am a bit swamped, so I would love it if someone else took some time to think through how we would do it. I would participate in the discussion (I have a lot of domain knowledge, the codebase is a mess, etc), but I wouldn't have to think it through from scratch (which can be very challenging when my head is full of a million things that I need to do).

**Comment by kotp** [comment]
I have recently started creating projects that can signal a "Yes do it" type of communication, as well as organizing the "things that are related" in a way that can help organize these.  If the project is on an organization level, it can organize all the things that are related, regardless of the repository location.

More localized changes, if more than 3 issues in the same repository, perhaps, if a project is created, it should be on that level.

As far as a label, "approved to implement" label and colored a shade of "green" to indicate a "Go!" status... I think would be good.  Or a "confirmed bug" also a "green" for the same indication.

**Comment by kytrinyx** [comment]
Green for "Go!" sounds like a good idea. I'd be interested to hear back in a couple months how the projects stuff is working for you.

**Comment by kotp** [comment]
[Exercism organization level projects](https://github.com/orgs/exercism/projects) so hopefully you will know when I know. :)  Still not sure how notifications work for those, etc.  But may be a good way to get a little higher level view on some of the things that involve multiple repositories.

**Comment by kytrinyx** [comment]
@kotp I don't think there are notifications for projects—at least I don't see a way to subscribe. I do think it's a good way to get a higher-level view of things, though!

**Comment by kotp** [comment]
exercism/discussions#108 to continue, I think it is a big enough conversation to have on its own, even if it is related.

**Comment by kytrinyx** [comment]
Agreed, thanks @kotp

**Comment by kotp** [comment]
Regarding [comment at June 25](https://github.com/exercism/discussions/issues/20#issuecomment-223837749) I have started (and may merge tomorrow) pull request and issue templates that can be used... it may be helpful to list these things in a checkbox to guide the things that we would like to see, reference labeling (they can check the box, we can label if they don't), and it is something that is up front, as well as in the contributing guide.  

The contributing guide could include the template as documentation even, so there would be no "Update contributing.md and the template to match" it would automatically match.

The templates issue is set to be field tested, on a limited basis, in the Ruby track, see exercism/xruby#497 (and make suggestions!)

**Comment by kytrinyx** [comment]
This issue was mostly about asking people to help triage the exercism/exercism.io repository. That repository now feels like it's under control, so I think we're done here. There is an interesting question about which labels are useful, but we have other open issues about labels, so I'm going to go ahead and close this.
