### ISSUE TITLE
Better guidance on solution setup for tests

### ISSUE THREAD

**Issue by a-dpq** [exercism/discussions#201]
I'm a beginner/intermediate learner of JavaScript and have found Exercism to be extremely useful so far. However, one of the biggest pain points for me is setting up solutions for the tests. There is virtually no guidance given on this, which is frustrating if you've never worked with a testing framework like Jasmine before.

Whenever I've gotten stuck, I've had to simply copy how other people set up their solutions, but whenever a slightly more complex test comes along, I hit another frustrating roadblock before I can even start on solving the problem itself. That's always a bummer, since I like to be able to figure things out myself, or at least understand the theory behind them so that I can do it myself the next time.

It would be great if you could provide a guide to setting up solutions for the tests at the beginning of the track. Ideally this would outline examples of the many different setups that users will encounter throughout the track.

**Comment by m-a-ge** [comment]
So, you are confused because the exercise placeholder is not provided, am I right? 
We've had a similar issue in Python track, but it's mostly solved - https://github.com/exercism/python/issues/509

**Comment by a-dpq** [comment]
Yes, no templates are provided in the JavaScript track, so you have to start from scratch with each exercise. Providing templates, or at least a guide to setting up the solutions based on different testing formats, would be a big help.

Now I realized this issue should actually be posted in exercism/javascript.

**Comment by petertseng** [comment]
I don't have a rationale entry for JavaScript in https://github.com/exercism/discussions/issues/114; I only have an issue that says "stubs should exist for the first two exercises" so I either missed the discussion on any future exercises or it doesn't exist. You can look at the list for rationale that other languages have used, and if you do open an issue in the JavaScript repo it would be good to include it in https://github.com/exercism/discussions/issues/114

**Comment by a-dpq** [comment]
Thanks for your feedback. I've opened an [issue](https://github.com/exercism/javascript/issues/424) about this in the JavaScript repo, so I'll close this one.
