### ISSUE TITLE
Commiting tests together with solution

### ISSUE THREAD

**Issue by FabienTregan** [exercism/discussions#202]
I started the elixir track so I can go from "global understanding" to "actually able to do things", and it's been a great experience so far.

One issue I encoutered is that, past the 5th problem, I wanted to write more tests (the provided ones where good specifications, but I needed to split them into smaller easy problems to reach a solution).

Currently,  I don't think there is a way to submit (in a different file than the solution) the tests I wrote and helped me reach the design I submit when I submit test (i.e., tests that are part of the solution and not part of the problem).

I would be happy to submit them and to see what others have done.

**Comment by Insti** [comment]
You can submit multiple files by specifying multiple files during the submit command.

**Comment by rpottsoh** [comment]
It appears as though you can submit your tests file is you use the `--test` flag while submitting.

**Comment by rpottsoh** [comment]
According to v2.4.1
```text
C:\projects.git\exercism.projects\Delphi\bank-account>exercism s -h
NAME:
   exercism submit - Submits a new iteration to a problem on exercism.io.

USAGE:
   exercism submit [command options] file1 [file2, etc...]

OPTIONS:
   --test                     allow submission of test files
   --comment value, -m value  includes a comment with the submission
```

**Comment by FabienTregan** [comment]
Tank you, sorry I missed this one :)
