### ISSUE TITLE
Translations of exercise instructions

### ISSUE THREAD

**Issue by suchja** [exercism/discussions#203]
Probably there is somewhere a project wide decision, but I was not able to find it. So I would like to know whether there is any idea of translating existing exercise documentation to languages like german, spanish, ...

I‘m a online teacher and found that it is, especially for beginners, much easier to have exercises in their native language.

Obviously the translation will add additional complexity to the project which might not be good for maintenance. 

Curious to hear your thoughts.

**Comment by m-a-ge** [comment]
It will require a lot of work, especially considering the planned release of Exercism 2.0. But it's definitely possible. I guess this should be a community effort in any case.

Personally, I'm against this idea because English is an international language, and a good software developer should learn it at some point. It should happen sooner rather than later. But this is just my opinion and it doesn't reflect Exercism philosophy.

**Comment by NobbZ** [comment]
Personally I avoid German stuff in the programming world, unless it is really about core things that haven't changed in the last 40 years... About 90% of the programming related content I consumed in my early days was at least a major release behind. This changed my thinking about translations.

**Comment by katrinleinweber** [comment]
Have you tried [automatic](https://translate.google.com/) [translations](https://www.deepl.com/translator)? I translated teaching material, release notes, help pages etc. for software every now and then until recently, but this seems to be an obsolete skill soon. @NobbZ's advice vs. the benefits of learning in your native language might find its synthesis in machine translation.

I piped the [R exercise subtitles](http://exercism.io/languages/r/exercises) into [deepl.com/translator](https://www.deepl.com/translator) just now and found them pretty good.

**Comment by wolf99** [comment]
Providing Exercism 2.0  allows for it, CrowdIn could be used to offload some localisation effort - it's free for open source projects but free open source project use does need to be specifically requested. See https://crowdin.com/page/open-source-project-setup-request

**Comment by suchja** [comment]
Totally agree on the importance of English! However People are different and especially the first steps are probably the most difficult. So in an attempt to divide and conquer it seems to me a valid way to start with learning to code and then start improving English. 

Maybe the core question is how many of the exercises are for real beginners and thus a translation would make their start much easier. If there are only few exercises for beginners and the complexity for such a change is that high, then it isn‘t worth it. 

When you say it isn‘t easy to implement what would be the most difficult task?

I haven‘t come across something awesome and impressive for practicing coding like excersim. I’m really happy that I stumbled upon this project.

**Comment by NobbZ** [comment]
Independent of the language of the exercise itself, we can't guarantee to have mentors speaking that language. So right after haing implemented "Halle, Welt" exercise, I'm confronted with a person that only speaks english… Or another language that is even more greek to me…

Be honest right from the start, the language of the service is english, nothing else.

**Comment by suchja** [comment]
@NobbZ that’s the killer argument. I only thought about the exercises itself, but that‘s (now also to me obvious) only the first step. 

Thank‘s for all the suggestions. I‘ll have a look into automatic translation and haven‘t even heard about CrowdIn and the other stuff. So a lot to learn from this conversation. 

Thank you again and I’m impressed how alive this project/community is.

**Comment by katrinleinweber** [comment]
About the "killer argument": we could make it clear that only the "self-service" parts of the website will be translated. That could prevent mentoring problems and even highlight what @NobbZ argued initially: you can't get around English. Maybe for the entry, but not for long.

**Comment by kytrinyx** [comment]
The question about translations comes up on a regular basis, and for now we've decided that we aren't going to invest in it (for all the reasons that are mentioned above), even though there are very good arguments for investing in it (also mentioned above)!

I'm going to close this, as we're not planning on implementing it in the near term.
