### ISSUE TITLE
Make travis-ci tests faster by only testing changed files.

### ISSUE THREAD

**Issue by Smarticles101** [exercism/discussions#204]
[Dart track has an issue on this](https://github.com/exercism/dart/issues/63) and @kytrinyx asked for one to be made here, but it never happened, so I've done it.

The idea is that only modified exercises should be tested by the ci.  The java track has implemented this approach a while ago and it significantly decreases build time for most PR's, however this has also become problematic due to github's rate limit (we call github's api to get changed files). Another approach is to use `git diff-tree -r --name-only HEAD master` however, I found travis doesn't seem to have a ref of master, so I didn't end up using it.

Just my thoughts on it. Could be nice to see across all the tracks

**Comment by katrinleinweber** [comment]
https://github.com/exercism/java/issues/410, https://github.com/exercism/java/pull/688, https://github.com/exercism/java/pull/734, and https://github.com/exercism/java/issues/772 are the relevant issues / PRs, right? Can the code be copied verbatim plus some `java`-to-`$track`-replacement?

**Comment by NobbZ** [comment]
I think this should be decided by the track.

For erlang, where we have build times of usually less than 5 minutes a job (3 jobs), I do not think its worth the effort to implement a "only changed files" runner.

Also I really do not like the idea in generall. Even though I like to speed up development locally by only running affected tests, I always do a full run of the testsuite before commiting, just to make sure there have been no chaotic effects lead to failure in an area of code which seems to be unrelated by human and static analyzes. Therefore I tend to always run all tests on CI.

**Comment by wolf99** [comment]
How would this affect the case where there are no changes to exercises, but instead there are changes to the CI scripts? Then the changed CI script could be incorrect but it would not be realised as the build would not run within the PR that changes it.... is this correct?

**Comment by kabiir** [comment]
@wolf99 I think if there is a test script for CI script then only running CI for that PR makes sense otherwise after the PR is reviewed and merged the new CI script will take effect. That's how it works, I think. Now if the desired effect is to run the newly updated CI script in the PR itself for testing if it works and produces desired output then there needs to be some logic that updates the active CI script to be replaced by the new CI script and any subsequent commits to trigger the new CI script for the that PR only, so that other PRs are not affected by a faulty script being updated. After the PR is merged all future and current PRs will use the new CI script.

**Comment by wolf99** [comment]
@kabiir Yes, this is my point I guess, that allowing the CI scripts themselves to be tested within the PR that changes them would be quite complicated to implement across all tracks... is the alternative to potentially let errors creep into CI scripts though? or test CI scripts separately?

WRT: 
>Could be nice to see across all the tracks

The C track build currently usually runs in under a minute or two so AFAIK a speed increase, though noticeable, would also be minor - at a guess the C++ track would likely be the same.

**Comment by N-Parsons** [comment]
Testing only the changed files might be useful for some tracks where tests run for longer, but the risk/reward should be weighed up. Heuristics can often be quite fragile and fail in unexpected ways, particularly if other things change over time. A recent example of this is the test script for the Python track that permitted arbitrary module names, which was only discovered when one of the maintainers noticed that a merged test file imported the wrong module name - an error that would prevent learner's tests from passing unless they fixed the import themself.

The Python tests currently take about 30 seconds per Python version - spinning up each VM often takes longer than running the actual tests. As a result, I don't think that running only a subset of tests wouldn't be worth the risk of errors creeping into the Python track.

**Comment by NobbZ** [comment]
Also there are tracks like idris, where a majority of time is currently spent in compiling the actual runtime system and compiler for the language because they are not available as a travis image nor as a pre-compiled package.

Those tracks won't gain much, if anything, from such an "incremental" or "partial" test behaviour.

**Comment by NobbZ** [comment]
> do you have any examples of this happening where a change on one exercise may pass a test specific to it, but the full tests would not pass even though they passed before the change?

Not for exercism tracks, as exercises are strictly separate projects in the sense of the corresponding build tools.

It was more meant as a general note about the problems introduced by this technique in software industries.

In my opinion, CI should always run all tests.

I think that we should investigate other means of compile time shortening first.

* Caching global dependencies
* Sharing of common dependencies and their artifacts (at least in erlang it feels as if 50% of tests runtime is spent fetching and compiling the same deps over and over again)
* Optimize exercises that currently have a long run- and/or compiletime to shorten them drastically
* Evaluate if parallelizing those is beneficial (travis gives you 1.5 cores IIRC)

If and only if there are still long compiletimes investigate the partial runs proposed in this ticket.

**Comment by kytrinyx** [comment]
Thanks for discussing, everyone. I think the points that NobbZ makes are key: overall it's worth seeing how to improve performance first, before reducing the coverage (which increases the risk).

Ultimately, though, this is up to the maintainers of each track to decide.
