### ISSUE TITLE
Prolog Track needing attention.

### ISSUE THREAD

**Issue by Average-user** [exercism/discussions#205]
As I mentioned on [reddit](https://redd.it/7glsdm), I think another maintainer for the Prolog repository would be great, because it is kind of  forgotten. And I really like Prolog, makes me sad.

This "thing" comes with another side of the coin that I didn't mention on reddit, and it's that being Declarative Programming such a different paradigm, I've found that the exercises that helps you improving, are very often very different from the ones that are commonly used in Functional or Imperative Programming. So I think having the possibility of doing specific exercises for Prolog or other declarative languages would be great.

I hope someones gets interested on this. Thanks!

**Comment by deckar01** [comment]
I almost stared the Haskell track because I didn't think there was a Prolog track. After finding this issue I found it in the "Upcoming" section at the bottom of the page. I think it would be more productive to include it in the primary languages list. There are already languages with only 10-20 lessons in the primary list.

**Comment by Average-user** [comment]
@deckar01 That should help too, but it would be better to try do both

**Comment by Insti** [comment]
It is possible to write your own exercises, see the [coq](https://github.com/exercism/coq) track 
for an example: https://github.com/exercism/coq/tree/master/exercises/tautology

**Comment by kytrinyx** [comment]
I think it would be great to have custom exercises for the Prolog track (definitely possible; it requires adding some custom metadata for the exercise if it's not included from the github.com/exercism/problem-specifications repo).

I saw a great talk in 2012 https://www.youtube.com/watch?v=hEOVcLAPRG8 - based on that talk it seems like there would be a vast array of possible exercises inspired by LSAT problem sets and matrix puzzles.

**Comment by kytrinyx** [comment]
Also: /cc @exercism/prolog

**Comment by Average-user** [comment]
@kytrinyx 
Thanks, a good talk indeed. But what about the first issue of this issue (no pun intended)?
Do you know @parkerl , Is he too busy? Does he know anyone able to help in the track?

**Comment by kytrinyx** [comment]
I'll check in with @parkerl—my guess is that he's got a full plate, though.

**Comment by parkerl** [comment]
@Average-user sorry, I had to take a long break. I'm going to merge all the open PRs since they have been open so long. Thanks for your hard work on that. Again, my apologies. 

We would LOVE to have another maintainer on that track. Interested?

**Comment by Average-user** [comment]
@parkerl No problem, we all have moments of a lot of work, thats why may be good to have another maintainer.

>We would LOVE to have another maintainer on that track. Interested?

I think I don't have the necessary experience neither with Prolog or git(hub).

**Comment by kytrinyx** [comment]
@Average-user We can help with the experience with Git(Hub) :-)

In terms of Prolog the question is more... do you think you could help out? Even responding to issues, merging pull requests that seem good to you would be incredibly helpful. And if someone else comes along and knows more Prolog-specific things, then maybe they'll point out things that should be different... and you can help make that happen too.

If you're interested I'd be delighted to add you to the team.

**Comment by Average-user** [comment]
@kytrinyx I can help wit PRs and issues yes. In the worst case scenario I will have to check with @parkerl, which doesn't harm, I guess.

**Comment by parkerl** [comment]
@Average-user I think you are definitely qualified on the Prolog side based on the exercises you created. I am by no means a Prolog expert. As @kytrinyx said, we can help you with the rest. I would LOVE to have the help. It usually does not take too much time, but it does take some.

**Comment by Average-user** [comment]
[here](https://github.com/Average-user/adventofcode-pl-2017) is more of my work with Prolog if you want to check it out.

>It usually does not take too much time, but it does take some.

I have some time :) . I'm still at high-school.

**Comment by neganp** [comment]
@Average-user If you need someone to consult on occasional git or GitHub shenanigans, I can help out with with that side of things. I have zero knowledge of Prolog though, so that might work best as an informal arrangement rather than an official one.

**Comment by Average-user** [comment]
@neganp Appreciate that, thanks!

**Comment by kytrinyx** [comment]
Much appreciated, @Average-user! I've sent you an invite. Welcome ⚡️

**Comment by Average-user** [comment]
@kytrinyx I've accepted. Lets close this. Shall we?

**Comment by parkerl** [comment]
@Average-user awesome! Welcome! 

Wish I could have put “Open Source Maintainer” on my college applications. All I had was “beat Myst in under 8 hours”. 😕 😆
