### ISSUE TITLE
A great part of my experience with 'exercism' was having to use command line. #Independent #Confident

### ISSUE THREAD

**Issue by Ornataweaver** [exercism/discussions#208]
The features that I like:
- simplicity
- command line interface
- very important: I write the code on my computer. I'm not dependent on freecodecamp's in-site text editor. I write it here and I test it here. INDEPENDENT, Confident.
- very pragmatic: exercism does not explain too much from the very first task it gives you. You have to go out and search the web from the very beginning. Thus if you do the first step you will never give up. You are used to leaving and browsing around.
This was the problem freeCodeCamp had, and caused me to abandon it halfway. I grew dependent on it since it had every thing necessary to go on the first 100 hours. I was used to that green website and didn't like to search for the code I needed. So midway I was stuck.

I hope I have helped, since you guys definitely helped me in my life.

**Comment by Ornataweaver** [comment]
Check the issue which led to this one:
https://github.com/exercism/gui/issues/60#issuecomment-354273461

**Comment by iHiD** [comment]
Hi. I'm not sure what has changed that you don't like. Maybe you could list some core features that are missing?

**Comment by Ornataweaver** [comment]
It seams like another codewars or codecademy.
The other discussion was smooth, transiting it here made it look awkward.

**Comment by iHiD** [comment]
I'm sorry. I don't understand. Can you give me some features that you feel are missing (as per the issue title) please?

**Comment by Ornataweaver** [comment]
My problem was with the gui, because I think a programmer should not fear cli.
Our solution is to force the beginner take a simple step in command line before entering this realm. In fact that step would be the Gate they have to enter, the obstacle they have to conquer to enter.
Afterwards their fear of command line would fade away slowly.

Sorry that this is vague, it's because I moved the discussion from https://github.com/exercism/gui/issues/60#issuecomment-354273461 to here.
Have you read it?

**Comment by iHiD** [comment]
V2 still has the cli like v1. There is no change to that.

**Comment by Ornataweaver** [comment]
The option of having a gui would keep their fear of cli. They would avoid using cli and learning shell.
I say it because I had the fear. Specially I remember the first time I put "help" into bash, the result freaked me out.

**Comment by iHiD** [comment]
Sure. I'm not debating that, but there is no GUI in v2, so I'm not sure
what this discussion is about.

**Comment by Ornataweaver** [comment]
@iHiD thank you for agreeing with that. I think I should have put this discussion in https://github.com/exercism/v2-feedback/issues/1. Is there anyway to delete this issue?
I'm sorry for wasting your precious time.

**Comment by troglotit** [comment]
@Ornataweaver no need to worry about expressing your thoughts. And no need to delete this, you could just close it:
<img width="859" alt="image" src="https://user-images.githubusercontent.com/10955264/34423058-ac76c6e8-ec2a-11e7-88c9-d16c32783897.png">
And yeah, I rather agree with you on having only CLI: having multiple ways to do one thing slows maintenance and creates burden of choice for beginners.

**Comment by Ornataweaver** [comment]
Thank you all my friends. I can't say how exciting it is for me to join an open software like this and have conversations with you. It's my first.
