### ISSUE TITLE
What about adding solidity at exercism

### ISSUE THREAD

**Issue by dvsingh9** [exercism/discussions#209]
Solidity is one of the powerful smart contract oriented programming language and it can be great for learners if you provide a learning path at exercism.

**Comment by budmc29** [comment]
That sounds like a good idea, if you want to get started with it you can find more informations in here: https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md.

**Comment by Ornataweaver** [comment]
Let's list all the sources we find for learning Solidity here.

**Comment by kytrinyx** [comment]
@Ornataweaver @dvsingh9 If you wish to start a Solidity track, then please open an issue in https://github.com/exercism/request-new-language-track/issues/new as described in the documentation that @budmc29 linked to above.

**Comment by Ornataweaver** [comment]
I dislike sucking energy. I like creating it.

**Comment by Ornataweaver** [comment]
I like breathing fire.
