### ISSUE TITLE
Elm Language Track is Stale

### ISSUE THREAD

**Issue by tuxagon** [exercism/discussions#210]
Hello! I am a huge fan of exercism and contributed to the elm language track about 2 months ago, but haven't received any communication. I do not want to be disparaging towards any of the maintainers and decided to inquire as to what the gameplan is when a language track goes stale because maintainers are inactive for whatever reason. 

Thanks for all the great work!

**Comment by yurrriq** [comment]
If given access, I could review and merge Elm PRs as I'm able.

**Comment by budmc29** [comment]
You can both go ahead and open an issue here: https://github.com/exercism/elm, that you want to be contributors for the project, I am sure the current contributors are busy and will appreciate the help.

**Comment by tuxagon** [comment]
@budmc29 I took your advice and created an issue in the `exercism/elm` repo. Now we wait.

**Comment by budmc29** [comment]
@yurrriq have a look here: https://github.com/exercism/elm/issues/188
