### ISSUE TITLE
Tool for managing PRs across repos

### ISSUE THREAD

**Issue by wolf99** [exercism/discussions#215]
Hi folks, 
More a suggestion than an issue, for anyone that is a contributer to multiple exercism repos (or indeed, any other repos). 

[CodeCapitan](https://codecapitan.com/?utm_campaign=Glo%20Emails&utm_medium=email&_hsenc=p2ANqtz--6MDmH6Ubmecj6H1Lh-bhiinPFMLXBknqMDSdiVMt02_ZGnBu_2vCJlWbmJ-C9KC2in4WRacSAmDAPj_z-rBpCB3Wkhg&_hsmi=63560973&utm_content=63560999&utm_source=hs_email&hsCtaTracking=2513c80d-e145-4234-b11c-c1c5296b145d%7Cd5bfb62d-628a-4c7d-abaa-864c16f391b3) by GitKracken(Axosoft) is a web tool that explores better ways to manage PRs
With it you can:
- Create groups of repositories that aggregate PR info
- Filter and sort pull requests within groups
- View CI status, mergability, and more at a glance

Hope someone finds it useful!

*I'm not affiliated with this tool or Axosoft in any way, just thought it looked like it may help here as we are a project where lots of people tend to contribute time across multiple repos.

**Comment by Stargator** [comment]
Interesting, I know @kytrinyx and @exercism/configlet may see that as useful when they have to handle PRs across multiple tracks because of configlet changes.

**Comment by kytrinyx** [comment]
Thanks @wolf99! It's always a struggle to manage PRs and notifications. I have some very janky scripts that I maintain, and I'm working (occasionally) on a bot to help manage things based on my most oft-felt painpoints, but this could be an interesting one to try out. 💙
