### ISSUE TITLE
Is there a way to change it from independent mode back to normal mode?

### ISSUE THREAD

**Issue by sunboshan** [exercism/discussions#219]
Click independent mode in a track when first time enter the track, however want to change it back to normal. Is there a way to do that now?

**Comment by sdball** [comment]
I'd like to do this as well. If there's a way it's not obvious.

**Comment by NobbZ** [comment]
Yes, there is a way. It abuses URL manipulation and I can not find the details.

But it when it was tested it made the tester loose all progress.

See also exercism/exercism.io#3810

**Comment by kytrinyx** [comment]
We have an open issue discussing how we are going to solve it.
I'm going to close this issue in favor of https://github.com/exercism/exercism.io/issues/3985
