### ISSUE TITLE
Contributing back to exercism

### ISSUE THREAD

**Issue by bernardoamc** [exercism/discussions#22]
Sorry in advance if something like this has previously been discussed.

In these last few days I have seen people trying to contribute to exercism but unsure how to do so, I can only assume this has already happened a few other times. Navigating through the site I have not seen a link to something like a "Contributing guide", so it looks like we are expecting people to investigate the repositories and finding the correct `CONTRIBUTING.md` file for his/her case. The problem here is that there are tons of repositories and sometimes it is confusing to know where to look (my opinion here).

Should we have something in `exercism.io` explaining/redirecting people to the right place? I will paste a few screenshots to give some ideas, but I am not a design/UX guy, so bear with me.

## Idea 1:
![screen shot 2016-05-30 at 1 34 29 am](https://cloud.githubusercontent.com/assets/428984/15639804/b54e8e68-2606-11e6-9afa-601fe847f3cb.png)

## Idea 2:
![screen shot 2016-05-30 at 1 23 36 am](https://cloud.githubusercontent.com/assets/428984/15639808/c5c72cd2-2606-11e6-8085-2fd7643c05f7.png)

## Idea 3:
![screen shot 2016-05-30 at 1 24 58 am](https://cloud.githubusercontent.com/assets/428984/15639705/73ca315a-2605-11e6-902d-780f6416bd44.png)

**Comment by kytrinyx** [comment]
> In these last few days I have seen people trying to contribute to exercism but unsure how to do so, I can only assume this has already happened a few other times.

Yes! This is definitely a problem, and I've been trying to figure out how to improve this.

> The problem here is that there are tons of repositories and sometimes it is confusing to know where to look (my opinion here).

Yeah, totally confusing and overwhelming.

I think having a link in the footer would be exactly what we need, with a friendly page that gives people the right starting points, and then we can link to this friendly page from various places, including the person's dashboard.

I think the page could have a quick intro telling people a bit about how exercism is put together (lots of repositories, etc), that we welcome all sorts of contributions, and then have separate sections with typical ways that people contribute. Each section would give an overview of how that would work, and links to more information (the correct section of the contributing guide, presumably).

E.g.

- add new exercises to a track by porting exercises that exist in other languages
- make up completely new exercises
- subscribe to a language track repository and help review new pull requests
- survey all existing implementations of an exercise and extract canonical test data
- help triage issues! (I want to write up something about how people can help with this)
- fix bugs
- tackle improvements to the site
- help us figure out the hard problems by thinking out loud in the "discussions"

**Comment by bernardoamc** [comment]
> I think the page could have a quick intro telling people a bit about how exercism is put together (lots of repositories, etc), that we welcome all sorts of contributions, and then have separate sections with typical ways that people contribute. Each section would give an overview of how that would work, and links to more information (the correct section of the contributing guide, presumably).

This would be awesome! I can take a stab at this and we can discuss things further in the PR, what do you think?

**Comment by kytrinyx** [comment]
That would be fantastic! Thank you :-)

**Comment by Cohen-Carlisle** [comment]
Closing as this seems resolved. Feel free to reopen if I'm dumb and missed something.
