### ISSUE TITLE
Need help adding maintainers to the Pharo language track

### ISSUE THREAD

**Issue by samWson** [exercism/discussions#220]
I don't know if this repo is the right place for this issue, but I haven't found anything better. 

I'm getting the Pharo language track up and running. At the moment I have two people who are actively helping me out. However I can't add these people as maintainers/contributors to the repository. The settings for the [exercism/pharo](https://github.com/exercism/pharo) repository are hidden from me so I can't give anyone elevated privileges. This is making my job harder than it should be, and making it harder for others to contribute.

I'm new to being the maintainer of anything on Github so I may just be missing something. Is there anyone who can help with this by giving me the necessary privileges, or adding others as contributors?

**Comment by Stargator** [comment]
Each week dev.to has a post where open source projects can post what they are in need of. You may be able to find someone there that is familiar with Pharo and can help.

**Comment by Stargator** [comment]
Here's an example: https://dev.to/ben/whos-looking-for-open-source-contributors-july-16-edition-57li

**Comment by samWson** [comment]
@Stargator Thanks for the suggestion. I will give that a look. 

My problem isn't finding contributors though, it's that they can't contribute. I don't have control over the settings of the repo, so I can't add others as admins/maintainers or contributors. I'll admit that I may be short of knowledge here. The repo is public so maybe other people can do all they need to be able to do with just their Github account and no special privileges over the repo. I just need people to be able to open/close issues, merge pull requests etc. Is all this possible without any elevated privileges?

**Comment by iHiD** [comment]
I've flagged this for @kytrinyx - I'm sure she'll be able to help you :)

**Comment by samWson** [comment]
@iHiD Thanks for the help.

**Comment by kytrinyx** [comment]
At the moment only org admins can give people write access. We have a bot that will make this easier but I have yet to deploy it. I will give you contributors write access. Would you confirm their GitHub usernames?

**Comment by samWson** [comment]
@kytrinyx Please give @bencoman and @macta write access. Thanks for the help.

**Comment by kytrinyx** [comment]
Done! I'm going to close this for now. Feel free to email me (email on my profile page) if you find more people you want to add.
