### ISSUE TITLE
profiles private link gone?

### ISSUE THREAD

**Issue by masters3d** [exercism/discussions#221]
https://exercism.io/profiles/masters3d/77d47b1cec02419489bbcebaf3236d80

Are there plans to expose a private link of progress like it was possible in the old site via profiles? By the way, great job on the new site!

**Comment by wolf99** [comment]
Did you mean something like this? https://exercism.io/my/tracks/c

**Comment by masters3d** [comment]
No, the profiles view was a private link that could be shared without authentication.

**Comment by iHiD** [comment]
> Are there plans to expose a private link of progress like it was possible in the old site via profiles? 

@masters3d If you publish the solution but don't put it on your profile, then that achieves similar to what was in v1. However, you can't see the full conversation, only the final iteration. 

We're going to work on improving options around here once we've got to a stable place.

> great job on the new site!

Thanks :)

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, as I _think_ it's answered with the "published but not on my profile". We will also be thinking a lot more about the profile / sharing in the future.

If I'm missing something, would you please open a new issue in http://github.com/exercism/exercism.io/issues?
