### ISSUE TITLE
TODO leaking on preview 

### ISSUE THREAD

**Issue by masters3d** [exercism/discussions#222]
Some places like Discourse show a preview of the page. 
![image](https://user-images.githubusercontent.com/6539412/42722624-068918e2-8704-11e8-9e91-b8f032cf6e4e.png)

**Comment by iHiD** [comment]
Thanks for this. We're still waiting for the maintainers of the swift track to [do a few things on the track](https://github.com/exercism/swift/issues/345). 

If you would like to submit a short blurb here, then I will **gratefully** merge it. You can edit the file on GitHub here: https://github.com/exercism/swift/edit/master/config.json#L4

For an example check out, C#s: https://github.com/exercism/csharp/blob/master/config.json#L4

**Comment by masters3d** [comment]
> So maybe the tracks where this is the case should be disabled until we have a more active community around them?

That is not my prerogative. How about something more playful like: "Oh oh, Usually there is really cool description of the language here. Want to contribute one? Please go here. " Instead, the tone of this issue and the TODO is more like:  ""The maintainers didn't do something they were suppose to do. There is not community support!" 

I agree on how small this change is but the old site was already using this: https://github.com/exercism/swift/blob/master/docs/ABOUT.md
So as a developer, I consider this was a breaking chance that was introduced by the new version. 

As a maintainer or developer, if all I had to do is to make sure the documentation is in the correct format I would've stop doing a long time ago.

**Comment by iHiD** [comment]
I agree - it was a breaking change. But it was a change that came with ~9 months of beta releases and multiple requests for it to be looked at. If it's something that people care about it's super trivial to fix for anyone that is familiar with the langauge. And if it's not something people care about then it won't get fixed. 

The maintainers choose what they spend their time on and I respect that this might be something that they feel is not important. But if its important it's a 2min fix.

I agree a nicer error message might be good. I actually argued this internally but others felt the TODO prompt gave a stronger incentive for it to be fixed and I think that's a fair pov, which is sort of born out by the fact we're having this conversation.

**Comment by kytrinyx** [comment]
@masters3d I'm curious if there is something we could have done to help encourage you and the other maintainers to add a blurb in the past 9 months. The "about" is included in the new site.

We've posted several issues about the blurb, and also asked maintainers to preview the site on the beta that has been up for quite some time.

Was it not clear that this needed to be done for the launch?

**Comment by iHiD** [comment]
(@masters3d for clarity - I didn't know you were a maintainer until I just spoke to @kytrinyx about this issue)

**Comment by masters3d** [comment]
It’s all good. As far as nudging people to make these types of changes: I think making this part of the configlet test would be helpful, I very much would fix it when it broke the build. In the same way when te confi.json schema changed, we dealt with the change and conformed new changes to keep the config happy. 

If it is important enough, give us heads up when some schema is required (like a ticking bomb) then break my build when that time comes. :)
