### ISSUE TITLE
Feature request - "I'll pass thanks" behaviour

### ISSUE THREAD

**Issue by nywilken** [exercism/discussions#224]
@soniah open this issue in https://github.com/exercism/cli/issues/636

“As a mentor,
when I click "I'll pass thanks"
it should take me to the next item in the mentor queue, rather than back to the "Solutions you're mentoring" page.

By making it easier for mentors to browse the queue, more comments will be made. In my opinion...”

**Comment by soniah** [comment]
👍

**Comment by iHiD** [comment]
Thanks @nywilken and @soniah 

This is an interesting idea. One thing that I'm not clear on yet is how mentors want to progress from solution to solution. Some are just taking them top to bottom, others are choosing a series of solutions to one particular exercise. We need to understand a bit more about this behaviour and how we can optimise for it. We're definitely thinking hard about this and working on making it as best as we can for you :)

**Comment by kytrinyx** [comment]
I personally choose specific exercises, so I typically go to the mentor dashboard and then open five or six exercises in different tabs.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this -- we have a whole heap of things to figure out with respect to the mentor dashboard, and at the moment the workflows are different enough that we aren't ready to change the default flow. Thanks for bringing this up!
