### ISSUE TITLE
Anyway to just do this online within the site?

### ISSUE THREAD

**Issue by legionio** [exercism/discussions#229]
Title pretty much explains... having to download files etc feels like an anti-modern approach.

**Comment by NobbZ** [comment]
You consider it old school to be able to do things offline, without the need of a browser? To be able to pick whatever editor you like? Even pick the exact version of a language you want to try? Learning under real world circumstances? Etc...

**Comment by legionio** [comment]
Text editor is arbitrary... I don't care for the editor for as long as it supports the language in question

**Comment by legionio** [comment]
I also follow the path instructions for MacOS provided too. It just doesn't work. Any other PATH related request I get with any other software works.. just not exercism.

**Comment by NobbZ** [comment]
A lot of people care for their editor. For example I do, and no browser will ever be able to replace my Emacs.

I do even write my mentors comments in Emacs most of the time.

Downloading, solving, uploading, this makes me able to have a workflow scripted around that runs tests when I want to submit, creates a git commit, asks for the commit text, pushes the commit and finally sends the changes to the page. This were not possible in a full in browser workflow.

Besides of that, maintaining the necessary infrastructure for more than 30 supported languages is close to impossible for a loosely coupled crowd maintained project as this, not to even speak about paying the infrastructure.

**Comment by legionio** [comment]
@NobbZ I don't care for the editor.. this isn't a discussion on whats a good editor or why you like it.

**Comment by ryanplusplus** [comment]
It sounds like you are looking for a different tool. Exercism is constructed in a way that enables what @nobbz described and in a way that it can be supported by volunteers. I understand that this isn't what you're looking for. That's okay. What you describe sounds like a great tool, it just isn't Exercism and there's not a clear path to get there from where Exercism currently is.

**Comment by iHiD** [comment]
@legionio Also, please calm your tone when responding to comments if you post again on the Exercism Github repository. Thank you.
