### ISSUE TITLE
How to publish hidden solution?

### ISSUE THREAD

**Issue by enaheld** [exercism/discussions#231]
Apologies if I'm asking this question in the wrong place.
When I submit a solution and then go to the "community solutions" page for that exercise, my solution is market "hidden" with a box that says "Publish your solution to see others' reaction." When I click "publish your solution..." bar, my solution displays but it doesn't publish. I've searched for instructions on how to publish solutions but I can't find anything. Could someone let me know how to do it? Thanks

**Comment by rpottsoh** [comment]
Issue moved to [exercism/exercism.io #4047](https://github.com/exercism/exercism.io/issues/4047) via [**ZenHub**](https://www.zenhub.com/)
