### ISSUE TITLE
A way to tell how a track is doing

### ISSUE THREAD

**Issue by singpolyma-shopify** [exercism/discussions#232]
Since the switch to V2, I've been churning along on the now "extra" exercises in my language track (rust) while waiting for mentor feedback on my existing "core track" work.  I have three submitted items, plus all my "extras".  I've now run out of "extras" with no movement on my core track items.

I understand that with the launch of the new site, the mentors are probably all overloaded with the existing content that got imported, etc.  So, what I think would be nice would be a way to see how much.  Like, "you are nth in the queue" or "there are n other solutions waiting for feedback" or similar -- just to give students a sense that progress is happening even if we're waiting for our own exercises.

**Comment by NobbZ** [comment]
As mentors are able (within bounds) to mentor the exercises in any order, beeing the 1st would actually mean you are the next. Waitng as the 1st for a week then is just another pain.

But yes, in general, I do think this is related to exercism/exercism.io#3834.

**Comment by iHiD** [comment]
@singpolyma-shopify Sorry the new experience is slow for you atm? Which track are you in? There are 3 that are currently pretty overloaded.

**Comment by kytrinyx** [comment]
_We've imported this issue to the https://github.com/exercism/exercism.io repository._
