### ISSUE TITLE
Beginner Interaction with Terminal

### ISSUE THREAD

**Issue by abigailloosle** [exercism/discussions#233]
I have just barely started with the Javascript track but am stuck! I have moved the folder successfully to the bin folder and even have downloaded the hello-world files.

However this bit of code won't run. My terminal won't recognize this function.
`jasmine hello-world.spec.js`

I've tried downloading jasmine and node.js but that hasn't fixed my problem.

I know I am a super beginner at this but can someone help me see what I'm missing here?

**Comment by NobbZ** [comment]
> However this bit of code won't run. My terminal won't recognize this function.
jasmine hello-world.spec.js`

How did you install `jasmine` and `node`? What operating system are you using? What is the exact output in your terminal when you run `jasmine hello-world.spec.js` and in which folder (absolute path please) are you in when you run it? What is the output of `exercism workspace`?

**Comment by abigailloosle** [comment]
![screen shot 2018-08-02 at 3 38 56 pm](https://user-images.githubusercontent.com/32072507/43612655-37a30c1a-966a-11e8-9440-ff1d995f22f0.png)

I am running macOS 10.13.5

**Comment by NobbZ** [comment]
Okay, but you missed to explain how you installed `jasmine` and `node`.

**Comment by kytrinyx** [comment]
_We've imported this issue to the https://github.com/exercism/exercism.io repository._
