### ISSUE TITLE
Dockerization of track environments

### ISSUE THREAD

**Issue by bi1yeu** [exercism/discussions#234]
Hi Exercism team -- I created a [project](https://github.com/bi1yeu/exercism-docker) to make it easier to get started with Exercism if one's already familiar with Docker. Rather than having to install the Exercism CLI and any of the specific tooling around a track, you could just build / run the relevant image and begin coding.

The project is a few hours old, only supports the Clojure and Python tracks, and I've only tested it on MacOS. But my hope is that if somebody is looking for a way to being experimenting with a new language and/or Exercism, this could help slightly lower the barrier to entry. Just wanted to put it on your radar.

**Comment by kytrinyx** [comment]
This is cool, thank you for sharing.

One of our long term goals is to allow people to try out a language from within the browser (something like https://try.dot.net/ but for each of the existing languages). That's unlikely to happen in the next 18 months, though, for a number of reasons.
