### ISSUE TITLE
List of unimplemented exercises for track in v2

### ISSUE THREAD

**Issue by cmccandless** [exercism/discussions#235]
Is there an equivalent page to the old http://exercism.io/languages/python/todo? Currently, that URL redirects to https://exercism.io/contribute.

**Comment by Stargator** [comment]
@kytrinyx @iHiD @NobbZ

**Comment by iHiD** [comment]
Nope. There's not. If you open an issue on exercism/exercism.io requesting one, we can work that out (eventually) though :)
