### ISSUE TITLE
Cannot publish solution

### ISSUE THREAD

**Issue by ftt** [exercism/discussions#236]
In the Independent track, I see no way of publishing (finalizing) my solution. How do I do that? I may have missed something in the UI :( I also tried to publish from the Community solutions page but couldn't either.

**Comment by sdball** [comment]
Same here. It looks like the new UX promoting the mentorship path has lost the ability to publish solutions from the independent track.

**Comment by kytrinyx** [comment]
_We've imported this issue to the https://github.com/exercism/exercism.io repository._
