### ISSUE TITLE
Adding more refactoring exercises

### ISSUE THREAD

**Issue by devonestes** [exercism/discussions#24]
I listened to [@kytrinyx on the Bike Shed](http://bikeshed.fm/65) this week, and I loved the idea of refactoring exercises. There are few ways to get more conversation started then around the merits of certain refactorings! I've been thinking of a couple ways in which that could be, done, but I wanted to bring it up here to get more feedback, and also to see if there is interest in having some refactoring exercises.

_Note: It's been pointed out that there is already one refactoring exercise in the Go track, so I guess the question is more about if there should be more of them and how to go about adding them._

So, my first thought is that we'd have an entirely new exercise, but this one would already be making all the tests pass. Then the user would be able to refactor the code as much as they like in an attempt to make it better while still keeping the tests green. For example, I can write a pretty poorly factored Markdown parser or something like that, and then let people go nuts making it better.

I don't think it would make sense to have a previously existing exercise for a refactoring exercise because then the user would have a reference in their heads already about how to refactor it. It would be better (I think) to have them come to the given problem totally fresh (unless they've written a Markdown parser before).

So, what do you think?

**Comment by kytrinyx** [comment]
I think it would be great to have more refactoring exercises. I like the idea of giving people a fresh problem that they've not necessarily thought about previously. The site already supports this—we give them a test suite and a fully functioning but dirty implementation, and they submit their refactoring per usual.

**Comment by devonestes** [comment]
So would step one then be adding an exercise to the x-common repo? And would it still have the same format given that it's a rather different kind of exercise? I can imagine how I might add this to an individual language track, but I'm not totally sure if there's anything we'll need to do differently before we get to that point.

**Comment by kytrinyx** [comment]
> So would step one then be adding an exercise to the x-common repo?

Yepp. We would need the usual `.md` and `.yml` files for it.

> And would it still have the same format given that it's a rather different kind of exercise?

Yeah, except that I don't think we'll have a .json file for it. We could, but there might not be any point.

> I can imagine how I might add this to an individual language track, but I'm not totally sure if there's anything we'll need to do differently before we get to that point.

No, I think it's straight forward. You can take a look at the `ledger` exercise in x-common for inspiration.

**Comment by kytrinyx** [comment]
@hankturowski also asked about refactoring exercises a while back in https://github.com/exercism/x-common/issues/94. Specifically he asked about the [Gilded Rose](https://github.com/emilybache/GildedRose-Refactoring-Kata) kata. We determined that the Gilded Rose was originally released under the MIT license, and that we should be fine including it provided that we have proper attribution.

**Comment by devonestes** [comment]
@kytrinyx After thinking about it some more, I think it might still be helpful to have a`.json` file for it so implementers have an easy way to create their test suites. The test suite will still need to be written - it just won't be referenced as much by the users doing the refactoring. It would probably be a convenience to have for other contributors, though, so they don't need to translate from another language that they might not be familiar with.

**Comment by kytrinyx** [comment]
@devonestes Yeah, you're right. The `json` would make sense, it just wouldn't necessarily help with implementing the messy initial solution.

**Comment by kytrinyx** [comment]
I believe that this issue has been settled satisfactorily: we encourage the inclusion of more refactoring exercises.

On a related note, we are doing a complete redesign from the core principles and questions up. Today we published the first set of documents that explore questions around enhancing and supporting people's motivation to learn and practice on Exercism: https://github.com/exercism/docs/blob/master/about/conception/README.md

In particular, check out the section on "expectancies of success", which links to a document where we explore an alternative way of structuring language tracks which we think will be more conducive to successful learning on the platform.

**Comment by kytrinyx** [comment]
Oh, also:  We have an issue open requesting thoughts and feedback on these design documents: https://github.com/exercism/discussions/issues/154
