### ISSUE TITLE
Rackspace - monitoring for Rikki?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#25]
I'm running rikki- as a daemon on a rackspace server. It's very barebones—an upstart script so that I have logging, and a bash/ssh script to deploy new versions.

For the most part, it just runs. It has died twice—once due to some rackspace server maintenance, and once (recently) due to... not actually sure what.

Anyway, we should probably have monitoring, but I don't know where to start on that.

@cforain @bernardoamc do you happen to know where I should start on this?

**Comment by kotp** [comment]
Probably monit on rackspace server.

**Comment by IanWhitney** [comment]
A +1 for Monit. I have found it easy to use for these sorts of things.

**Comment by kytrinyx** [comment]
We ended up not moving forward with Rikki for the v2 site. We will be re-implementing some variation on the automated feedback, but likely it will be in the form of hints to mentors rather than feedback to solution authors directly.

When we do, we will run it on the same infrastructure as the Exercism stuff, with the same monitoring.
