### ISSUE TITLE
Old, open pull requests - help with triage

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#26]
We have a lot of open pull requests (82 at the time of writing this).

https://github.com/search?o=asc&q=user%3Aexercism+is%3Apr+is%3Aopen+&s=created&type=Issues&utf8=%E2%9C%93

I would love some help getting all of these taken sorted out. I think there are three parts to this:

_Part I: Figure out why they are not merged._
- Did we forget about it?
- Did we give feedback, and the author didn't follow up?
- Is it controversial in some way, and we haven't decided what to do?
- Is it out of scope for exercism?
- Something else?

_Part II: Decide what needs to happen to it?_
- Should it be merged as is?
- Can it be merged with some tweaks? If so, can a track maintainer carry it? (see comments below)
- Should it be closed without merging? (see comments below)

_Part III: Decide on follow-up actions_
- Is there any update we should make to the documentation so that people avoid making pull requests that we end up not merging?
- Should we open an issue regarding a specific issue?
- Should we open an issue in the discussions repository to hash out the details of something that is unclear?
- Should we explain something better on the website?

---

**carrying a pull request**

This entails making a new pull request that includes the original commits so that the author gets credit.

The steps would be:
- create a branch from the pull request
- rebase etc
- make a final commit that tweaks the things discussed
- push to origin
- make a new pull request
- comment on the old pull request explaining what we've done, linking to the new one
- close the old pull request

**closing without merging**

If we do this we should be very careful to:
- recognize and show appreciation for the effort that went into it
- explain why we are not accepting it
- if relevant, mention what we _would_ accept (A different, similar PR? Help figuring out an underlying problem?)

**Comment by kotp** [comment]
To help keep track of this, I have the [bookmark](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+user%3Aexercism+sort%3Aupdated-desc+) that slows this in another configurable way. 

It also lets you track your mentioned, inside the "Exercism" organization as well.

**Comment by kytrinyx** [comment]
This call to action didn't work :) Closing. I'll think of something else.
