### ISSUE TITLE
Pull request review guide for new exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#27]
In some of the language tracks we don't have a lot of people reviewing pull requests, and I think it might be possible to write up a short guide or checklist of things that we typically thing about when reviewing a new exercise. This would make it much easier for people to help review new pull requests, even if they've not been involved in the project or language track yet.
- Is there a canonical data set for this exercise? (x-common, json)
- If so, does this follow it?
- Do each of the assertions make sense? (Are there copy/paste errors? Inverted assertions? Typos?)
- Are we missing any important edge cases?
- Does the order of the tests make sense? (Ideally each new test should encourage a small bit of new functionality or a small change. If a single test enforces functionality that is "introduced" with a later test, this can get frustrating and a bit confusing).

In general, we haven't necessarily been making the example exemplary, though I think some tracks have been focusing on this more than others. In what way should we evaluate the example code?

/cc @exercism/track-maintainers Is there anything in particular that you look for?

**Comment by verdammelt** [comment]
RE: example code - I think the example code should be good (evaluated like any exercise) but not clever (if there is a clever solution to the problem (like using `FORMAT` for the roman number exercise in Common Lisp)).

**Comment by kotp** [comment]
I think the example code should be 'good enough' and the tests really need to be the 'exemplar' case here as they are public facing.  If it is clever, it has little bearing on the impact on the Exercism.io website and how the interaction goes.  The tests are pivotal here, not the example code.

The example code initially tells the exercise designer that it is feasible, the potential 'hardness' of the problem solved and the location it should go.  It is important in that way, but not important to be more than simply 'good enough'.

**Comment by wobh** [comment]
Examples are a good idea but everyone submitting exercises are providing them already. Lots of exercises seem to have multiple, perfectly exemplary solutions--at least in Common Lisp. Perhaps in Java, Python, or Go the set of good examples for an exercise is smaller, but CL, Ruby, Perl, and Javascript, the same exercise could have lots of good examples.

I suggest a list of questions, centering around technique. One could ask oneself these questions while writing the exercise, or adapt for asking about on an exercise they're reading. I recall, one reason for breaking away from the "nitpick" terminology was to encourage question-asking for people who were uncomfortable or unconfident in giving critique.

**Comment by IanWhitney** [comment]
I use example solutions in two ways:

- As a track maintainer, I use them to pass the tests & CI.
- As a student, I use them to learn about aspects of the language that I don't yet know.

If I'm learning a new language I frequently have next-to-no idea how to solve a problem when I first look at it. Not because I don't understand the algorithm, but because I don't yet know that language's syntax/features/etc.

So I frequently go look at the example code. And then I read up on the tools that example code uses. And then I write my own solution.

Because of that, I try really hard to make the Rust examples idiomatic and, most importantly, not clever.

**Comment by kotp** [comment]
So should we strive for that, and direct people there to see an idiomatic solution?

I think your second point, as a student, that is what exercism is for, on the website, not the examples itself.

I have directed people to submit what they have so far, for discussion, to gain access to other solutions, rather than pointing to (necessarily) an idiomatic approach.  Sometimes this happens even if they have yet to get the tests to pass.  It gives that discussion a chance to happen.  I don't think the example code in the repository gives that same value.  I don't believe that is what it is there for.

Sorry, I may not be expressing myself well, I am recovering and unable to think clearly.

**Comment by kytrinyx** [comment]
I've been hesitant to mandate good/idiomatic examples, but I think that @IanWhitney is right—people probably do use them this way. I think it would make sense to start being more deliberate about making them idiomatic.

In terms of showing users an idiomatic example, I want to avoid ever showing people _one_ idiomatic solution. I'd rather show several possible approaches. There's an ongoing discussion in https://github.com/exercism/exercism.io/issues/2803 about some ideas surrounding this (and pros/cons of various approaches).

**Comment by Cohen-Carlisle** [comment]
I must admit, I have taken a peek at example solutions before hoping to get some insight into a 'good' implementation. However, I think any interest in making the example solution idiomatic for cases such as mine should be a quite distant second to their primary purpose, which I've understood to be demonstrating the problem can be solved and "testing the tests".

My primary reasons for this position are that:

1. exercism is supposed to have a social component and relying on the examples in this way is counter to that mission
2. the example exercises are 'hidden' and not integrated into exercism.io or the CLI
  a. this means the audience for them is going to be much smaller than exercism in general
  b. its a waste of time to invest too much effort into something so unofficial

3. There is no single idiomatic solution. A lot comes down to preference.

That said, I think _some_ effort should certainly go into making the examples follow well-established language best practices. Just not a lot.

**Comment by kytrinyx** [comment]
> I must admit, I have taken a peek at example solutions before hoping to get some insight into a 'good' implementation.

I'm thinking that this probably happens much more than I was aware of.

As long as we stick with "not clever" I'm OK with making them exemplary.

**Comment by IanWhitney** [comment]
> exercism is supposed to have a social component and relying on the examples in this way is counter to that mission the example exercises are 'hidden' and not integrated into exercism.io or the CLI
> a. this means the audience for them is going to be much smaller than exercism in general
> b. its a waste of time to invest too much effort into something so unofficial

The social aspect of Exercism can be huge, but you can't participate in it if you can't provide a working solution. For people like myself who are novices in a language, the example code can be vital recipe to follow.

> I'm thinking that this probably happens much more than I was aware of.

If you ever have some free time (hah), write a script that compares submitted solutions to example code. I've seen quite a lot that are character-for-characte matches.

**Comment by kotp** [comment]
I don't think there is any enforcement that you can't submit if the tests aren't passing, at least so far on the Ruby track that hasn't been the case.  Is there a social contract that states otherwise?

**Comment by kytrinyx** [comment]
> Is there a social contract that states otherwise?

I would not be surprised if people assume that the code needs to work. I don't know that we're very good at saying "we'll help you". Especially since in some tracks you're not going to get help at the moment (too few reviewers).

**Comment by ErikSchierboom** [comment]
To me, the example code is there mainly to verify that an implementation is actually possible and to help with structuring the tests. As the example code is not available from the website, I don't think it should carry much more wait than that. If people want to use it as inspiration, they're free to do so, I wouldn't want to guarantee it is the most idiomatic or clean solution available.

However, I do like the idea of having some pre-defined solutions per exercise (where applicable) to show different approaches.

**Comment by rchavarria** [comment]
I would like to add a point to the review guide (or *checklist*). That is to try to solve the new proposed exercise as if the track maintainer were a real exercism user.

It will depend on language tracks, but sometimes running all the tests and running tests as a user differs a little bit. I found myself having all tests passing locally and in the CI server, but when I tried to solve it, I was unable to run the tests: files weren't fetched correctly, missing dependencies, whatever...

**Comment by kytrinyx** [comment]
That's an excellent point—testing the fetching of it.

I think that this could be done in two steps:

- write the solution without having to fetch it
- then, verify that fetching it actually works

Verifying that fetching actually works is a lot more involved than just writing it and testing it locally, because you either have to set up the entire web frontend plus the x-api in order for it to work... or we have to merge it and deploy it to x-api to test it live.

**Comment by kytrinyx** [comment]
We have a guide for reviewing pull requests here: https://github.com/exercism/docs/blob/master/maintaining-a-track/reviewing-a-pull-request.md

There is some discussion here about the value of making the sample solution idiomatic, but we did not have a clear problem statement or suggestion about what decision we need to make, so I'm going to go ahead and close this as solved.
