### ISSUE TITLE
Make it so that we don't have to commit the generated javascript and css

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#28]
Right now when there are changes to the javascript or the css, we regenerate, and commit the changes. The reasons are very legacy:

In the beginning of the project someone submitted javascript stuff using a framework called lineman.js. This was at a time when everything was up in the air, and I never really thought this would be a real project, so I was basically accepting all pull requests, especially things that had to do with javascript or css, because these are things that I don't know much about.

Lineman.js had a custom Heroku buildpack. Heroku's buildpack changed, the custom lineman one stopped working, and by that time the original contributor wasn't around anymore.

I ripped out the buildpack and started just committing the generated files, because I didn't have the time or energy to dig into how to do it right.

Then someone came and fixed a lot of the CSS and this is now generated "stand alone" using compass, but Heroku doesn't generate it, we still commit it to the project.

We've still got lineman, which has lost the configuration management wars. We should probably be using one of the common tools so that people who know javascript can easily jump in and help figure this out.

Apparently, if we follow certain conventions, Heroku will be able to "just do it". If we can figure out what "it" is, and what those conventions are, maybe we can simplify things a bit.

Maybe we need to figure out CSS and JavaScript separately.

I do not have time at the moment to rewrite the APIs, even though this should most certainly be done at some point, so I really want to do the simplest possible thing to reduce complexity and make it possible to stop committing generated files.

One contributor started working on this, but got stuck on the buildpack thing.

**Comment by tejasbubane** [comment]
> One contributor started working on this, but got stuck on the buildpack thing.

Not sure if I will be able to work on this, but for reference of anyone who stumbles upon this issue, can you point to this discussion?

Did anyone try using @hone's [buildpack](https://github.com/hone/lineman.js-on-Heroku) with cedar-14 as suggested in the [old lineman buildpack readme](https://github.com/linemanjs/heroku-buildpack-lineman)?

**Comment by kytrinyx** [comment]
Here's the old discussion. I don't know if anyone tried hone's buildpack.

**Comment by hone** [comment]
Hi, how can I help?

**Comment by kytrinyx** [comment]
@hone: don't worry about it—we have a huge amount of legacy crap in the CSS/JS, and everything is non-standard. We need to do an overhaul as far as I can tell, rather than try to shoehorn one of the buildpacks to work with our little disaster.

**Comment by hone** [comment]
@kytrinyx I've referred many people to exercism.io and I'd like to see your experience on Heroku be a great one. So, happy to spend some time helping if I can nudge the needle.

Specifically, the static buildpack uses nginx to serve static assets, so it might fit your use case here. A common setup would be to use node + static to build and serve assets.

**Comment by tejasbubane** [comment]
I am working on this.

**Comment by kytrinyx** [comment]
Finally merged @tejasbubane's PR. :tada:
