### ISSUE TITLE
exercism.io - full rewrite

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#29]
One of the biggest barriers to contributing to the website right now is that it's a horrific mess of hacks.

When I originally wrote the prototype, I didn't really know where anything was going. I thought it was going to be a tiny little hack, and it has grown beyond all comprehension. Now the ideas are coalescing into something coherent.

It's very, very important to have a clean and understandable code base in order for people to be able to contribute. Some of this might involve simplifying and rethinking certain parts of the app.

I am thinking about a few things:

Sinatra might not be the best choice, since a lot of contributors and potential Ruby contributors are quite new to programming, and they tend to have focused on rails development. Also, because the project is quite big, we end up reinventing things, and putting things in completely unconventional places.

Should we do a rewrite in Rails?

We should completely re-think the API and the interactions between the website and the CLI.

We should include all the x-api functionality in the main app. The important thing was to not have all the language tracks in the same repository, but the x-api itself doesn't make sense as a stand-alone thing, because we end up having some cross talk between the two apps.

We would need to ensure that old exercism CLIs either demand that users upgrade to the newest version of the CLI, which would support the new API, or have legacy APIs available. I'd rather not do the legacy thing.

If we were to do this sort of thing, I'd like to do it in lots of small stages so that we don't have any long-lived branches, and so that we're safe the whole way.

Here is the terminology that I've been adopting.
- **Track** -  track is in a language (e.g. C++) and has an ID (e.g. `cpp`)
- **Problem** - a generic description of a problem to be solved, can be implemented in any language
- **Implementation** - a language-specific implementation of a problem. It has a test suite in that language.
- **Solution** - an author's worked answer to an exercise. It may have 1 or more iterations.
- **Iteration** - a single version of an author's solution to an exercise.

I think that the x-api codebase (well, at least the stuff in `lib`) uses the correct terminology, and is pretty clean and easy to understand.

How would we go about thinking through a major cleanup effort? I think it would be important to avoid longrunning branches—we've been burnt by that before.

**Comment by GustavoCaso** [comment]
Thinking about rewriting in Rails it makes a lot of sense, base on the idea of simplifying for the new comers.

I don't ming start a little rails app and move code from place to place, but it would be great to have a solid idea abut the controllers and the code conventions we want to follow.

**Comment by ErikSchierboom** [comment]
I think a rewrite makes sense at this point, as the website is clearly becoming bigger and bigger and you'll need all the help you can get. When I want to participate in an open-source project, the first barrier is its structure. If things look messy or just unclear, I usually just move on. Ideally, I think one of the main goals of the rewrite is to make the barrier to get people to participate as low as possible. 

Having a better structured application will also help in finding and fixing performance problems, I found.

I don't really know anything about Ruby, but it seems to me that the best bet would be to use the framework most people use, which is Rails I guess.

Merging the API and the website makes sense.

**Comment by GustavoCaso** [comment]
Yes @ErikSchierboom definitely make much sense to merge the API and the website.

About making it in small steps we could start by moving the API to the actual sinatra app.

**Comment by wolverineks** [comment]
It seems like github and exercism have a lot of functional overlap. Any way to leverage that?

What if the cli pushed the solutions to a repo on the users github account, and Exercism used the github api to display the commits as different attempts?

**Comment by GustavoCaso** [comment]
Thats a good idea, it looks familiar like the Upcase product from the people of [thoughtbot](https://thoughtbot.com/), but the idea is for other people to comment on everyones solutions, this will force the user to go to github and comment in the user repo. Maybe looking for a solution intermediate of this two. The idea of showing the diff really sound super cool for `Exercism`

**Comment by kytrinyx** [comment]
@joeltaylor we talked a bit about something similar. Have any thoughts about it?

**Comment by joeltaylor** [comment]
Catching up on initial discussion — I'm really fond of the idea of doing a Rails rewrite. As much as I love Sinatra and the way Exercism has used it, I recognize the barrier for newcomers. Specifically, I think the conventions that Rails carries will be helpful for users to lean on when they're questioning existing design choices or where to put their contributions.

This seems like a great (and incredibly exciting) time to consider leveraging GitHub.  I'm fairly confident that this can be done while maintaining all of the current functionality (feedback, iterations, etc). I really like the idea of leveraging diffs, too!

I really like @wolverineks suggestion! While there are _a lot_ of implementation details to consider, I feel like it'd actually simplify things in the end.

One question I've been thinking about the most is how to handle pushing user submissions to GitHub. 

In order for the CLI to push code on the user's behalf to repo, we'd need read/write access to their repos. That sort of scope could potentially deter some individuals.

An alternative would be to add [hub](https://hub.github.com/) style functionality to the CLI so the user is actually pushing with their credentials. I imagine this would need to be made absurdly simple to prevent it from being a barrier. The CLI would potentially gain a number of new responsibilities.

**Comment by GustavoCaso** [comment]
What @wolverineks suggested, i like what upcase is using at the moment, what I haven't thought about is the way to add comments over the iterations inside the application, maybe `github` allow to bring the code from the commits, so we can display it and let the user comments on.

What do you think ? @joeltaylor @kytrinyx

**Comment by joeltaylor** [comment]
@GustavoCaso I believe we could store a user's commit `sha` to represent and iteration for an exercise and then associate comments to it. Looks like we can pull the contents of the file for each commit via the API using [trees](https://developer.github.com/v3/git/trees/). Would need to have them oAuth with Github though to avoid rate limiting. I think it'd also require full repo access :/

**Comment by kytrinyx** [comment]
We will be doing a full rewrite (in Ruby/Rails) as the conclusion of the design process described in the roadmap: https://github.com/exercism/docs/blob/master/roadmap.md#the-product

Thanks, everyone for weighing in!
