### ISSUE TITLE
Onboarding: diagram that shows how exercism works

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#30]
Last year @studiolo played around with some ideas about creating a diagram for how Exercism works.

I think that this could help in the onboarding process to give people an idea of where they're headed.

![b8d8d722-fb33-11e4-97b6-f05901b0ace3](https://cloud.githubusercontent.com/assets/276834/15805893/04cee1e4-2af4-11e6-944c-41b989a94bae.png)

I like the idea of this, and would want to emphasise the human aspects of the site more.

The original discussion is here: https://github.com/exercism/x-common/pull/82

**Comment by wobh** [comment]
If you center the down arrow and flip the right circle arrow to counter-clockwise, I think it'll give a more "physical" impression.

**Comment by gusseting** [comment]
I do think a graphic is super helpful in illustrating what exercism is about, and I agree @kytrinyx it would be great to emphasise the human/community aspects more, along with that new little known nugget of:
- submit your code
- **learn from the community by seeing how they completed the same problem**
- receive feedback

**Comment by kytrinyx** [comment]
We're doing a complete overhaul as described in #113 and #154, which will include a brand new onboarding experience.
