### ISSUE TITLE
About burnout and avoiding maintainer guilt

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#36]
Homebrew has a lovely document that talks about the things they've decided are important to be explicit about as maintainers.

https://github.com/Homebrew/brew/blob/master/docs/Maintainers-Avoiding-Burnout.md

Here's the original that homebrew's document was inspired from: https://gist.github.com/ryanflorence/124070e7c4b3839d4573

I'd love to talk about which of these ideas are applicable to exercism as a whole, or perhaps to parts of them.

/cc @exercism/track-maintainers

**Comment by Cohen-Carlisle** [comment]
I really like the maintainers as users bit. For myself, I should probably dedicate a small chunk of time to doing exercisms periodically as I've fallen out of the habit a bit. The no guilt over leaving I think definitely applies as well.

**Comment by rchavarria** [comment]
I see the maintainer as a user thing really important. I wouldn't say a maintainer that doesn't use the product can't be a maintainer any more, but I consider it important to use exercism to share the experience with the rest of the users.

Definitely, no guilt over leaving is quite important as well. I don't know too many open source projects, but I think is a very common problem in open source. Maintainers feel some kind of pressure when the are not as motivated as in the beginning of their contributions.

The fourth point in the article, learning to say no, I think it's just the maintainer's job. Accepting or rejecting pull requests and issues. Always talking to other contributors with respect, but not every contribution can be accepted. In these cases, I found useful opinions of other maintainers. Sometimes, I don't feel I have the power of reject something, so a second or third opinion helps the conversation to go forward.

**Comment by kytrinyx** [comment]
THere's a great thread on twitter by James Kyle about this: https://twitter.com/thejameskyle/status/825783661622472704

He also wrote this a few weeks ago: https://medium.com/@thejameskyle/dear-javascript-7e14ffcae36c

**Comment by kytrinyx** [comment]
Here's another great discussion. From Sarah Mei, this time: https://twitter.com/sarahmei/status/771078230266609664

**Comment by RecruiterBill** [comment]
HI all- I'm helping a Boston-based startup (distributed team) tackle maintainer burn-out and the larger problems that will come with it.  I'm looking for a Front-End engineer passionate about the problem to help this 4 person team start solving it. bill@thetycheproject.com for more details!

**Comment by kytrinyx** [comment]
@RecruiterBill I'd appreciate it if you didn't use the issues in the Exercism organization as a place to recruit folks. I'm going to go ahead and delete the comment, as it is not related to the discussion at hand. Thanks.

**Comment by katrinleinweber** [comment]
Homebrew's doc has/was moved to https://github.com/Homebrew/brew/blob/master/docs/Maintainers-Avoiding-Burnout.md ;-) BTW is it OK around here to edit other peoples posts in such simple cases of updating a link?

**Comment by kytrinyx** [comment]
> BTW is it OK around here to edit others' posts/comments in the simple case of updating a link?

Yeah, I think that's fine.

**Comment by kytrinyx** [comment]
I'm going to close this for now. We still need to address it, but I'm going to table the discussion for a few months until we get the new site running smoothly.
