### ISSUE TITLE
Adding a Quote button to comments on the website

### ISSUE THREAD

**Issue by oalbe** [exercism/discussions#4]
Hey there,

I don't know if this is the right place to ask this, but the description says _future features_ so I figured I'd post here.

Basically, recently I'm finding myself thinking that, especially when replying to long comments, I would totally make use of a Quote button. I'm talking about something that will copy the message one is replying to in the box for the answer (adding maybe the `blockquote` markdown syntax), preserving the formatting, the links etc.

I'm aware one can just copy-paste the thing, but this obviously doesn't keep any formatting and any link, making the quoted text lose some of the context that might be provided by that.

Of course, this is more like one of those _last-of-the-problems_ issue, but I thought about submitting it anyway.

**Comment by kytrinyx** [comment]
Yepp, this is the right place.

I think this could be useful, and probably not too difficult to implement. My main concern is that the user interface for that page is already kind of a mess, and adding more stuff to it might make it harder to understand/use.

> this is more like one of those last-of-the-problems issue

Yeah, it's not very high up on the list, but definitely a nice-to-have. If someone suggests how to do this visually without making the page harder to use, then I would not have an issue with adding this.

**Comment by oalbe** [comment]
>  If someone suggests how to do this visually without making the page harder to use, then I would not have an issue with adding this.

If I'd have to make a suggestion, I'd say something along this line:

![ui-example](https://cloud.githubusercontent.com/assets/3052609/14003099/9886c146-f150-11e5-92bb-0eb6d5a40ec3.png)

Or, to keep it more minimal, maybe something similar:

![ui-example2](https://cloud.githubusercontent.com/assets/3052609/14003100/98afcc80-f150-11e5-8e68-916d310a132e.png)

But I have no idea if this objectively makes the page harder to use or not.

**Comment by kytrinyx** [comment]
I wouldn't understand what the button does without trying it, I think. What do existing sites do when they have this feature?

**Comment by oalbe** [comment]
Actually I've seen it on forums like vBulletin, but IIRC it is just called `"Quote"`. I checked some Discourse forums but it seems to be missing this feature. It has a `Reply` button, but as you would expect it doesn't only quote the message, it also makes you reply _directly_ to a certain post from a user (which means your reply goes directly under their post).

I guess it wouldn't be that bad to try it once and learn it forever, would it?

**Comment by kytrinyx** [comment]
Yeah, a tooltip would probably solve it. Given that, I'm open to having this be implemented.

**Comment by oalbe** [comment]
And here my usefulness ends. I'd like to help but Ruby is not my thing, I'm sorry.

**Comment by kytrinyx** [comment]
@oalbe :) Understood. From here we'll write up a proper todo so that someone whose thing is Ruby can grab it.

Thanks for helping elaborate this!

**Comment by petertseng** [comment]
The bad news: This request was duplicated https://github.com/exercism/exercism.io/issues/2449

The good news: And then it was implemented in https://github.com/exercism/exercism.io/pull/3327! All right!
