### ISSUE TITLE
Sort solutions by "Looks Good"

### ISSUE THREAD

**Issue by wolverineks** [exercism/discussions#45]
As the number of solutions starts increasing, it would help newbs get familiar with idiomatic/high quality code if the solutions with higher "Looks Good" ratings could be sorted to the top.

Does this fit with the Exercism vision?

**Comment by kytrinyx** [comment]
Hi @wolverineks, thanks so much for asking!

I don't think that the feature you're suggesting fits in, but I do think that the underlying need that you're describing is very real, and definitely something we should solve.

We've discussed aspects of this in a long (and very interesting) discussion here: https://github.com/exercism/exercism.io/issues/2803

Would you take a look at that and see if this answers any of your questions? Also, if you have opinions/thoughts I'd love to hear what you think in that thread.

**Comment by jtigger** [comment]
Looks like we properly folded this question into that other issue; closing.
