### ISSUE TITLE
Searching solutions

### ISSUE THREAD

**Issue by kotp** [exercism/discussions#46]
I am not finding a way to search solutions to problems in a track.

For instance, perhaps I want to pull solutions that use a specific method, for examples of how others have used it.

Currently, there doesn't appear to be a way to do this in the web interface.

**Comment by kytrinyx** [comment]
No, we don't have a way to do that.

**Comment by clarkburbidge** [comment]
+1
Also...
tagged solutions
vote +/- solutions

**Comment by kytrinyx** [comment]
This is an area that we are working on in the new prototype: https://github.com/exercism/v2-feedback/blob/master/README.md

This is not yet completely solved, but one of the big things that we will be continuously working to improve is discoverability/searchability of existing solutions.

I'm going to go ahead and close this, though, as we would like any further discussion about the topic to be based on the new prototype, in the v2-feedback repo.
