### ISSUE TITLE
we have a lot of repos! Any way to help people figure things out?

### ISSUE THREAD

**Issue by petertseng** [exercism/discussions#49]
It's well noted in #48 that we have a lot of repos. We even admit this ourselves in https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#we-will-gladly-help-you-help-us where we call ourselves a "sprawling 50 repository beast" (and it's grown since that was written).

It makes me wish that there were a way to categorise our repos somehow - the language track repos are all one obvious category, for example. What if I want to look at the other categories too without having to scroll through all the language track repos?

A hacky way to do this with current resources may have been to create a separate org for the language tracks, but that comes with problems of its own (so... do track maintainers have to be added to multiple orgs? doh!)

The result of this discussion may be as simple as "make a request to Github for a better way to organise repos, and in the meantime we'll have to make better documentation", but if someone has an idea on how to make life better, it would be good to hear

**Comment by kytrinyx** [comment]
I think that a little bit of documentation would help a lot.

@exercism/rgsoc2016 is working on a PR for a repository page: https://github.com/exercism/exercism.io/pull/2965

As noted in #48 we're missing a couple of things there for it to be complete, but I think that it would help.

Now that you bring it up, it sure would be nice to have labels for repositories. `tool`, `language-track`, `deprecated` would be handy labels for exercism to have.

**Comment by petertseng** [comment]
http://exercism.io/repositories is pretty good, so I'll consider that good for this. Assuming that that page is sufficiently available to omeone with the question "there are so many repositories, how do I start".

Github letting us categorise repos would still be helpful, but that's not quite something we can control.

**Comment by Insti** [comment]
That page doesn't include https://github.com/exercism/todo or https://github.com/exercism/discussions

**Comment by kytrinyx** [comment]
I'm becoming increasingly skeptical of exercism/todo—I'm finding it very difficult to keep track of everything there. A better choice might be to regenerate the relevant issues in the repositories that they belong in.

We should definitely have a link to exercism/discussions; probably at the top.

**Comment by petertseng** [comment]
> A hacky way to do this with current resources may have been to create a separate org for the language tracks, but that comes with problems of its own (so... do track maintainers have to be added to multiple orgs? doh!)

Apparently this is now being considered at #103 . I'll talk about it there.
