### ISSUE TITLE
Portfolio Mode: Allow viewing all of a users submissions

### ISSUE THREAD

**Issue by wolverineks** [exercism/discussions#50]
It appears that a user cannot access a submitted solution if they themselves have not yet submitted a solution.

Would you consider allowing users to show off their "portfolio" of work to those that have no attempted all of the same exercises?

I believe this would increase the exposure of Exercism, and incentivize users to complete more exercises.

One possible mechanism could be a single, unique link, only visible on the user dashboard, which could be included in a resume, linkedin, github, email, etc...

**Comment by petertseng** [comment]
From http://exercism.io/account:

 By creating a "private share" url, you can share your complete profile with specific people, and they will be able to see all of your solutions, provided you share the link with them. And the good thing is that they don't need to be an Exercism user themselves.

**Comment by kytrinyx** [comment]
I'd love to make this more clear in the user interface. See https://github.com/exercism/discussions/issues/33

Also, I think that this will be much easier once we ship this: https://github.com/exercism/exercism.io/issues/2059
