### ISSUE TITLE
copy + placement re: "submit code that doesn't work" 

### ISSUE THREAD

**Issue by gusseting** [exercism/discussions#54]
As per #47, exercism needs to have copy on the site that it's possible to submit code that doesn't work, in order to see solutions from others and revisit the problem.

Suggested locations and **possible new copy in bold**:

- [x] http://exercism.io/how-it-works/newbie #2986
    - [x] Under the heading "How it Works: For New Developers":

        > Submit your solution using the command line. **It's possible to submit incomplete solutions; if you do, you'll then be able to see others solutions, which could assist in completing yours.**

    - [x] Under the heading "Working the Exercises":
       
       > Once you've gotten all of the tests passing, you're good to go. Submit the solution to the site using the CLI. **If you get stuck on a problem, it's possible to submit incomplete code.** Then check out other people's solutions and iterate/improve on your own. Re-submit a new iteration at any time.
- [x] http://exercism.io/how-it-works #2986
    - [x] Under the heading "How it Works: For Experienced Developers"

       > Your local computer: Download an exercise, write your solution locally, and submit it to the site. **It's possible to submit an incomplete solution so you can see how others have completed the exercise.**

As @IanWhitney has suggested in #47 , copy could also be in each README file. However, that would mean the same copy in a large amount of exercises, and I'd appreciate others feedback re: how appropriate it would be to have copy about submitting incomplete exercises in each README. Might there be a more simple solution?

**Comment by kytrinyx** [comment]
> Under the heading "How it Works: For New Developers":
> "Submit your solution using the command line. It's possible to submit incomplete solutions; if you do, you'll then be able to see others solutions, which could assist in completing yours."

Yes, I think this is a good idea. Maybe we could make it a bit more informal, something like:

_Submit your solution using the command line. If you get stuck, submit what you have and ask for help. You also get to see other people's solutions to the same problem, which could help you figure it out._

> If you get stuck on a problem, it's possible to submit incomplete code.

How about _If you get stuck on a problem, feel free to submit incomplete code._

I like the suggestion for the "How it Works: For Experienced Developers" page.

> copy could also be in each README file. However, that would mean the same copy in a large amount of exercises

Yeah, agreed that this is too much. That makes it hard to manage later, if we decide to tweak the language.

**Comment by gusseting** [comment]
As discussed with @kytrinyx  + my coach jo, there's further work to be done in this issue:
as per @IanWhitney's recommendation, I'll be adding copy to each .README file, via the the API at: https://github.com/exercism/x-api/blob/master/lib/xapi/implementation.rb#L35

I'm not sure what copy is already there, but am planning on adding: "It's possible to submit an incomplete solution so you can see how others have completed the exercise."

**Comment by kytrinyx** [comment]
This sounds great, @gusseting. We'll continue the conversation in your PR there.
