### ISSUE TITLE
What if you don't want comments?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#55]
Comment from a person who is going through all the exercises in a particular language:

> I don't want comments. At all. I'm just exploring, going through the language. I don't want to address other people's comments. I'd be willing to go comment on other people's stuff, but I don't want them to get defensive, and I don't want them to come comment on my stuff. I'm perfectly happy to have people look at my stuff.

There really are different approaches to using Exercism, I think we should explore this more.

**Comment by kotp** [comment]
The simple solution is to submit and then comment on the submission that no comments are needed/wanted.

The other, is to archive.  I think the archive now signals mostly that comments are not being sought after.

This could be stated clearly, or a flag given, that indicates this as well, or even disables the comment area.

**Comment by Insti** [comment]
An indication of what people want in their feedback would be helpful.  
I usually do this by commenting my own solutions, but maybe it would be good if there was some kind of automatic 'profile/signature' comment that could be added to all solutions:  

"Total beginner, I've no idea what I'm doing, please help!"
"Intermediate programmer, no feedback please, I'm embarrassed."
"Experienced programmer, learning a new language, idiomatic feedback needed."
"Pro, golf for fun, help make this shorter!"

**Comment by jtigger** [comment]
I can understand the notion of "just wanting to solve the problems" but ... and I don't want to come across as closed-minded ... but isn't that antithetical to the value that Exercism brings?

I'd vote down the idea of putting effort into features that disable conversation altogether.  I'm absolutely in support of controls that help users manage their experience (e.g. exercism/exercism.io#3180) but these help address corner cases.

**Comment by dvberkel** [comment]
I don't think that this would be antithetical to the value of Exercism. It's slogan is still _level up your programming skills_. This can be done by various means, some of them offered by the exercism.

I think that comments could be a valuable source of feedback, but one has to be ready for it. Clearly somebody isn't ready, for what ever reason. If this is off-putting for some, I think we cut short a interesting learning path for those.

So I am in favour of exploring

**Comment by kytrinyx** [comment]
I'm a little bit curious why someone would post their solutions if they didn't want feedback. Why not just solve them locally and not post them?

**Comment by kotp** [comment]
The easy answer is "humans".  We know they do crazy things.

**Comment by kytrinyx** [comment]
Fair enough @kotp :-) That said, I'd still like to know what the motivation is, since having an idea about that could give us a better idea of how (or whether) to tackle this.

**Comment by kotp** [comment]
Yeah, you got me thinking of the "Why".  Most scenarios I can think of have easier solutions... 

* Showing code to mentees -> Gists
* Asking questions -> Well, feedback on exercism
* Solving problems to learn -> local solution with no share

**Comment by kotp** [comment]
I noticed the wording in the issue first post... did you ask the person that you got this information from that "Why?" question?

**Comment by kytrinyx** [comment]
Yeah, I know why they don't want comments. Their learning is very self-driven.

I realized now that the only reason I can think of to post code even if you don't want a code review is to be able to browse other people's solutions.

The workaround here is to archive immediately. It won't show up in the activity streams. People could conceivable find your profile and click through, but it would be fairly unlikely.

This person did not suggest that we add functionality for it, I just wanted to raise the question in case there was something that I had missed.

Another person I talked to recently stopped using Exercism because of the comments. Not because they didn't want comments, but because the commenters were just plain wrong. This person did not have any particular interest in starting a conversation with (or mentoring) people who had completely missed the point.

Now, having seen more discussion, I think the answer is: "I can see why people wouldn't want comments" and also "we probably shouldn't build this into the platform".

**Comment by kotp** [comment]
I also do archive.  Sometimes bringing it back out of archive when ready for feedback again.  I also do ask when their exercise is archived if they would like to receive comments, since that is one of the indicators to me that they don't need/want the noise.

And yes, push back on advice well intentioned and wrong brings some civil responsibility that may not be wanted.  I can see that.  I think we have partial, or at least intent revealing, functionality already, though not a full out "No, Donny you can't comment, there is no way to."

**Comment by kytrinyx** [comment]
This is being tracked as part of the nextercism redesign. I'm going to go ahead and close it.
