### ISSUE TITLE
OK if I remove myself from the Ruby team?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#57]
@exercism/ruby I'm so incredibly delighted and grateful at the excellent collaboration that is going on in Ruby, and now that there are several people who are active on a regular basis, it doesn't feel like the Ruby track is in danger of being abandoned or ignored.

Would you all be cool with me officially resigning as maintainer of the Ruby track? I'll still keep an eye on what's going on, and of course you can always call me up with an `@`-mention if you want my eyes on something in particular.

Somewhat related to https://github.com/exercism/discussions/issues/3

PS: @markijbema if you've gotten busy and want to officially move on there should be absolutely no guilt involved :heart:

**Comment by markijbema** [comment]
Heh, you're right, maybe I should. I really like exercism, but due to changed circumstances I don't currently have time to participate, let alone maintain. So I think I'll follow your lead on this one.

**Comment by markijbema** [comment]
Which does beg the question; what is the state of the coffeescript tag; since I have no time, and I'm the only team member?

**Comment by Insti** [comment]
Also related #36 

So, go, fly, be free!

Your time will certainly be well spent on the higher level details of Exercism and I'm sure we can keep the Ruby track on track. Thanks for everything you've done.

**Comment by kytrinyx** [comment]
> what is the state of the coffeescript tag

It's pretty much be orphaned, but we don't have a whole lot of open issues/PRs either. Nor submissions. Nor responses.

http://exercism.io/stats/coffeescript

Finding new maintainers and improving the experience for track maintainers is one of the things I am planning on spending a fair amount of time working on in the next few months, so whether or not you're here, it's on my list to figure out how to get a minimum of 2 ideally 3 or 4 active and enthusiastic maintainers on each track that doesn't have someone checking in regularly.

**Comment by kytrinyx** [comment]
Also: Thanks y'all!!! :heart:

**Comment by Insti** [comment]
> http://exercism.io/stats/coffeescript

Exercism has a LOT of good features that are hard to discover :crying_cat_face:

**Comment by kytrinyx** [comment]
Yeah, I know. I'm sorry. I've been having a lot of trouble keeping on top of things over the past three years. That combined with the fact that I am not a UX person, and we so rarely get contributions from people who understand UX. It makes in really difficult to figure out how to improve this.
