### ISSUE TITLE
Tag each language repo with link to http://exercism.io/languages/<language>

### ISSUE THREAD

**Issue by masters3d** [exercism/discussions#58]
![image](https://cloud.githubusercontent.com/assets/6539412/17218814/06ce8f2a-549e-11e6-8aed-04dff575028b.png)

**Comment by Insti** [comment]
Why is this useful?

**Comment by masters3d** [comment]
Shortcut to the project page for that repo.
When I am trying to have people help with an implementation of a new problem, I want to send them the github link but with out previous knowledge it is hard to know what the repo is about.

**Comment by Insti** [comment]
Thanks. Sounds like a good idea then!

**Comment by kytrinyx** [comment]
Agreed, this would be helpful. We can use [blazon](https://github.com/exercism/blazon) to ask track maintainers to make the change.

@masters3d @Insti would one of you confirm that you're allowed to make the change on a repository that you have commit access to?

Here's my first draft for the blazon issue:

```
Add link to exercism.io/languages/:track_id in repository header

The repository header can contain a description and a URL. Currently most tracks contain a description that is something like _Exercism exercises in $LANGUAGE_.

It would be useful to also include a link to the main page for the language track on Exercism, as this can provide useful context when trying to direct people to the right place, or help them contribute an implementation to a track.
```

**Comment by masters3d** [comment]
I don't have access to setting so I think so.

**Comment by Insti** [comment]
I do **not** have access to edit the repository title on exercism/xruby

**Comment by kytrinyx** [comment]
Dang. In that case it's something only organization owners can do.

I've got this :)

**Comment by kytrinyx** [comment]
There are two tasks here:

- [ ] write a script to update all existing language tracks
- [ ] add this automation to the bootstrap script in request-new-language-tracks

**Comment by kytrinyx** [comment]
This is done.
