### ISSUE TITLE
Github's new web Squash Commits 

### ISSUE THREAD

**Issue by masters3d** [exercism/discussions#6]
Can we turn this on the repos? 
https://github.com/blog/2141-squash-your-commits

I don't see any drawbacks but if any please let me know.

**Comment by masters3d** [comment]
nvm, it seems to be on at least for xswift. Closing.

**Comment by masters3d** [comment]
Okay so, I don't see the squash option to merge & squash anymore
@kytrinyx Do you know is this is something that needs to be *turn* on?

**Comment by masters3d** [comment]
never mind. Grrrr I really don't like this UI.You have to click to get the options. 
![image](https://cloud.githubusercontent.com/assets/6539412/14340096/b8aa7006-fc38-11e5-8f89-7c481219bac6.png)

**Comment by kytrinyx** [comment]
Yeah, apparently it's on by default. I'm not quite comfortable with the UI yet, either, but I do like having the option.

**Comment by masters3d** [comment]
:)
![image](https://cloud.githubusercontent.com/assets/6539412/14357037/f4f76998-fc9b-11e5-93f8-0a274dba54b6.png)
