### ISSUE TITLE
How To Encourage Contributions To Exercism

### ISSUE THREAD

**Issue by scottwhudson** [exercism/discussions#61]
Branching off from https://github.com/exercism/todo/issues/174

While working on the above issue, we discussed ways to encourage developer contribution to Exercism through the web app, and how it might work on a  generic level.  This was a basic mock-up I did in the browser that would accommodate a track's [contribute page](http://exercism.io/languages/ruby/contribute) (using ruby as an example)

<img width="994" alt="screen shot 2016-07-26 at 4 35 33 pm" src="https://cloud.githubusercontent.com/assets/6406203/17156358/0943525e-534f-11e6-96b6-015985a0ec75.png">

The basic idea is to include a button for unimplemented exercises that would give the user instructions to contribute if they chose. Something like this could also be used to help contribute to implemented but incomplete exercises (especially for those JSON test outputs).  The ultimate goal here is to make the pending workload more visible and (hopefully) accessible.

**Comment by kytrinyx** [comment]
How about instead of having them under the "Available" heading (they're not really available yet) we could have a separate heading?

Or perhaps at the very end of that section we can have some copy that encourages people to help port exercises, and link to the page that has all the things to port: `http://exercism.io/languages/:track_id/contribute`?

**Comment by troubalex** [comment]
@kytrinyx 
> How about instead of having them under the "Available" heading (they're not really available yet) we could have a separate heading?

Wouldn't they fit neatly under the "Contribute to Ruby on Exercism" section? 

The list of unimplemented exercises is linked from there, but it's probably better if this kind of thing is really in people's faces, as @scottwhudson said.

**Comment by kytrinyx** [comment]
That sounds like a good approach, @troubalex

**Comment by kytrinyx** [comment]
This was implemented, and we now have a separate heading/page for them. Thanks for bringing it up, @scottwhudson!
