### ISSUE TITLE
Add a "Next Problem" button?

### ISSUE THREAD

**Issue by cmccandless** [exercism/discussions#62]
I just completed my first Exercism.io track (C#), and it was overall a great experience. It would be nice to have a button to go to the Readme page for the next problem, especially since the dynamic nature of the site breaks browsers' "Back" functionality: (Example: 
1. Go to a language track on Exercism.io
2. Click "Available Exercises"
3. Scroll down a bit and select an exercise
4. Click "README"
5. Click browser "Back" button
6. "About track" section loads instead of "Available Exercises")

I did see that there is current discussion about redesigning the site already. I suggest that this could be implemented with that new design.

**Comment by kytrinyx** [comment]
Redesigning the site will not be a complete site overhaul as such, but rather looking at one aspect at a time (either a specific feature such as the solution page, or one aspect of the design, such as fonts).

> the dynamic nature of the site breaks browsers' "Back" functionality

Yeah, I used the default twitter bootstrap for that (I'm not a front-end developer) and it absolutely sucks to not be able to link to separate parts of that page.

I like the idea of having a "next"/"previous" button when browsing the available exercises.

**Comment by codingthat** [comment]
> I like the idea of having a "next"/"previous" button when browsing the available exercises.

Me too.  Am I missing something, or is there currently no way to view the readme of the exercise you're currently working on until after you've submitted it?  (I.e. aside from looking at the markdown locally.)  It seems that fetching the next one doesn't cause it to appear at http://exercism.io/tracks/clojure/exercises or http://exercism.io/tracks/clojure/my_solutions or anywhere else that I can see, until first submission.

**Comment by kytrinyx** [comment]
> Am I missing something, or is there currently no way to view the readme of the exercise you're currently working on until after you've submitted it?

You have access to all the readmes/test suites at all times. E.g. http://exercism.io/exercises/fsharp/pascals-triangle/readme

Fetching an exercise doesn't put it in any of your lists though. You'd have to navigate to it via http://exercism.io/languages > http://exercism.io/languages/clojure > http://exercism.io/languages/clojure/exercises

**Comment by codingthat** [comment]
Somehow I totally missed that.  Thanks!

**Comment by kytrinyx** [comment]
> Somehow I totally missed that. Thanks!

Nothing is discoverable on Exercism at the moment, unfortunately. We're working on fixing this (see https://github.com/exercism/discussions/issues/113 for details).

**Comment by kytrinyx** [comment]
We're doing a complete redesign, and rethinking this entire user experience. See #113 and #154 for details. I'm going to go ahead and close this in favor of that process.
