### ISSUE TITLE
Docs—can we use them for both the site and the exercise READMEs?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#63]
Right now each language track on exercism has a `docs/` directory, which contains

```
docs/
├── ABOUT.md
├── HELLO.md
├── INSTALLATION.md
├── LEARNING.md
├── RESOURCES.md
├── TESTS.md
├── TOOLS.md
└── img/
    ├──something.png
    └── something-else.png
```

This is used on the `exercism.io/languages/:track_id` page.

I'd love to find a way to break this up in a way that lets us have all the verbose information we want on the site, and also have two bits of stand-alone, minimal data that could be included in each exercise README:
- How to install the test dependencies
- How to run the tests (generically)

e.g. For Ruby:
- You need minitest >= v5 `gem install minitest`
- You run the tests by invoking ruby and the name of the test file `ruby path/to/exercise_test.rb`

@exercism/track-maintainers What do you think?

**Comment by kotp** [comment]
Right now, I don't see much "common" in the xruby/docs or xgo/docs that would support this very well.  Other than the file names, the documentation itself seems to be very track specific.

Is there something you had in mind that you would like to see as 'common' to all tracks on that page?

**Comment by kytrinyx** [comment]
I don't mean generically / common to all the tracks.

I mean, can we have the minimal version that would included for the README of every exercise in that track?

**Comment by kotp** [comment]
So as few files as possible as concise, but informative as possible?

**Comment by kytrinyx** [comment]
I don't know. I want to be able to include the "gem install minitest" and the "ruby path/to/file_test.rb" equivalents other places (such as the exercise README), but all of the existing information is also useful (on the site).

I want to eat my cake and have it too.

I don't see an obvious way of doing this, but I'm hoping someone else has some good ideas.

**Comment by petertseng** [comment]
It seems there are a few components to what's desired:

# 1. Track-specific information that automatically gets included in each README.

> I want to be able to include the "gem install minitest" and the "ruby path/to/file_test.rb" equivalents other places (such as the exercise README)

Were there any other places you wanted this as well?

Is there something in this portion that `SETUP.md` does not already provide? `SETUP.md` for a track is already being provided with each README: https://github.com/exercism/x-api/blob/78ce4b95db5d1c97520145cdeef7f8ce49f3041f/lib/xapi/implementation.rb#L100

If not, does there need to be a new file under `docs/`?

* all of the existing information is also useful (on the site).

This sounds like asking for deduplication and/or fewer docs.

For example, what's in common between SETUP.md and TESTING.md, can we extract the common bits into some third file? But that means there would be another file, and the relationship between our various `.md` files would get harder to understand. So the benefit would have to be substantial.

Another way to do this is if for our markdown files can specify "interpolate the contents of this other markdown file here", which seems a bit complicated (unless markdown... already supports that?!)

**Comment by kytrinyx** [comment]
> Were there any other places you wanted this as well?

Yeah, I'm working on some tools that would turn the exercises into high school classroom assignments. They will have a reference to the relevant exercism track track, but should not talk about submitting etc.

Also, it might be nice to have it on some of the exploration pages as people look around the site and figure out how to get started.

But then again, a better onboarding would obviate the need for that.

**Comment by kytrinyx** [comment]
> Is there something in this portion that SETUP.md does not already provide?

The SETUP.md is too much, unless we can specifically pare that down to always only include these two things, in which case it would be perfect.

> the relationship between our various .md files would get harder to understand. So the benefit would have to be substantial.

Yeah, I don't want it to get too complicated. And we may find a way to simplify further—all of this has sort of grown organically, and it might be that taking a step back we could find a simplification.

> Another way to do this is if for our markdown files can specify "interpolate the contents of this other markdown file here"

Not that I know of.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, as the problem I was exploring wasn't really clear, and I think our current approach is good for now.
