### ISSUE TITLE
What do the in-progress / ready labels help with?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#66]
@Insti I've noticed that you've added in-progress and ready labels? Can you say a little bit about why you did this and how they're helping?

**Comment by Insti** [comment]
These labels apply to pull requests.

`in progress` - This means that the PR is actively being worked on. Ideally this would be the natural state for all PR's but this is not always the case. Some become idle or show no signs of starting. (WIPs on the xruby language track are an example of this.)

`ready` - This means that the PR is considered completed and ready to be merged pending you looking through it to give the final OK. It means that someone other than the author has looked through it closely enough to consider it in a good enough state to merge.

Once PRs are merged the labels are removed.

The theory is that if you only have a short time available, you can look through the 'ready's and find patches that should be straightforward to merge. And I don't spend my time re-checking the status of PR's that are ready to go.

**Comment by kytrinyx** [comment]
OK, cool. This doesn't quite fit into my workflow in any way, but if it helps you not look at things twice, that's awesome.
