### ISSUE TITLE
User Experience - Notifications

### ISSUE THREAD

**Issue by gusseting** [exercism/discussions#68]
![image](https://cloud.githubusercontent.com/assets/540264/17721235/1c0249da-646c-11e6-8500-67ecfa7d0ae4.png)
(This is a screenshot of @kytrinyx's notifications)

Here’s what it contains:

Notifications:
- submissions
- comments
- mentions

Content:
- Person
- Date
- Time
- Problem
- Language
- Language Icon

It would be great to clean up notifications so that it looks simpler, and people have the information that they need. 
Starting point: What could be removed?
Could we start out with read/unread, and remove dates/times from this panel?

What signposts might help?
Could it be useful to color code submissions/comments/mentions?

Adding to the master list of User Experience: https://github.com/exercism/discussions/issues/34

**Comment by troubalex** [comment]
👍 for simplification.

A couple of suggestions:
+ The timestamp could be down prioritised in color and moved below the main entry, it _probably_ doesn't need to be as precise either
+ The list could be grouped by type: mentions, submissions, comments, or by language
+ The complete line should probably be clickable and take people to the specific item
+ The language icons could be down prioritised as well, or dropped if the list is grouped by language

**Comment by troubalex** [comment]
Thinking about this again, it probably makes most sense to group by language, similar to how Github solves this with grouping by repo. 

If this sounds like a good idea, I can open an issue in the exercism.io repo. :)

**Comment by kytrinyx** [comment]
Yes, this makes a lot of sense, @troubalex.

**Comment by brandondees** [comment]
Gut reaction, I think that having an icon on both ends of the line creates undue visual complexity and makes vertical scanning less ergonomic. I'd probably experiment with moving the language icon to be immediately adjacent to the user avatar (not sure right or left side, worth playing with both to get a feel for it).

Taking a second closer look, I realized that there is sometimes a 3rd party involved, but they're mentioned only by username, no avatar (is the name a link at least?). Maybe the whole "context of the activity" section on the left could be the actor's avatar, then the language icon, then the related 3rd party avatar if applicable. I think that would make it much easier to parse the list for the person/track combo you may be most interested in catching up with, without needing to deal with sorting/filtering controls yet.

Last thought, I might also experiment with getting that date/time stuff more out of the way. It's a helpful detail to have access to but not likely to be any of the primary things a person is searching for, so it should be de-emphasized in both its position in the information hierarchy as well as size/visual intrusiveness. I'd try using a [time element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time) to conceal some of the granular detail and summarize it with the more human readable format like '3 days ago', 'several months ago' etc. and also align the element to the right end of the column, which can both restore some visual structure and get the least significant detail further out of the way of the thing users are most likely there to read first.

**Comment by kytrinyx** [comment]
These are all great suggestions, @brandondees.

I also realized that since we added the "reply-to" we now typically get two notifications for each comment. One for the mention (from the reply-to) and one for the comment itself. That seems excessive.

**Comment by brandondees** [comment]
@kytrinyx that probably _is_ excessive, haha. At least they get cleared properly when viewing the thread.

**Comment by kytrinyx** [comment]
We're tracking this as part of the nextercism prototype. I'm going to go ahead and close this. Thanks all!
