### ISSUE TITLE
Sort and filter activity streams

### ISSUE THREAD

**Issue by blunckr** [exercism/discussions#69]
As far as I can tell, you can't see how many likes a solution has without clicking on it. it would be nice to see that in the list, and also to sort by most likes or comments.

**Comment by kytrinyx** [comment]
I think this goes back to the more general topic of needing to filter the activity streams by various criteria. I know this has come up a number of times, but I don't think we've collected all those discussions in the same place. Maybe we could do that here.

**Comment by kytrinyx** [comment]
Here's one: filter already read submissions in the activity stream: exercism/exercism.io#2945

**Comment by Cohen-Carlisle** [comment]
Doing a text search on solutions was requested on issue https://github.com/exercism/discussions/issues/46.
@kotp said:
> For instance, perhaps I want to pull solutions that use a specific method, for examples of how others have used it.

On the same issue, solution tagging was requested by @clarkburbidge.

**Comment by aklap** [comment]
I would also like to filter the solutions in the Activity Stream based on number of comments.

Some solutions have interesting discussions between people on style and optimization but they can be buried many pages back making it hard to find them. I'm not entirely sure how that would work or what the layout would be.

**Comment by kytrinyx** [comment]
@aklap Agreed—I'd love to be able to find both solutions without comments, and solutions where it's clear that discussion is happening.

**Comment by kytrinyx** [comment]
We're tracking this as part of the nextercism / redesign work. I'm going to go ahead and close this.
