### ISSUE TITLE
Consistency in language tracks readme for help and further information

### ISSUE THREAD

**Issue by ghost** [exercism/discussions#70]
How can we make the content in language Readme files less confusing?
What seems to be happening is that we're linking to the language overview page (aka about language), and calling it the exercism help page, or the help page.
For example:

> **Ruby:**
> For installation and learning resources, refer to the [exercism help page](http://exercism.io/languages/ruby).

I'd be assuming that exercism help would be the [help page in the footer](http://exercism.io/help).

I'm wondering if it's going to be more helpful to everyone to have a standard piece of copy in each language along the lines of:

> "For language installation, learning resources and help, see `[about language](http://exercism.io/languages/language)`. 

Would it be helpful for track maintainers to discuss what that generic copy should be?
I wasn't sure if every language needed installation instructions.
@Insti might you have suggestions?

Here's examples of what we currently have in each languages readme:

**Python:**
For more detailed information about running tests, code style and linting, please see the help page.
http://exercism.io/languages/python

**Java:**
No mention of the word "help" in the problem.

**Javascript:**
No mention of the word "help" in the problem.

**Rust:**
Refer to the exercism help page for Rust installation and learning resources.
http://exercism.io/languages/rust

**Comment by Insti** [comment]
I think it's fine if languages maintain their own documentation including links to more help.
This text is probably not reviewed often, so it's good you're looking at it.

The text you've quoted comes from the [SETUP.md](https://github.com/exercism/xruby/blob/master/SETUP.md) file in the [x]language repository. (Please make a pull request if you have any changes.)

It could also be good to add suggestions/improve the documentation in the x-common contributing guide which has a section on [Updating Language-Specific Additions](https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#updating-language-specific-additions)

**Comment by kytrinyx** [comment]
Thanks for bringing this up. I think more standardization here would be a good thing, and that we should discuss what that should look like.

We could have something completely identical for all the languages that lives in x-api rather than in the individual repositories. That would ensure that 

1. it's the same everywhere
1. that new tracks get some level of detail there
1. it will always be up to date

**Comment by kytrinyx** [comment]
We've completely reworked the exercise READMEs so that each language can lean on shared documentation, but veer from that and customize where necessary.

Please see the documentation about this at: https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/readmes.md
