### ISSUE TITLE
Add "friend" feature

### ISSUE THREAD

**Issue by officiallyandy** [exercism/discussions#71]
Allow exercism to track a friend's list and "watch" them to be notified of new work they done. This is inspired by our company trying it out as a skill building tool but needing to track users manually.

**Comment by Insti** [comment]
It is possible to create a 'team' that contains you and your friend. Would this be helpful?

**Comment by ryanplusplus** [comment]
My company uses a team for this.

**Comment by officiallyandy** [comment]
How do I do this? There may be about 30 of us.

Best Regards,
Andy Nunez

**Comment by Insti** [comment]
Start here: http://exercism.io/teams/new

Feedback / Pull Requests about how to make the process better and improve the documentation are encouraged!

**Comment by kytrinyx** [comment]
Thanks for the suggestion @officiallyandy! As others have mentioned, this is what teams are for. At the moment the teams features are a bit hidden. @bernardoamc is working on some features that will help make this easier to discover.

I'm going to close this, but do feel free to open issues and pull requests if you run into trouble. :heart:
