### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by bernardoamc** [exercism/discussions#74]
Today I was asked which browser versions Exercism support and I actually don't know the answer. Do we know which browser versions we currently support or want to support? And do we have any data on the browser versions used by Exercism users?

Sorry if this is documented somewhere already. :)

**Comment by kytrinyx** [comment]
We have the data, but I'm not very good at looking at it.

I want to suggest that we should not support browsers that their creators no longer support (so new versions of IE, yes, old versions of IE that are no longer supported by Microsoft, no).

@bernardoamc I will give you access to the analytics data so you can take a look at this.

**Comment by bernardoamc** [comment]
That's awesome @kytrinyx, thanks!

I'm going to evaluate the data and generate some charts. I will also add the browser versions that we currently support in the contributing guide.

> I want to suggest that we should not support browsers that their creators no longer support (so new versions of IE, yes, old versions of IE that are no longer supported by Microsoft, no).

Totally agree!

**Comment by kytrinyx** [comment]
I'm going to close this. The reimplementation of Exercism is going to be a lot more standardized and will (naturally) tend to work in more browsers.
