### ISSUE TITLE
Hacktoberfest (October 2016)

### ISSUE THREAD

**Issue by Insti** [exercism/discussions#76]
GitHub and DigitalOcean are running [Hacktoberfest](https://github.com/blog/2260-hacktoberfest-is-back) again this year.

> Apply the label "Hacktoberfest" to issues in your GitHub-hosted project that are ready for new contributors to work on.

[xrust seems to have already started](https://github.com/exercism/xrust/issues?q=is%3Aissue+is%3Aopen+label%3AHacktoberfest)

Is this something Exercism wants to try harder to be a part of?

Adding the 'hacktoberfest' label to issues that area already labelled as 'good first patch' would be a good start.

Any other suggestions for things we can do to encourage contributions?

**Comment by Insti** [comment]
How do we get Exercism into the 'Featured projects' list?

**Comment by IanWhitney** [comment]
I looked a little but didn't see a way to highlight Exercism short of emailing emailing them.

Am I super excited about getting that shirt? Yes.

**Comment by kytrinyx** [comment]
> I looked a little but didn't see a way to highlight Exercism short of emailing them.

I'm tangentially involved in this and can talk to them about getting Exercism highlighted. I would want to be certain that we have a way to give people well-curated issues, though. Maybe we can create a /hacktoberfest page on exercism.io that points people to tracks that we know are actively maintained, and issues that have the "good first patch" mark on them.

**Comment by petertseng** [comment]
Okay, I decided to bite. I applied the Hacktoberfest label to [some xgo issues](https://github.com/exercism/xgo/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Ahacktoberfest).

Now, I don't know if it's because of that, or some other factors, but contributions have come in for issues not touched for months, which is interesting.

**Comment by Insti** [comment]
Hacktoberfest is over now.
See you again in 2017!

**Comment by kotp** [comment]
Let's set our calendars for September to get this more organized next year.

**Comment by jtigger** [comment]
Keep or remove the [Hacktoberfest labels on issues](https://github.com/search?q=org%3Aexercism+label%3Ahacktoberfest)?

**Comment by Insti** [comment]
My preference would be to leave them on closed tasks but take them off open ones.

**Comment by jtigger** [comment]
done.
