### ISSUE TITLE
unable to submit 

### ISSUE THREAD

**Issue by AroniasPrenovost** [exercism/discussions#77]
Hi there, first I want to say thank you for building this awesome tool. I'm really excited to get into it all weekend! 

My issue is that I made an exercism_io folder on the desktop 

/Users/aronprenovost/Desktop/exercism_io 

but i can't seem to submit successfully. I've read that I need to configure my JSON file but i can't find it, either in the original exercism folder created in the root path of /aronprenovost

What confuses me is that within /aronprenovost/Desktop/exercism_io, I can run 
$exercise fetch "language" hello-world successfully and get the file, but if i was to write 

$ exercism submit aronprenovost/Desktop/exercism/javascript/hello-world/hello-world.js 

it returns 

2016/09/30 06:55:06 Please specify each file that should be submitted, e.g. `exercism submit file1 file2 file3`

I've tried a ton of different combinations so I wasn't sure it's a syntax error. If i run 

exercism configure --key=d5b8******

i keep getting:

Macintosh-2:~ aronprenovost$ exercism configure --key=d5b8******
Configuration written to /Users/aronprenovost/.exercism.json

  --key=d5b8******
  --dir=/Users/aronprenovost/Desktop/exercism_io
  --host=http://exercism.io
  --api=http://x.exercism.io

which makes me think the JSON file is in the wrong spot.

Any advice is much appreciated!

**Comment by jtigger** [comment]
*(@AroniasPrenovost I redacted your API key)*

**Comment by jtigger** [comment]
Delighted that you're excited, @AroniasPrenovost!

There are two bits that need aligning:

1.  the path of the the `submit` command doesn't match with the "Exercises Directory" path.  It should be `exercism_io` not `exercism`.
2. the path supplied to the `submit` command should be relative to the current working directory (which I've inferred is `/Users/aronprenovost/Desktop/exercism_io`)

Try this:

```
$ cd /Users/aronprenovost/Desktop/exercism_io/javascript/hello-world
$ exercism submit hello-world.js
```

**Comment by jtigger** [comment]
Note that we do have a support chat room too: https://gitter.im/exercism/support

You can continue working through this issue and/or use that chat room.

**Comment by AroniasPrenovost** [comment]
Awesome, Once I get back to my home computer I'll try that out. Thank you for showing me the chat room as well.

Best,
Aron
