### ISSUE TITLE
What topics does Kindergarten Garden teach?

### ISSUE THREAD

**Issue by IanWhitney** [exercism/discussions#78]
I'm working on a PR to provide a standard test suite for Kindergarten Garden. As part of this, I'm trying to figure out what this exercise is trying to teach, as that will help me figure out what the tests should be.

Looking at the current implementations, I'm having a hard time figuring out the problem's goal. Some implementations feature the ability to use the default kid names or provide your own names ([C# is a pretty common approach](https://github.com/exercism/xcsharp/blob/f8c033b450f51c4ff4bd7cbc6063722103f7748c/exercises/kindergarten-garden/KinderGartenGardenTest.cs). Others only let you use the kids named in the story ([lua](https://github.com/exercism/xlua/blob/8786793744ade872a5a4bcbbe2ffd376ec91b6ee/exercises/kindergarten-garden/kindergarten-garden_spec.lua)). And others feature metaprogramming, having their students implement student-specific methods ([Ruby](https://github.com/exercism/xruby/blob/7069d234c48f36219c44b2a6d13b344fdf2505b8/exercises/kindergarten-garden/kindergarten_garden_test.rb)).

As written, the problem seems like it could be covered by just a few tests:
- Test a garden with 0 plants
- Test a garden with 4 plants
- Test a full garden

Maybe you throw in a test or two to capture edge cases (e.g., too many plants or not enough plants)

Are there deeper or more interesting concepts in the problem that the test suite could draw out? What do you think the problem should focus on?

**Comment by kytrinyx** [comment]
For the record, I can't remember why I made this, only that it was in response to observing a new programmer who had trouble with a concept. But what that concept is... that's really hard to say!

**Comment by Insti** [comment]
For reference: [Kindergarten Garden Readme](https://github.com/exercism/x-common/blob/master/exercises/kindergarten-garden/description.md)

**Comment by IanWhitney** [comment]
I was looking for more details about the concepts being taught, not the parameters of the exercise.

For those who have implemented this, or done the exercise, any thoughts on the topics it teaches?

**Comment by Insti** [comment]
The reference was for people like me reading the issue who had no idea what the exercise was about.

**Comment by sguermond** [comment]
Indexing/string slicing?

**Comment by unmanbearpig** [comment]
Maybe it's good for teaching how `zip` might be useful?

**Comment by petertseng** [comment]
Did exercise today. Used `zip`, so I confirm the above.

**Comment by petertseng** [comment]
Of course, not everyone will use `zip`, but no matter how you achieve it, the idea of iterating through two iterables in lock-step, as you would with hamming or (in the case of more than two iterables) ocr-numbers.

**Comment by kytrinyx** [comment]
This seems to have gotten resolved in the merged PR above :) Closing
