### ISSUE TITLE
Run continuous integration on pull requests

### ISSUE THREAD

**Issue by dvberkel** [exercism/discussions#79]
@stevejb71 posted an interesting suggestion in the [OCaml track](https://github.com/exercism/xocaml/issues/65#issuecomment-250972880). The expectation was that a continuous integration test would run on a pull request to see if anything is broken.

I really liked this idea and searched in the discussions if this was suggested already. Unfortunately I couldn't find an earlier reference.

I am opening this discussion to see what others are thinking of the idea and maybe how to achieve it.

**Comment by mhelmetag** [comment]
All the tracks that I've used have their test suites run on a PR (namely Ruby, Elixir, Go and Crystal). Some even check formatting and/or styling.

I'm not familiar with testing in OCaml but you could poke around some other language tracks to see how they do it. You can usually see how the testing suite is run in a track's `travis.yml` file.

**Comment by kytrinyx** [comment]
We have started opening an issue when launching a new track called "Test the tests" (I couldn't get the search narrowed down quite far enough, but this shows some of the issues: https://github.com/search?q=org%3Aexercism+%22test+the+tests%22&type=Issues)

In some language tracks it's harder than others to implement this. I've created a gist with all the current .travis.yml files so you can take a look.

https://gist.github.com/ee2553c2153ebbfe044203381639260e

**Comment by petertseng** [comment]
I did remember an earlier discussion of https://github.com/exercism/x-common/issues/174 - in there I discussed some specific examples. The short is: Yup, the tracks that I work with do this, so it seems a good idea!

**Comment by dvberkel** [comment]
Thanks for all the pointers!

**Comment by jtigger** [comment]
BTW, the Java track [has implemented](https://github.com/exercism/xjava/issues/83) both a test-of-the-tests **and** [a full journey test](https://github.com/exercism/xjava/blob/master/bin/journey-test.sh) wherein we stand-up x-api, install the CLI, fetch each of the exercises and "solve" them by copying over the example.

Not only has this significantly reduced the effort required to review submissions, but it catches most likely regressions.

**Comment by kytrinyx** [comment]
@jtigger that is brilliant. I'm going to add this as one of the suggested things we do for each track.

**Comment by jtigger** [comment]
Being mindful not to violate YAGNI, that script can be made more general and be suitable for all tracks.  Off the bat, it would be a minor tweak to get it working for @exercism/kotlin.

**Comment by kytrinyx** [comment]
> Being mindful not to violate YAGNI, that script can be made more general and be suitable for all tracks.

The tricky thing is that we'd need both the original language environment and a java environment on Travis.

**Comment by jtigger** [comment]
In fact, it's that we'd need the original language environment as a Ruby environment (to fire-up x-api, on the CI box).  The part that's Java-specific can be externalized and "injected" per track.

**Comment by kytrinyx** [comment]
> Ruby environment

D'oh. Of course. Which isn't any better :)

Hm. It's terribly tempting to rewrite everything in Go so we can use a static binary. But then again, there are such things as dayjobs and priorities that would prevent us from doing that offhand.

**Comment by jtigger** [comment]
ha!

In fact, it *is* better on Travis: it comes with rvm.  Here's the trimmed version of the xjava/.travis.yml

```
---
language: java
...
before_install:
  - rvm install 2.2.5
  - rvm use 2.2.5
...
```
So, there's "original track language" at the top ([if available](https://docs.travis-ci.com/user/languages/)) and then the `rvm` calls for the ruby install... away you go...

**Comment by kytrinyx** [comment]
OK, now that's pretty cool!

I'd be perfectly willing to have the first version _only_ be available on travis if you don't happen to have a ruby environment locally.

Would you put a summary of this into a new issue in https://github.com/exercism/discussions/issues so that we can hash out a plan for how to potentially document this and figure out what would be necessary to implement it across all of the tracks?
