### ISSUE TITLE
Reset Rubocop on exercism/exercism.io to zero

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#80]
We originally added rubocop to the exercism/exercism.io codebase in hopes that we would start converging on a cleaner codebase.

Instead what happened was that we started blocking PRs for arbitrary style reasons.

This has been painful and frustration.

There are two things going on here, I think.
1. We introduced a bunch of rules that aren't necessarily meaningful to us without discussing which ones we actually care about. This means that we have PRs that fail for reasons that are pretty arbitrary.
2. We have _much_ bigger problems than syntactic consistency. Running rubocop has caused us to nitpick about things we don't actually care a lot about, while not actually making the code better in any noticeable way. This is like shaving off nanoseconds on an hour-long test suite that is doing expensive operations that take several seconds each.

In principle I'm all for having a comprehensive and strictly enforced style, since this means that contributions from diverse contributors will look roughly the same. But I believe that a enforcing large set of fairly arbitrary rules _right now_ is counter-productive.

I'd like to arrive at a project standard in the future, and would suggest that for the exercism/exercism.io repository we:
- remove all rules and restrictions from rubocop
- never block any pull requests for style reasons
- open an issue and discuss it, every time we find a style thing that we actually care about
- define a task to actually fix that one thing once we've got agreement
- add the rubocop rule for that style once the code base is clean
- enforce the new rule during code review once the cop has been added

See https://github.com/exercism/exercism.io/pull/3114 for context.

**Comment by kotp** [comment]
I can work on this, directly.  Another thing we can do is remove the travis-ci part so that it simply doesn't run.  Another option is to run it, but set the "fail level" higher so that just because there are cops that are present it doesn't return with a non-zero at the OS level.  Either may be a simple first step thing.  The rubocop related directives in the current code are "work done" style things, pointers to look at when we get back to that code if there is need for any churn.

**Comment by kytrinyx** [comment]
@kotp I think as a first step removing it from travis-ci is great. Then we could disable all of the cops and delete the TODOs and directives in the code.

Rather than have pointers in the code, I'd like to discuss potential refactorings here. I'm not quite sure how I think we should tackle refactorings for the Exercism codebase.

**Comment by Insti** [comment]
Anecdata: If I'm looking for a quick refactoring task I will grep the codebase for Rubocop cop disable comments.

I guess the fact there there are still a lot there mean the rate of progress using this method may not be a blocker for removing them, but a PR that just removes all the comments seems like throwing away useful information. Albeit information that can be recreated by running Rubocop on the codebase. 

I think I'm trying to say, leave the comments in until they are naturally removed by the evolution of the code.

**Comment by kytrinyx** [comment]
> I think I'm trying to say, leave the comments in until they are naturally removed by the evolution of the code.

Yeah, that seems fine to me.

**Comment by kotp** [comment]
As an example of what can be done, I just pushed up exercism/xruby#449 and it has the benefit of listing all cops, while disabling them all.  This way they can be activated as we find the styles that fit.

**Comment by kotp** [comment]
This also means that we can leave it in travis-ci (or set it as a no-op) so that it can be activated later, and it will do the right thing when we enable the ones that we want to enable as we want to enable them.

**Comment by kotp** [comment]
NB: Rubocop does have customizable system codes, we can report failures, without failing from CI viewpoint, I think, by setting it to always return 0 (unless actual program failure).

**Comment by tejasbubane** [comment]
I gave a nitpick [here](https://github.com/exercism/exercism.io/pull/3235#discussion_r87546439) which people seem to agree upon. There is a [cop for that](https://github.com/bbatsov/rubocop/blob/d4cfe7dfa06551ea2ccb9da64025272b9338dfaa/lib/rubocop/cop/rails/dynamic_find_by.rb). 

Should we start adding back those few cops that seem essential and that we all agree upon? If yes, how do we proceed?

**Comment by Insti** [comment]
Yes we should start adding them in.

Create a PR for the cop you want to add and see if anyone objects?

**Comment by kytrinyx** [comment]
Yeah, let's have that one.

**Comment by kotp** [comment]
@tejasbubane Please don't forget to mention this issue so we get a reference there and back.

**Comment by kytrinyx** [comment]
We've launched the new site, and for now we've not added rubocop. We may decide to judiciously add certain rules at a later date.
