### ISSUE TITLE
Is editorconfig worthwhile to start using?

### ISSUE THREAD

**Issue by dvberkel** [exercism/discussions#82]
[editorconfig](http://editorconfig.org/)

> helps developers define and maintain consistent coding styles between different editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems.

As a maintainer I now manually format the code. Editorconfig could help out here. I have some, but not much experience with EditorConfig. Does anybody want to share experiences?

**Comment by kytrinyx** [comment]
I've never used EditorConfig, but I have a couple of experiences that are kind of relevant... maybe :)

1. In Go in general, and on the Go track we use `gofmt`, which means that nobody ever has to think about formatting. It's _amazing_.
2. In Ruby there's a linter named `rubocop` which complains, but doesn't necessarily fix things. My experiences with this are very mixed.

I think this might be valuable, and should be decided on a track-by-track basis.

**Comment by dvberkel** [comment]
I very much like the idea of a compiler provided formatting tool. It totally side tracks often unhelpful discussion on style.

Unfortunately `gofmt` does not format JSON or Markdown. (Or does it? I am just guessing here, I have very little experience with `gofmt`.)

I will suggest using editorconfig for the OCaml track and get back with our experiences.

**Comment by kotp** [comment]
Rubocop and a git hook can enforce (a lot of things) but new contributors, unclear style decisions in the language, etc... definitely a mixed bag in Ruby.  I definitely agree about the distracting (at best) style discussions.  @dvberkel please do mention this discussion there so I can track that as well.  Working on some tactics for not only track but also exercism.io as an application.

**Comment by kytrinyx** [comment]
When we bootstrap a new language track, we automatically submit an issue that asks the track implementors/maintainers to consider whether there are linting tools that the project should use, and whether these should be suggested to people doing the exercises (the answer is not necessarily the same in both cases).

If you want to suggest improvements to the text of this generated issue (https://github.com/exercism/request-new-language-track/blob/master/CONSISTENCY.md), you can submit a pull request to that repository.

I'm going to go ahead and close this.
