### ISSUE TITLE
Explicitly look for new contributors for language tracks

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#85]
One thing that we've not done at all is to make an explicit effort to go look for people who would be interested in contributing to the language tracks on Exercism.

How would we go about doing this more strategically?

**Comment by kotp** [comment]
I have done this "lightly" by enlisting a few people to make their first issue, generally from inside the Exercism site itself.  This has, at a high rate of success, brought them to make their first PR.

I am pleased so far in how this has gone, and finding them on the site, seems like a natural place to start.  They are already interested at a "base level" or they would not be there making submissions, and responding to reviews.

Having the gitter room helps here as well, as you can have a more personal discussion, one that does not necessarily fit inside of the site.  Get to know people, a little more social, etc.  I still haven't been able to find the time to add the `xruby` room link on the web site yet, but people seem to be finding their way to the support and dev rooms.

I have even gotten a chance to talk with some of my favorite Exercismists (eh? wut?) there.

**Comment by tleen** [comment]
Closing in favor of overarching discussion in #191.
