### ISSUE TITLE
Link to great articles about test driven development

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#87]
We got a suggestion a while back to write documentation about TDD as part of the exercism documentation, and I've come to the conclusion that this is out of scope for the project.

That said, it would be lovely to be able to point people to awesome articles out on the web.

We could do it somewhere generally, or perhaps have language-specific links in the track documentation about testing or getting started.

**Comment by brandondees** [comment]
maybe something like [https://github.com/unicodeveloper/awesome-tdd](https://github.com/unicodeveloper/awesome-tdd)?

**Comment by tracypholmes** [comment]
Is there a specific range of time that you would want to stick to for this? Like articles/repos/etc. from the past 2 years or so?

**Comment by kytrinyx** [comment]
@tracypholmes That's a great question. I think that as long as the article doesn't feel old due to referencing outdated technologies, it would be fine to include it.

**Comment by kotp** [comment]
This may be a decent source of information for this issue.  https://github.com/unicodeveloper/awesome-tdd which is "Curated list of resources: books, videos, articles about using TDD".

**Comment by kytrinyx** [comment]
This is an area that we are working on in the new prototype: https://github.com/exercism/v2-feedback/blob/master/README.md

In particular, we have a ton of work we want to do with respect to resources that mentors can point people to as they help people work through the exercises.

I'm going to go ahead and close this, as we will be exploring this with a much broader perspective shortly.
