### ISSUE TITLE
Add support for meta-commentary on solutions

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#89]
There's an interesting idea that came up a while ago here: https://github.com/exercism/exercism.io/issues/2077

Let people add a commentary that would be about the exercise / their solution (not about an individual iteration). They could talk about what they learned, or summarize their process, or in some other way draw conclusions or muse about things at a high level.

**Comment by jtigger** [comment]
...visible to anyone who has "completed" that exercise, across all tracks?

I've been thinking about ideas like this in terms of improving the discoverability of quality commentary/conversation.  Imagine [Ward's wiki](http://wiki.c2.com/?PatternIndex) but organically arrived at (i.e. generalized *from* examples).

It is one of those potential goals of NLPing over comments: to determine, among "conversations" which are on a common topic (e.g. Balancing Readability with Expressiveness).

Starts to really hit home that Exercism is about the craft of programming, not just another toy problem site.  The latter is a series of exercises; the former is the conversation that results.

**Comment by kytrinyx** [comment]
> ...visible to anyone who has "completed" that exercise, across all tracks?

Yeah, you'd only see it if you can see the solution.

> Starts to really hit home that Exercism is about the craft of programming, not just another toy problem site.

Right. On the one hand, Exercism's sweet spot is "get fluent quickly in the basic syntax, standard libraries, and conventions of a language", but then layered on top of that is this deeper exploration of the craft of programming. The process, the insights. Developing the intuition about code smells and patterns and readability. And then layered on top of that again is the craft of communicating about code: code review, mentorship, and disagreeing without being disagreeable.

**Comment by kytrinyx** [comment]
This is being tracked as a feature for the nextercism prototype. Thanks @jtigger 🌷
