### ISSUE TITLE
Implement granular and flexible subscriptions and notifications

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#91]
The goal here is to let people know that there's interesting new stuff, which would likely mean that they participate more frequently and for a longer amount of time, which means that they'd probably get a lot more out of Exercism (both in terms of learning and enjoyment).

This would mean integrating with a proper email platform.

Some examples of things people might want to subscribe to:
- new exercises to solve in a language track
- new solutions in a language track
- new solutions on a particular exercise in a language track
- new solutions by a particular user
- ...

We might also consider various types of digests of recent/interesting activity.

**Comment by brandondees** [comment]
FWIW I'll note that not getting external notifications is the main thing keeping me from being much more active with Exercism. I'd love to be able to get a digest email of team activity, and immediate emails corresponding to the existing site notifications. Optionally it might be nice to have a service worker and browser-based toast/popup notifications as well. That's all just for improving engagement and responsiveness for existing activities on the platform, but I would also love to see some additional nudges periodically to get back into regular practice with new exercises. The typical "we haven't seen you in a while" and "looks like you started but didn't finish X, need some help?" type things that are common for customer retention purposes in various places.

**Comment by kytrinyx** [comment]
@brandondees Thanks! Yeah we're going to be rethinking notifications from scratch as part of our design reboot #113

**Comment by nilbus** [comment]
@kytrinyx in https://github.com/exercism/exercism.io/issues/2487:
> I removed all the email functionality. It was an unconfigurable firehose.

Do you remember roughly what the monthly volume was? There are [various services][1] that offer up to 100,000 or 150,000 messages per month (small firehose? 😉 ) for free. [ElasticEmail][2] offers the most but would benefit from porting a Ruby client. This could be a useful reference when it's time to choose an email provider.

[1]: https://github.com/ripienaar/free-for-dev#email
[2]: https://elasticemail.com/pricing/

**Comment by kytrinyx** [comment]
@nilbus I don't recall what the monthly volume was, but the cost was around $80/month. ElasticEmail looks very reasonable.

**Comment by nilbus** [comment]
​Based on current sendgrid pricing, that could have been 150–200k
emails/month.

With more granular emails and digests, we might have lower volume. Exercism
has also grown in the last 1.5 years.

**Comment by kytrinyx** [comment]
We're tracking this separately for the nextercism prototype. I'm going to go ahead and close this.
