### ISSUE TITLE
The purpose of `.version` file

### ISSUE THREAD

**Issue by kotp** [exercism/discussions#93]
I have started noticing that some people are reading too much into the `.version` file that they receive on their file systems as it pertains to the BookKeeping and they are reading that file rather than giving a literal version that we can see in the iteration.

This goes against the purpose of communicating the version of the test that the solution solves against.  Should it be delivered to the participant?

**Comment by Insti** [comment]
No the .version file should not be delivered.

I also think that expressing the version in the solution through anything other than an optional comment is overkill, and the BookKeeping module we use in xruby is way more trouble than it's worth.

**Comment by kotp** [comment]
I have noticed a drop in "Your solution does not pass the tests" comments when the BookKeeping module is used as it is intended.  I think it is more likely to be used when it "nags" you with a failing test, and to suggest that someone mentions their version, consistently.  Especially since a lot of exercises are "version 0" at the moment.

What "trouble" have you experienced with the BookKeeping module?

**Comment by kytrinyx** [comment]
We were using it as a simple way to know the current version. But if we're consistent about naming, we can simply read the existing file before writing the new one, and parse out the version constant.

**Comment by Insti** [comment]
Creation of the un-served per-exercise `.meta` directory will mean that the `.version` file can live there and not be served to the users.
(A PR to add this is on my todo list.)

**Comment by petertseng** [comment]
Y'all dealt with this in https://github.com/exercism/xruby/pull/502
