### ISSUE TITLE
Normalize files used to compile exercise READMEs

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#95]
Right now each exercise README is compiled from:

* (in exercism/x-common) - exercises/$SLUG/description.md (basic problem specification)
* (in exercism/x$TRACK_ID) - SETUP.md (a reminder about how to run the tests)
* (in exercism/x$TRACK_ID) - exercises/$SLUG/HINTS.md (any hints about the specific exercise)

`SETUP.md` is a terrible name, since it sounds like it should be a one-time thing about how to set the track up. If you're doing all the exercises in a track, this will get annoying.

I think `HINTS.md` is a good name for the exercise hints.

Any suggestions for what to name `SETUP.md` to be less confusing?

**Comment by Insti** [comment]
I think it would be better if SETUP.md were moved into the /exercises subdiretory.

`exercism/x$TRACK_ID/exercises/SETUP.md`

This would remove a bit of the confusion.

Ordered brainstorming for a new name: 
```
PER_EXERCISE_README.md (worst)
TESTING.md
SOLVING.md
HINTS.md
INFO.md
INFORMATION.md
ADDITIONAL_INFORMATION.md
ADDITIONAL_DESCRIPTION.md
TRACK_DESCRIPTION.md
TRACK_HINTS.md (best)
```
I think I like `TRACK_HINTS.md` best at the moment.

**Comment by dvberkel** [comment]
I think I like `TRACK_HINTS.md` as well

**Comment by kytrinyx** [comment]
Yeah, of all the various suggestions so far, I think `TRACK_HINTS.md` is good.

It is consistent with the fact that this is _hints_, without the potential confusion of having exactly the same file name as the `exercises/:slug/HINTS.md` file.

I'm going to open a tracking issue in the exercism repo with an explanation of the problem and the fix and a checklist of how to get there.

**Comment by kytrinyx** [comment]
Ok, the new issue is here: https://github.com/exercism/exercism.io/issues/3240
