### ISSUE TITLE
Exercism in the Wild: workshops, meetups, pairing, mentorship

### ISSUE THREAD

**Issue by kytrinyx** [exercism/discussions#98]
I'm curious to hear from people who have used Exercism or Exercism exercises when mentoring others, or as a part of meetups or workshops or general pairing sessions.

I've created a survey: https://docs.google.com/forms/d/e/1FAIpQLSdP8rE0gRaoKz81Krem4fCznm9J6uR377oHbMmL6DHBYHv84g/viewform

If you've got experience, please, please respond! I'd love to hear from you. If you know of someone who has experience, please encourage them to reply to the survey.

**Comment by Insti** [comment]
It wants my github username to be an email address :confused:

**Comment by kytrinyx** [comment]
Dang. My bad. I've fixed it. Thanks for reporting it!

**Comment by kytrinyx** [comment]
I got a few responses to this. If/when I'm ready to start tackling a task force to help create a playbook for using Exercism at meetups or for workshops, I'll be contacting the people who responded.
