### ISSUE TITLE
Exercism promotional materials? 

### ISSUE THREAD

**Issue by Insti** [exercism/discussions#99]
Thinking about [Exercsim in the wild](http://tinyletter.com/exercism/letters/exercism-in-the-wild-how-is-exercism-being-used-in-face-to-face-interactions)

I'd like to be able to have Exercism cards and/or stickers to be able to give out to people.

Does such a thing already exist?
Are there source graphic files I could just send to my local printer?
If not maybe we need a promotional materials repository?

**Comment by dvberkel** [comment]
:+1:  for stickers. I would love to have them

**Comment by ProgrammingFuad** [comment]
I would love a sticker as well! 

I havent seen much Promotional material anywhere this sounds like a great idea.

**Comment by kytrinyx** [comment]
> If not maybe we need a promotional materials repository?

Yes! We absolutely need this.

We have some .ai files with the logo in it (as SVG) which could be used to create things. I need help from someone who knows how to deal with SVGs (and who has Adobe Illustrator so we can extract them) to help me out with this.

We don't have any promotional materials, but I would love to make it happen.

**Comment by spuder** [comment]
We recently purchased company stickers from here: 

https://www.stickermule.com/

**Comment by IanWhitney** [comment]
Would prefer not stickermule. Just giving them money probably violates our COC. Some details here: https://twitter.com/monteiro/status/785579905601839104 More available if you're interested.

**Comment by spuder** [comment]
If I understand correctly from that link. The CEO of sticker mule supported a particular political candidate. 

The political candidate a person supports is a _personal_ choice. Blacklisting a _business_ because of the founder's _personal_ belief is a bit extreme. In fact there is a word for that, it is called '[persecution](http://www.dictionary.com/browse/persecute)'. Surely you weren't suggesting excercism.io should persecute that company because of whom their CEO voted for. That would be crazy and would mean you couldn't do business with 50% of stores. 

Obviously there must be some 'non political' reason for not using that company. In that case, [stickergiant](https://www.stickergiant.com/?c=637832838&ag=31566570533&kw=sticker%20giant&gclid=Cj0KEQiAperBBRDfuMf72sr56fIBEiQAPFXszQYCGfljJjYSAMy-iBh3x4tp1opowProTpa_pDIsSlcaAra78P8HAQ) could also get excercism stickers starting at about $0.56 each.

**Comment by IanWhitney** [comment]
Don't put words in my mouth, @spuder.

**Comment by mienaikage** [comment]
Let's not jump to conclusions. @IanWhitney, would you care to elaborate/give more info for clarity?

Choosing not to do business with a particular company would not be persecution, as we would in no way be pursuing them.

**Comment by Insti** [comment]
Please create a new issue for political discussion. 
It would be nice to be able to use this one for discussing Exercism promotional materials.
At this point we do not even have any stickers, so choosing where to print them is completely irrelevant right now.

**Comment by troubalex** [comment]
> I need help from someone who knows how to deal with SVGs (and who has Adobe Illustrator so we can extract them) to help me out with this.

I can probably help out here, @kytrinyx.

**Comment by kytrinyx** [comment]
@troubalex that's awesome. Let me send you a link to the .ia files I have, and you can see if there's anything we can extract.

**Comment by Insti** [comment]
Maybe another thread required: Are we married to the current horned e logo?

It doesn't really say to me 'the friendly way to chat about code.'

Logos are harder than names.

**Comment by kotp** [comment]
It should say "The devil is in the details - Exercism".

**Comment by troubalex** [comment]
Turns out the logo file in SVG is here: https://github.com/exercism/exercism.io/blob/master/public/icons/logo.svg

Let me know if you want any help in preparing something for stickers. Although, a real graphic designer might know more about these things than me.

**Comment by kytrinyx** [comment]
I'm not married to anything. I really like "the devil is in the details", but I took it off the front page because it's not immediately clear what I mean by that. I think it would work better for swag. I don't know.

@troubalex I have been wanting a sticker that is a black circle with a cut-out of the horned e so that I could put it over the apple on my macbook and have the e light up. Is that something you'd know how to make the graphic for?

**Comment by Insti** [comment]
Lower-case `e` is a hard letter to create a cutout for topologically speaking.

**Comment by troubalex** [comment]
I made a cutout version of the logo. The SVG file lives here: https://www.dropbox.com/s/lyhdwunefxleau1/logo_cutout.svg?dl=0

@Insti 
> Lower-case e is a hard letter to create a cutout for, topologically speaking.

That's what I thought too. Stickermule offers the option to print on clear vinyl though which should do the trick. I'd assume other sticker providers do the same.

**Comment by kotp** [comment]
![Cutout version of logo](https://photos-3.dropbox.com/t/2/AADG8zSkGY-mYOQN6GoCQVJwszT7v6vNFHONYtTjvSfRmA/12/1849057/png/32x32/3/1480701600/0/2/logo_cutout.svg/EL2qvgEY2amXRSACKAI/FJ8fvpbqmLcM3UOUVidShIAJVH8BaXZ-X679YDMviY0?size_mode=3&dl=0&size=2048x1536)
Here for convenience.  @troubalex  let me know if you need this not linked directly (unsure link limits, etc).

**Comment by troubalex** [comment]
Is this still SVG? I tried uploading that directly here but Github wasn't happy.

**Comment by kotp** [comment]
No, it is here for display purposes.  It is linked to it, but translated in transport.

**Comment by kytrinyx** [comment]
That. Is. Awesome! (screenshot of the svg below)

<img width="178" alt="screen shot 2016-12-04 at 8 44 10 am" src="https://cloud.githubusercontent.com/assets/276834/20867289/e3725a32-b9fd-11e6-814f-54ce0415c92b.png">

**Comment by troubalex** [comment]
The e looks off center. I'll give it another shot.

**Comment by kytrinyx** [comment]
@troubalex it might just be the screenshot.

**Comment by troubalex** [comment]
I moved it up a bit. Good enough.

![logo_cutout](https://cloud.githubusercontent.com/assets/1913615/20868127/291dddbc-ba54-11e6-9e8b-1f3a39ed6721.png)

The Dropbox link further up is up to date.

**Comment by kytrinyx** [comment]
Love it, thanks!

**Comment by kytrinyx** [comment]
I've created a repo for stuff like this: https://github.com/exercism/marketing

I added the exercism logo, and this cutout.

**Comment by alebaffa** [comment]
oh, please create also a red version :red_circle: . It's so cool! :smiley:

**Comment by Insti** [comment]
Red, or "Exercism pink"?

**Comment by tejasbubane** [comment]
Here is one with the `exercism pink` https://www.dropbox.com/s/1yd8fupjkssszgp/logo_cutout.svg?dl=0 @alebaffa 
`svg`s are nice to manipulate. Just replace the color in text. 😄

**Comment by kytrinyx** [comment]
I've added it to the repo: https://github.com/exercism/marketing/tree/master/stickers

We'll totally take PRs to that repo, by the way :)

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this. I still think swag/promotional materials is a great idea, but I want to table the discussion until we have a redesign, as this could influence the design of the swag significantly.
